package assertionauthor_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/bharm16/readmit/internal/assertion"
	"github.com/bharm16/readmit/internal/assertionauthor"
)

func TestImportRoundTripsEveryOperatorInTheFixture(t *testing.T) {
	data, err := os.ReadFile("../../testdata/fixtures/assertion-set.json")
	if err != nil {
		t.Fatal(err)
	}
	original, err := assertion.Decode(data)
	if err != nil {
		t.Fatal(err)
	}
	draft, err := assertionauthor.ImportDocument(data)
	if err != nil {
		t.Fatal(err)
	}
	if draft.Name != original.Name || len(draft.Assertions) != len(original.Assertions) {
		t.Fatalf("import lost the set: name=%q assertions=%d", draft.Name, len(draft.Assertions))
	}
	generated, err := assertionauthor.Generate(draft)
	if err != nil {
		t.Fatal(err)
	}
	again, err := assertion.Decode(generated)
	if err != nil {
		t.Fatalf("generated bytes are not an assertion set: %v", err)
	}
	if again.Name != original.Name || len(again.Assertions) != len(original.Assertions) {
		t.Fatalf("round trip lost clauses: %+v", again)
	}
	seen := make(map[assertion.Operator]bool, len(again.Assertions))
	for _, item := range again.Assertions {
		seen[item.Operator] = true
	}
	for _, operator := range []assertion.Operator{
		assertion.FieldEquals, assertion.FieldNotEquals, assertion.FieldState,
		assertion.TextMatches, assertion.NumericRange, assertion.NumericTolerance,
		assertion.DateWindow, assertion.ValuesEqual, assertion.RecordCount,
		assertion.RecordsUnique, assertion.RecordsContain, assertion.RecordsOrdered,
		assertion.RecordMultiplicity, assertion.RecordsAbsent, assertion.RecordKeyMatches,
		assertion.RecordsChanged,
	} {
		if !seen[operator] {
			t.Errorf("fixture round trip dropped operator %q", operator)
		}
	}
}

func TestGenerateRefusesEmptyNameOrAssertions(t *testing.T) {
	draft := assertionauthor.NewDraft()
	if _, err := assertionauthor.Generate(draft); err == nil {
		t.Fatal("an empty draft generated a set")
	}
	named, err := draft.SetName("Synthetic expectations")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := assertionauthor.Generate(named); err == nil {
		t.Fatal("a nameless-assertions draft generated a set")
	}
}

func TestImportRefusesUnknownVersionsAndOperators(t *testing.T) {
	if _, err := assertionauthor.ImportDocument([]byte(`{"schema":"readmit-assertion-set/v2","name":"x","assertions":[]}`)); err == nil {
		t.Fatal("accepted an unknown assertion set version")
	}
	bad := []byte(`{
  "schema": "readmit-assertion-set/v1",
  "name": "bad",
  "assertions": [{
    "id": "shell",
    "operator": "shell",
    "subject": {"field": {"scope": "observed", "message": "s0001-e000001", "selector": "MSA-1"}},
    "when": null,
    "expected": {"field": {"state": "present", "text": "AA"}}
  }]
}`)
	if _, err := assertionauthor.ImportDocument(bad); err == nil {
		t.Fatal("accepted an unknown operator")
	}
}

func TestGenerateRefusesAMalformedClause(t *testing.T) {
	draft := assertionauthor.NewDraft()
	draft, err := draft.SetName("Broken pairing")
	if err != nil {
		t.Fatal(err)
	}
	holds := true
	draft, err = draft.SetAssertions([]assertionauthor.Clause{{
		ID: "wrong", Operator: assertion.FieldEquals,
		Subject:  assertion.Subject{Field: &assertion.FieldRef{Scope: "observed", Message: "s0001-e000001", Selector: "MSA-1"}},
		Expected: assertion.Expected{Holds: &holds},
	}})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := assertionauthor.Generate(draft); err == nil {
		t.Fatal("accepted a field_equals paired with holds")
	}
}

func TestSaveWritesANewEntryAndReturnsItsIdentity(t *testing.T) {
	data, err := os.ReadFile("../../testdata/fixtures/assertion-set.json")
	if err != nil {
		t.Fatal(err)
	}
	draft, err := assertionauthor.ImportDocument(data)
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	saved, err := assertionauthor.Save(root, draft, "expectations.json")
	if err != nil {
		t.Fatal(err)
	}
	if saved.Output != "expectations.json" || saved.Identity == "" {
		t.Fatalf("save did not report the written entry: %+v", saved)
	}
	written, err := os.ReadFile(filepath.Join(root, saved.Output))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := assertion.Decode(written); err != nil {
		t.Fatalf("written file is not an assertion set: %v", err)
	}
	if _, err := assertionauthor.Save(root, draft, "expectations.json"); err == nil {
		t.Fatal("save replaced an existing entry")
	}
}

func TestDecodeDraftRefusesUnknownMembers(t *testing.T) {
	if _, err := assertionauthor.DecodeDraft([]byte(`{
  "schema": "readmit-assertion-set-draft/v1",
  "name": "n",
  "assertions": [],
  "deadline": "5s"
}`)); err == nil {
		t.Fatal("accepted an unknown draft member")
	}
	if _, err := assertionauthor.DecodeDraft([]byte(`{"schema":"readmit-assertion-set-draft/v2","name":"","assertions":[]}`)); err == nil {
		t.Fatal("accepted an unknown draft version")
	}
}
