package main

import (
	"bytes"
	"encoding"
	"encoding/json"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"
)

// modulePath is the import path of the readmit module. Every Go type the
// facade reaches is named relative to it, in errors and in the declarations'
// comments.
const modulePath = "github.com/bharm16/readmit"

// object is one Go value the shell binds. Wails publishes each exported method
// of its pointer type at window.go.<package>.<type>.<method>; facade is the
// TypeScript interface that declares those methods.
type object struct {
	value  any
	facade string
}

// generator turns the bound objects' method signatures, and every type those
// signatures reach, into TypeScript declarations of what encoding/json puts on
// the wire. Wails marshals every result and unmarshals every argument with
// encoding/json, so its rules — not the Go types' spelling — decide each
// member's name, whether it can be absent and whether it can be null.
type generator struct {
	root     string // the repository root, where each package's source is read
	names    names
	declared map[reflect.Type]string // the TypeScript name each declared type took
	owners   map[string]reflect.Type // the Go type behind each TypeScript name
	decls    map[string]string       // each declaration's text, by TypeScript name
	sources  map[string]*source      // parsed Go source, by import path
}

// generate returns the declarations of every object's methods and of every
// type they reach, ordered by name so the output depends only on the Go
// declarations.
func generate(root string, objects []object, n names) ([]byte, error) {
	g := &generator{
		root:     root,
		names:    n,
		declared: map[reflect.Type]string{},
		owners:   map[string]reflect.Type{},
		decls:    map[string]string{},
		sources:  map[string]*source{},
	}
	var facades []string
	for _, o := range objects {
		facade, err := g.facade(o)
		if err != nil {
			return nil, err
		}
		facades = append(facades, facade)
	}
	for _, name := range slices.Sorted(maps.Keys(n.vocabularies)) {
		if err := g.vocabulary(name, n.vocabularies[name]); err != nil {
			return nil, err
		}
	}
	var out bytes.Buffer
	out.WriteString(header)
	for _, name := range slices.Sorted(maps.Keys(g.decls)) {
		out.WriteString("\n")
		out.WriteString(g.decls[name])
	}
	for _, facade := range facades {
		out.WriteString("\n")
		out.WriteString(facade)
	}
	return out.Bytes(), nil
}

const header = `// Code generated by "go run ./bindgen" in desktop; DO NOT EDIT.
//
// The TypeScript declarations of the two Go objects the desktop shell binds:
// internal/desktop.App, published at window.go.desktop.App and declared here
// as Facade, and desktop/hubadmin.Admin, published at window.go.hubadmin.Admin
// and declared as HubAdminFacade. They are derived from the methods' Go
// signatures and every type those reach, as encoding/json carries them across
// Wails' boundary, so each is exactly what crosses it:
//
// - a member is named by its json tag, and is optional exactly when the tag
//   says omitempty or omitzero, because Go then leaves it out;
// - a pointer that is not optional is the pointed-to type or null;
// - a named Go string type that declares constants is the union of their
//   values, the empty string only when a constant declares it, and any other
//   string is a string;
// - a slice is an array and a map a record, as Wails' own bindings declare
//   them, though Go sends null for a nil one;
// - a time is its RFC 3339 string, and raw JSON is unknown;
// - the choices a panel offers for a member Go carries as a plain string are
//   the union of the Go constants that name them.
//
// Each declaration names the Go type it comes from, which carries its
// documentation. bindings.ts holds the hand-written call policy over these
// declarations; regenerate this file whenever a Go type the facade reaches
// changes, and never edit it.
`

// facade declares one bound object's methods and, through them, every type
// their signatures reach.
func (g *generator) facade(o object) (string, error) {
	bound := reflect.TypeOf(o.value)
	if bound.Kind() != reflect.Pointer || bound.Elem().Kind() != reflect.Struct {
		return "", fmt.Errorf("%s: a bound object is a pointer to a struct, not %s", o.facade, bound)
	}
	if bound.NumMethod() == 0 {
		return "", fmt.Errorf("%s: %s binds no method", o.facade, goName(bound.Elem()))
	}
	src, err := g.source(bound.Elem().PkgPath())
	if err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "/** The methods Wails binds for %s. */\n", goName(bound.Elem()))
	fmt.Fprintf(&b, "export interface %s {\n", o.facade)
	for i := range bound.NumMethod() {
		method := bound.Method(i)
		signature, err := g.method(method, src.params(bound.Elem().Name(), method.Name))
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", goName(bound.Elem()), method.Name, err)
		}
		fmt.Fprintf(&b, "  %s%s;\n", method.Name, signature)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

var errorType = reflect.TypeFor[error]()

// method declares one bound method as Wails calls it: each parameter is one
// argument decoded by encoding/json, and the promise settles with the first
// result, or rejects with the error the method returned last.
func (g *generator) method(method reflect.Method, paramNames []string) (string, error) {
	signature := method.Type
	var params []string
	for i := 1; i < signature.NumIn(); i++ {
		if signature.IsVariadic() && i == signature.NumIn()-1 {
			return "", errors.New("Wails cannot call a variadic method")
		}
		t, err := g.expr(signature.In(i))
		if err != nil {
			return "", fmt.Errorf("parameter %d: %w", i, err)
		}
		name := fmt.Sprintf("arg%d", i)
		if i-1 < len(paramNames) && paramNames[i-1] != "" && paramNames[i-1] != "_" && !reserved[paramNames[i-1]] {
			name = paramNames[i-1]
		}
		params = append(params, name+": "+t)
	}
	outs := signature.NumOut()
	if outs > 0 && signature.Out(outs-1) == errorType {
		outs--
	}
	result := "void"
	switch outs {
	case 0:
	case 1:
		t, err := g.expr(signature.Out(0))
		if err != nil {
			return "", fmt.Errorf("result: %w", err)
		}
		result = t
	default:
		return "", errors.New("Wails returns one result and an optional error, not more")
	}
	return "(" + strings.Join(params, ", ") + "): Promise<" + result + ">", nil
}

// reserved are the words TypeScript refuses as a parameter name.
var reserved = map[string]bool{
	"break": true, "case": true, "catch": true, "class": true, "const": true, "continue": true,
	"debugger": true, "default": true, "delete": true, "do": true, "else": true, "enum": true,
	"export": true, "extends": true, "false": true, "finally": true, "for": true, "function": true,
	"if": true, "import": true, "in": true, "instanceof": true, "new": true, "null": true,
	"return": true, "super": true, "switch": true, "this": true, "throw": true, "true": true,
	"try": true, "typeof": true, "var": true, "void": true, "while": true, "with": true,
	"implements": true, "interface": true, "let": true, "package": true, "private": true,
	"protected": true, "public": true, "static": true, "yield": true, "await": true,
}

var (
	timeType       = reflect.TypeFor[time.Time]()
	rawMessageType = reflect.TypeFor[json.RawMessage]()
	jsontextType   = reflect.TypeFor[jsontext.Value]()
	marshalerType  = reflect.TypeFor[json.Marshaler]()
	textType       = reflect.TypeFor[encoding.TextMarshaler]()
	untextType     = reflect.TypeFor[encoding.TextUnmarshaler]()
)

// expr is the TypeScript type of a value of t as encoding/json writes and
// reads it.
func (g *generator) expr(t reflect.Type) (string, error) {
	if t.Kind() == reflect.Pointer {
		elem, err := g.expr(t.Elem())
		if err != nil {
			return "", err
		}
		return elem + " | null", nil
	}
	switch t {
	case timeType:
		return "string", nil
	case rawMessageType, jsontextType:
		return "unknown", nil
	}
	if encodesItself(t) {
		return "", fmt.Errorf("%s marshals itself, so its JSON is not its Go shape; declare what it writes in bindgen", goName(t))
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return g.enum(t)
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			// encoding/json writes a byte slice as its base64 string.
			return "string", nil
		}
		return g.array(t.Elem())
	case reflect.Array:
		return g.array(t.Elem())
	case reflect.Map:
		switch t.Key().Kind() {
		case reflect.String, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		default:
			return "", fmt.Errorf("%s is a map encoding/json cannot key by %s", t, t.Key())
		}
		elem, err := g.expr(t.Elem())
		if err != nil {
			return "", err
		}
		return "Record<string, " + elem + ">", nil
	case reflect.Struct:
		if t.Name() == "" {
			members, err := g.members(t)
			if err != nil {
				return "", err
			}
			return "{ " + strings.Join(members, "; ") + " }", nil
		}
		return g.declare(t)
	case reflect.Interface:
		if t.NumMethod() > 0 {
			return "", fmt.Errorf("encoding/json cannot decode into the interface %s", t)
		}
		return "unknown", nil
	}
	return "", fmt.Errorf("encoding/json cannot carry %s", t)
}

// encodesItself reports whether encoding/json hands t to its own code rather
// than writing its shape. A type that only decodes itself is read as it is
// written: the strict readers of ADR-0003 refuse what their shape does not
// declare, they do not read another shape.
func encodesItself(t reflect.Type) bool {
	for _, iface := range []reflect.Type{marshalerType, textType, untextType} {
		if t.Implements(iface) || reflect.PointerTo(t).Implements(iface) {
			return true
		}
	}
	return false
}

func (g *generator) array(elem reflect.Type) (string, error) {
	t, err := g.expr(elem)
	if err != nil {
		return "", err
	}
	if strings.Contains(t, " | ") {
		t = "(" + t + ")"
	}
	return t + "[]", nil
}

// enum declares a named string type as the union of the constants its package
// declares of it. A string with no declared constants is any string.
func (g *generator) enum(t reflect.Type) (string, error) {
	if t.Name() == "" || t.PkgPath() == "" {
		return "string", nil
	}
	if name, ok := g.declared[t]; ok {
		return name, nil
	}
	src, err := g.source(t.PkgPath())
	if err != nil {
		return "", err
	}
	values, err := g.constants(src, t.Name())
	if err != nil {
		return "", fmt.Errorf("%s: %w", goName(t), err)
	}
	if len(values) == 0 {
		return "string", nil
	}
	name, err := g.claim(t)
	if err != nil {
		return "", err
	}
	g.decls[name] = union(goName(t), name, values)
	return name, nil
}

// union is the declaration of a string union, on one line when it fits.
func union(origin, name string, values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = strconv.Quote(value)
	}
	decl := fmt.Sprintf("export type %s = %s;", name, strings.Join(quoted, " | "))
	if len(decl) > 100 {
		decl = fmt.Sprintf("export type %s =\n  | %s;", name, strings.Join(quoted, "\n  | "))
	}
	return fmt.Sprintf("/** %s */\n%s\n", origin, decl)
}

// vocabulary declares the choices a panel offers for a member Go carries as a
// plain string, as the union of the Go constants that name them: every string
// constant of the const block that declares the one constant named, so a
// choice added there is a choice the panel must handle, or exactly the
// constants named when a block also declares other things.
func (g *generator) vocabulary(name string, constants []string) error {
	if _, taken := g.owners[name]; taken {
		return fmt.Errorf("the vocabulary %s is named like a declared Go type", name)
	}
	var values []string
	for _, reference := range constants {
		at := strings.LastIndex(reference, ".")
		if at < 0 {
			return fmt.Errorf("the vocabulary %s names %q, which is not a package's constant", name, reference)
		}
		src, err := g.source(modulePath + "/" + reference[:at])
		if err != nil {
			return fmt.Errorf("the vocabulary %s: %w", name, err)
		}
		constant, ok := src.consts[reference[at+1:]]
		if !ok {
			return fmt.Errorf("the vocabulary %s names %s, which its package does not declare as a constant", name, reference)
		}
		members := []string{reference[at+1:]}
		if len(constants) == 1 {
			members = src.blocks[constant.block]
		}
		for _, member := range members {
			c := src.consts[member]
			value, err := g.value(src, c, c.value, 0)
			if err != nil {
				return fmt.Errorf("the vocabulary %s: constant %s: %w", name, member, err)
			}
			if !slices.Contains(values, value) {
				values = append(values, value)
			}
		}
	}
	origin := strings.Join(constants, ", ")
	if len(constants) == 1 {
		origin += " and the constants declared with it"
	}
	g.decls[name] = union(origin, name, values)
	return nil
}

// declare declares a named struct type as an interface of its JSON members.
func (g *generator) declare(t reflect.Type) (string, error) {
	if name, ok := g.declared[t]; ok {
		return name, nil
	}
	name, err := g.claim(t)
	if err != nil {
		return "", err
	}
	members, err := g.members(t)
	if err != nil {
		return "", err
	}
	var body strings.Builder
	for _, m := range members {
		body.WriteString("  " + m + ";\n")
	}
	g.decls[name] = fmt.Sprintf("/** %s */\nexport interface %s {\n%s}\n", goName(t), name, body.String())
	return name, nil
}

// members declares a struct's JSON members, in field order. A member two
// fields would declare, whether declared directly or promoted from an embedded
// struct, is refused: encoding/json keeps one of them by rules bindgen does not
// model.
func (g *generator) members(t reflect.Type) ([]string, error) {
	fields, err := g.fields(t)
	if err != nil {
		return nil, err
	}
	declared := make(map[string]bool, len(fields))
	members := make([]string, 0, len(fields))
	for _, f := range fields {
		if declared[f.name] {
			return nil, fmt.Errorf("%s declares the member %q twice; encoding/json keeps only one: rename one", goName(t), f.name)
		}
		declared[f.name] = true
		members = append(members, f.decl)
	}
	return members, nil
}

// jsonField is one JSON member of a struct: its name on the wire and its
// declaration.
type jsonField struct{ name, decl string }

// fields lists a struct's JSON members in field order. An untagged embedded
// struct's members are the embedding struct's own, in its place, as
// encoding/json promotes them; any other embedded field is refused.
func (g *generator) fields(t reflect.Type) ([]jsonField, error) {
	var fields []jsonField
	for i := range t.NumField() {
		field := t.Field(i)
		if field.Anonymous {
			if _, tagged := field.Tag.Lookup("json"); tagged || field.Type.Kind() != reflect.Struct || !field.IsExported() {
				return nil, fmt.Errorf("%s embeds %s; bindgen promotes the members of an untagged embedded struct and nothing else: name the member", goName(t), field.Type)
			}
			promoted, err := g.fields(field.Type)
			if err != nil {
				return nil, err
			}
			fields = append(fields, promoted...)
			continue
		}
		if !field.IsExported() {
			continue
		}
		tag := field.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name, options, _ := strings.Cut(tag, ",")
		if name == "" {
			name = field.Name
		}
		optional := false
		for option := range strings.SplitSeq(options, ",") {
			switch option {
			case "omitempty", "omitzero":
				optional = true
			case "":
			default:
				return nil, fmt.Errorf("%s.%s: the json option %q is not modeled by bindgen", goName(t), field.Name, option)
			}
		}
		at := field.Type
		if optional && at.Kind() == reflect.Pointer {
			// An absent member, not null: Go leaves a nil pointer out.
			at = at.Elem()
		}
		expr, err := g.expr(at)
		if err != nil {
			return nil, fmt.Errorf("%s.%s: %w", goName(t), field.Name, err)
		}
		mark := ""
		if optional {
			mark = "?"
		}
		fields = append(fields, jsonField{name: name, decl: member(name) + mark + ": " + expr})
	}
	return fields, nil
}

// member is a JSON member name as a TypeScript property name.
func member(name string) string {
	for i, r := range name {
		if !(r == '_' || r == '$' || 'a' <= r && r <= 'z' || 'A' <= r && r <= 'Z' || i > 0 && '0' <= r && r <= '9') {
			return strconv.Quote(name)
		}
	}
	return name
}

// claim gives t its TypeScript name and refuses a second Go type the same
// name.
func (g *generator) claim(t reflect.Type) (string, error) {
	name := g.names.of(t)
	if other, ok := g.owners[name]; ok && other != t {
		return "", fmt.Errorf("%s and %s would both be declared as %s; name one of them in names.go", goName(other), goName(t), name)
	}
	g.owners[name] = t
	g.declared[t] = name
	return name, nil
}

// goName names a Go type by its import path relative to the readmit module.
func goName(t reflect.Type) string {
	if t.PkgPath() == "" {
		return t.String()
	}
	return relative(t.PkgPath()) + "." + t.Name()
}

// relative is an import path relative to the readmit module.
func relative(importPath string) string {
	return strings.TrimPrefix(strings.TrimPrefix(importPath, modulePath), "/")
}

// source is the parsed Go source of one package: the constants it declares
// and its methods' parameter names, neither of which reflection reports.
type source struct {
	name   string // the package clause
	files  []*ast.File
	consts map[string]constant
	order  []string   // constant names in file and declaration order
	blocks [][]string // constant names by the const declaration that declares them
}

// constant is one declared constant, with the file's imports its value may
// refer through and the const declaration it belongs to.
type constant struct {
	typ, value ast.Expr
	imports    []*ast.ImportSpec
	block      int
}

// source parses a package of this repository once. A package outside it is
// declared only through the fixed shapes of expr.
func (g *generator) source(importPath string) (*source, error) {
	if src, ok := g.sources[importPath]; ok {
		return src, nil
	}
	rel, ok := strings.CutPrefix(importPath, modulePath)
	if !ok || rel != "" && !strings.HasPrefix(rel, "/") {
		return nil, fmt.Errorf("%s is outside the readmit module, so its source cannot be read", importPath)
	}
	dir := filepath.Join(g.root, filepath.FromSlash(rel))
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	src := &source{consts: map[string]constant{}}
	fset := token.NewFileSet()
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || path.Ext(name) != ".go" || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		src.name = file.Name.Name
		src.files = append(src.files, file)
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.CONST {
				continue
			}
			// A spec with neither type nor values repeats the one before it.
			var typ ast.Expr
			var values []ast.Expr
			block := len(src.blocks)
			src.blocks = append(src.blocks, nil)
			for _, spec := range gen.Specs {
				vs := spec.(*ast.ValueSpec)
				if vs.Type != nil || len(vs.Values) > 0 {
					typ, values = vs.Type, vs.Values
				}
				for i, ident := range vs.Names {
					if ident.Name == "_" || i >= len(values) {
						continue
					}
					src.consts[ident.Name] = constant{typ: typ, value: values[i], imports: file.Imports, block: block}
					src.order = append(src.order, ident.Name)
					src.blocks[block] = append(src.blocks[block], ident.Name)
				}
			}
		}
	}
	g.sources[importPath] = src
	return src, nil
}

// params names the parameters of the method of the receiver type, in order.
func (s *source) params(receiver, method string) []string {
	for _, file := range s.files {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || fn.Name.Name != method || len(fn.Recv.List) != 1 {
				continue
			}
			recv := fn.Recv.List[0].Type
			if star, ok := recv.(*ast.StarExpr); ok {
				recv = star.X
			}
			if ident, ok := recv.(*ast.Ident); !ok || ident.Name != receiver {
				continue
			}
			var names []string
			for _, field := range fn.Type.Params.List {
				if len(field.Names) == 0 {
					names = append(names, "")
				}
				for _, name := range field.Names {
					names = append(names, name.Name)
				}
			}
			return names
		}
	}
	return nil
}

// constants returns the values of every constant the package declares of
// the named type, in file and declaration order, each once.
func (g *generator) constants(src *source, typeName string) ([]string, error) {
	var values []string
	for _, name := range src.order {
		c := src.consts[name]
		if !ofType(c, typeName) {
			continue
		}
		value, err := g.value(src, c, c.value, 0)
		if err != nil {
			return nil, fmt.Errorf("constant %s: %w", name, err)
		}
		if !slices.Contains(values, value) {
			values = append(values, value)
		}
	}
	return values, nil
}

// ofType reports whether a constant is declared of the named type, by its
// type or by a conversion to it.
func ofType(c constant, typeName string) bool {
	if c.typ != nil {
		ident, ok := c.typ.(*ast.Ident)
		return ok && ident.Name == typeName
	}
	call, ok := c.value.(*ast.CallExpr)
	if !ok {
		return false
	}
	ident, ok := call.Fun.(*ast.Ident)
	return ok && ident.Name == typeName
}

// value evaluates a string constant expression: a literal, a conversion, a
// concatenation, or another constant of this or another package of the
// repository.
func (g *generator) value(src *source, c constant, e ast.Expr, depth int) (string, error) {
	if depth > 16 {
		return "", errors.New("a constant refers to itself")
	}
	switch e := e.(type) {
	case *ast.BasicLit:
		if e.Kind == token.STRING {
			return strconv.Unquote(e.Value)
		}
	case *ast.ParenExpr:
		return g.value(src, c, e.X, depth+1)
	case *ast.CallExpr:
		if len(e.Args) == 1 {
			return g.value(src, c, e.Args[0], depth+1)
		}
	case *ast.BinaryExpr:
		if e.Op == token.ADD {
			left, err := g.value(src, c, e.X, depth+1)
			if err != nil {
				return "", err
			}
			right, err := g.value(src, c, e.Y, depth+1)
			return left + right, err
		}
	case *ast.Ident:
		if other, ok := src.consts[e.Name]; ok {
			return g.value(src, other, other.value, depth+1)
		}
	case *ast.SelectorExpr:
		pkg, ok := e.X.(*ast.Ident)
		if !ok {
			break
		}
		for _, spec := range c.imports {
			importPath, err := strconv.Unquote(spec.Path.Value)
			if err != nil || !strings.HasPrefix(importPath, modulePath) {
				continue
			}
			if spec.Name != nil && spec.Name.Name != pkg.Name {
				continue
			}
			other, err := g.source(importPath)
			if err != nil {
				return "", err
			}
			if spec.Name == nil && other.name != pkg.Name {
				continue
			}
			if referred, ok := other.consts[e.Sel.Name]; ok {
				return g.value(other, referred, referred.value, depth+1)
			}
		}
	}
	return "", fmt.Errorf("its value %T is not a string constant bindgen can read", e)
}
