package tests

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json/v2"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/bharm16/readmit/internal/correlate"
	"github.com/bharm16/readmit/internal/desktop"
	"github.com/bharm16/readmit/internal/diff"
	"github.com/bharm16/readmit/internal/grid"
	"github.com/bharm16/readmit/internal/guide"
	"github.com/bharm16/readmit/internal/hl7"
	"github.com/bharm16/readmit/internal/index"
	"github.com/bharm16/readmit/internal/redact"
	"github.com/bharm16/readmit/internal/replay"
	"github.com/bharm16/readmit/internal/reproducer"
	"github.com/bharm16/readmit/internal/testauthor"
	"github.com/bharm16/readmit/internal/testlicense"
	"github.com/bharm16/readmit/internal/testrunner"
	"github.com/bharm16/readmit/internal/transform"
)

// chosenFolder stands in for the host's native folder dialog.
type chosenFolder string

func (c chosenFolder) ChooseFolder(string) (string, error) { return string(c), nil }

func unlicensedDesktopApp(t *testing.T, folder string) *desktop.App {
	t.Helper()
	return desktop.New(chosenFolder(folder), desktop.ShellDocuments{Folder: t.TempDir()})
}

// The desktop shell and the command line are two entry points into one engine.
// Neither reimplements the generator, so every case bundle the desktop writes
// must be byte-identical to the one `readmit synth` writes from the same
// declared inputs, down to every manifest, record, payload and identity.
//
// What the shell writes is a workspace rather than a family. A directory holding
// the family completion record is retained evidence nothing may be written
// inside, and the guided sample saves a test and retains two runs in this one,
// so the record is not kept and a practice endpoint is written instead. Neither
// of those is evidence, and neither changes a generated byte.
func TestDesktopSampleWorkspaceHoldsTheCommandLineFamilyBytes(t *testing.T) {
	command := filepath.Join(t.TempDir(), "family")
	createSynth(t, synthArgs(command))

	parent := t.TempDir()
	result := desktopApp(t, parent).CreateSampleWorkspace()
	if result.State != desktop.Completed || result.Workspace == nil {
		t.Fatalf("sample workspace: %+v", result)
	}

	shell := treeOf(t, result.Workspace.Root)
	reference := treeOf(t, command)
	for name, want := range reference {
		if name == "family.json" {
			if _, present := shell[name]; present {
				t.Fatal("the sample workspace carries a family completion record and cannot be written in")
			}
			continue
		}
		got, present := shell[name]
		if !present {
			t.Fatalf("the desktop sample workspace is missing %s", name)
		}
		if !bytes.Equal(got, want) {
			t.Fatalf("%s differs between the desktop shell and the command line", name)
		}
	}
	// Nothing else is generated: the two entries the shell adds are the practice
	// endpoint a test names and the index the message grid reads, neither of
	// which is evidence and neither of which a generated family holds.
	for name := range shell {
		if _, expected := reference[name]; !expected && name != guide.TargetName && name != guide.IndexName {
			t.Fatalf("the desktop sample workspace wrote %s, which the command line did not", name)
		}
	}
	if _, err := replay.ReadDeclaredTarget(filepath.Join(result.Workspace.Root, guide.TargetName)); err != nil {
		t.Fatalf("the practice endpoint is not a target configuration this release reads: %v", err)
	}
}

// Opening a case in the shell must be the same verification `timeline`
// performs, reported as typed values instead of prose.
func TestDesktopCaseVerificationAgreesWithTheCommandLine(t *testing.T) {
	parent := t.TempDir()
	app := desktopApp(t, parent)
	created := app.CreateSampleWorkspace()
	if created.State != desktop.Completed || created.Workspace == nil {
		t.Fatalf("sample workspace: %+v", created)
	}
	root := created.Workspace.Root

	for _, name := range []string{"regression", "cancellation", "invalid"} {
		opened := app.OpenCase(root, name)
		if opened.State != desktop.Completed || opened.Case == nil {
			t.Fatalf("desktop open %s: %+v", name, opened)
		}
		stdout, stderr, err := run(t, "timeline", filepath.Join(root, name))
		if err != nil || stderr != "" {
			t.Fatalf("timeline %s: %v %s", name, err, stderr)
		}
		for _, want := range []string{
			"Bundle: " + opened.Case.Identity,
			"Schema: " + opened.Case.Schema,
			"Provenance: " + opened.Case.Provenance,
			fmt.Sprintf("Sources: %d", opened.Case.Sources),
			fmt.Sprintf("Occurrences: %d", opened.Case.Occurrences),
			fmt.Sprintf("Messages: %d", opened.Case.Messages),
			fmt.Sprintf("ACKs: %d", opened.Case.Acknowledgements),
			fmt.Sprintf("Unparsed: %d", opened.Case.Unparsed),
		} {
			if !strings.Contains(stdout, want) {
				t.Fatalf("timeline %s disagrees with the desktop facade about %q:\n%s", name, want, stdout)
			}
		}
	}

	// Damaged evidence is refused identically by both entry points.
	if err := os.WriteFile(filepath.Join(root, "invalid", "identity.sha256"), []byte("0000\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if opened := app.OpenCase(root, "invalid"); opened.State != desktop.Failed || opened.Case != nil {
		t.Fatalf("the desktop facade accepted damaged evidence: %+v", opened)
	}
	if _, _, err := run(t, "timeline", filepath.Join(root, "invalid")); err == nil {
		t.Fatal("the command line accepted damaged evidence")
	}
}

// The desktop shell is a separate module with a webview and cgo. The released
// command line must stay a static build that never reaches it.
func TestCommandLineReleaseNeverReachesTheDesktopShell(t *testing.T) {
	packages := goCommand(t, nil, "list", "-deps", "../cmd/readmit")
	for _, forbidden := range []string{"wails", "github.com/bharm16/readmit/internal/desktop", "github.com/bharm16/readmit/internal/testlicense"} {
		if strings.Contains(packages, forbidden) {
			t.Fatalf("the released command line depends on %s", forbidden)
		}
	}
	binary := filepath.Join(t.TempDir(), "readmit-static")
	goCommand(t, []string{"CGO_ENABLED=0"}, "build", "-o", binary, "../cmd/readmit")
	if _, err := os.Stat(binary); err != nil {
		t.Fatalf("the command line no longer builds without cgo: %v", err)
	}
}

// The packaging declaration is the one place the finite desktop target matrix
// and the platform prerequisites of D5 are named. Both the packages and the
// pages that promise them read it from here, so neither can drift away from
// what an operator is actually handed.
func TestDesktopPackagesDeclareThePrerequisitesTheDocumentationPromises(t *testing.T) {
	type packagingDeclaration struct {
		Schema              string   `json:"schema"`
		Product             string   `json:"product"`
		DisplayName         string   `json:"display_name"`
		Summary             string   `json:"summary"`
		Manufacturer        string   `json:"manufacturer"`
		Maintainer          string   `json:"maintainer"`
		BundleIdentifier    string   `json:"bundle_identifier"`
		UpgradeCode         string   `json:"upgrade_code"`
		MinimumMacOSVersion string   `json:"minimum_macos_version"`
		DebianDependencies  []string `json:"debian_dependencies"`
		WebView2            struct {
			RegistryKey   string `json:"registry_key"`
			RegistryValue string `json:"registry_value"`
			Message       string `json:"message"`
		} `json:"webview2"`
		Targets []struct {
			OS                  string   `json:"os"`
			Arch                string   `json:"arch"`
			PackageArchitecture string   `json:"package_architecture"`
			Formats             []string `json:"formats"`
		} `json:"targets"`
	}
	declaration := readStrictDocument[packagingDeclaration](t, "../desktop/packaging/packages.json")
	if declaration.Schema != "readmit-desktop-packaging/v1" {
		t.Fatalf("the packaging declaration declares %q", declaration.Schema)
	}
	page, err := os.ReadFile("../docs/desktop.md")
	if err != nil {
		t.Fatal(err)
	}
	documented := string(page)
	for _, dependency := range declaration.DebianDependencies {
		if !strings.Contains(documented, dependency) {
			t.Errorf("the .deb depends on %s, which the desktop page does not name", dependency)
		}
	}
	if len(declaration.DebianDependencies) == 0 {
		t.Error("the .deb declares no platform library")
	}
	installer, err := os.ReadFile("../desktop/packaging/readmit-desktop.wxs")
	if err != nil {
		t.Fatal(err)
	}
	// Every value the declaration names reaches the installer as a variable, so
	// the declaration stays the single place it is stated.
	for _, variable := range []string{"$(var.WebView2Key)", "$(var.WebView2Value)", "$(var.WebView2Message)", "$(var.UpgradeCode)", "$(var.Version)"} {
		if !strings.Contains(string(installer), variable) {
			t.Errorf("the installer does not take %s from the packaging declaration", variable)
		}
	}
	if !strings.Contains(string(installer), "Installed OR READMITWEBVIEW2") {
		t.Error("the installer no longer refuses a machine without the WebView2 runtime")
	}
	if !strings.Contains(documented, "WebView2") || !strings.Contains(documented, declaration.MinimumMacOSVersion) {
		t.Error("the desktop page does not state the WebView2 prerequisite and the macOS floor")
	}
	targets := map[string][]string{}
	for _, target := range declaration.Targets {
		if target.PackageArchitecture == "" || len(target.Formats) == 0 {
			t.Fatalf("%s/%s declares no package", target.OS, target.Arch)
		}
		targets[target.OS+"/"+target.Arch] = target.Formats
		for _, format := range target.Formats {
			if !strings.Contains(documented, "`."+format+"`") {
				t.Errorf("the desktop page does not describe the .%s package", format)
			}
		}
	}
	// Restated here on purpose: `packages.json` is where the matrix is declared,
	// and this is the check that adding a target is a deliberate act rather than
	// a line that slipped into a data file.
	expected := map[string][]string{
		"linux/amd64":   {"deb"},
		"linux/arm64":   {"deb"},
		"darwin/amd64":  {"dmg", "pkg"},
		"darwin/arm64":  {"dmg", "pkg"},
		"windows/amd64": {"msi"},
	}
	if !reflect.DeepEqual(targets, expected) {
		t.Fatalf("the declared desktop targets are %v, not the finite matrix %v", targets, expected)
	}
}

// The desktop module keeps its dependency graph out of the released module, so
// adding a webview dependency cannot change what the command line resolves.
func TestDesktopDependenciesStayOutOfTheReleasedModule(t *testing.T) {
	released, err := os.ReadFile("../go.mod")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(released), "wails") {
		t.Fatal("the released module requires the desktop webview dependency")
	}
	shell, err := os.ReadFile("../desktop/go.mod")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"module github.com/bharm16/readmit/desktop", "github.com/wailsapp/wails/v2", "replace github.com/bharm16/readmit => ../"} {
		if !strings.Contains(string(shell), want) {
			t.Fatalf("the desktop module no longer declares %q", want)
		}
	}
}

// The recent workspace list is local shell state. It records folders the person
// opened and nothing read out of them.
func TestRecentWorkspacesRecordFoldersAndNoEvidence(t *testing.T) {
	store := filepath.Join(t.TempDir(), "recent.json")
	parent := t.TempDir()
	app := desktop.New(chosenFolder(parent), desktop.ShellDocuments{Folder: filepath.Dir(store)})
	created := app.CreateSampleWorkspace()
	if created.State != desktop.Completed {
		t.Fatalf("sample workspace: %+v", created)
	}
	recent := app.RecentWorkspaces()
	if recent.State != desktop.Completed || !reflect.DeepEqual(recent.Roots, []string{created.Workspace.Root}) {
		t.Fatalf("the sample workspace was not recorded for reopening: %+v", recent)
	}
	stored, err := os.ReadFile(store)
	if err != nil {
		t.Fatal(err)
	}
	for _, leaked := range []string{"MSH", "SCH", "SYNTH-", "regression", "identity"} {
		if strings.Contains(string(stored), leaked) {
			t.Fatalf("the recent workspace list recorded %q: %s", leaked, stored)
		}
	}
	// Reopening from the recorded folder returns the same workspace.
	reopened := desktop.New(chosenFolder(""), desktop.ShellDocuments{Folder: filepath.Dir(store)}).OpenWorkspace(recent.Roots[0])
	if reopened.State != desktop.Completed || reopened.Workspace == nil || reopened.Workspace.Root != created.Workspace.Root {
		t.Fatalf("a recorded workspace could not be reopened: %+v", reopened)
	}
	if len(reopened.Workspace.Artifacts) != len(created.Workspace.Artifacts) {
		t.Fatalf("reopening changed the listing: %+v", reopened.Workspace.Artifacts)
	}
}

func goCommand(t *testing.T, environment []string, args ...string) string {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	command := exec.CommandContext(ctx, "go", args...)
	command.Env = append(os.Environ(), environment...)
	var stdout, stderr bytes.Buffer
	command.Stdout, command.Stderr = &stdout, &stderr
	if err := command.Run(); err != nil {
		t.Fatalf("go %s: %v %s", strings.Join(args, " "), err, stderr.String())
	}
	return stdout.String()
}

// The command line and the desktop shell are two entry points into one engine,
// and the index is the one search path over a case. So the occurrences a
// filtered message grid renders must be exactly the ones `readmit index search`
// reports for the same question over the same index, and the grid must say how
// many of the case it left out.
func TestDesktopGridRendersExactlyWhatTheCommandLineIndexSearchFinds(t *testing.T) {
	const occurrences = 120
	const wanted = "MRN-0042^^^READMIT^MR"

	workspace := t.TempDir()
	evidence := filepath.Join(workspace, "incident")
	if _, stderr, err := run(t, "capture", indexCorpus(t, occurrences), "--output", evidence); err != nil || stderr != "" {
		t.Fatalf("capture: %v %s", err, stderr)
	}
	written := filepath.Join(workspace, "incident.index.json")
	if _, stderr, err := run(t, "index", "build", evidence, "--output", written,
		"--field", "PID-3", "--retain", "values", "--retain-until", "indefinite"); err != nil || stderr != "" {
		t.Fatalf("index build: %v %s", err, stderr)
	}
	stdout, stderr, err := run(t, "index", "search", evidence, written, "--field", "PID-3", "--equals", wanted)
	if err != nil || stderr != "" {
		t.Fatalf("index search: %v %s", err, stderr)
	}
	reported := reportedOccurrences(stdout)
	if len(reported) != 1 {
		t.Fatalf("the command line found %v, want exactly one occurrence:\n%s", reported, stdout)
	}

	app := desktopApp(t, workspace)
	saved := app.SaveFilter(grid.Filter{Name: "one patient", Fields: []grid.FieldPredicate{
		{Selector: "PID[1]-3[1]", Match: index.Equals, Term: wanted},
	}})
	if saved.State != desktop.Completed || saved.Selected != "one patient" {
		t.Fatalf("the filter was not saved: %+v", saved)
	}
	result := app.OpenGrid(workspace, "incident", "incident.index.json", 0, 50)
	if result.State != desktop.Completed || result.Grid == nil {
		t.Fatalf("the grid did not open: %+v", result)
	}
	rendered := make([]string, 0, len(result.Grid.Rows))
	for _, row := range result.Grid.Rows {
		rendered = append(rendered, row.ID)
	}
	if !reflect.DeepEqual(rendered, reported) {
		t.Fatalf("the grid rendered %v and the command line found %v", rendered, reported)
	}

	// The case holds one occurrence this release cannot decode, and the grid
	// separates that from the records the filter simply removed.
	if result.Grid.Total != occurrences+1 || result.Grid.Matched != 1 {
		t.Fatalf("the grid did not describe the whole case: %+v", result.Grid)
	}
	if result.Grid.Excluded != occurrences || result.Grid.Undecodable != 1 {
		t.Fatalf("the grid did not name what it excluded: %+v", result.Grid)
	}
	if encoded, err := json.Marshal(result); err != nil {
		t.Fatal(err)
	} else if strings.Contains(string(encoded), "MRN-") || strings.Contains(string(encoded), "corpus.mllp") {
		t.Fatalf("the grid disclosed evidence: %s", encoded)
	}
}

// reportedOccurrences reads the occurrence IDs out of an `index search` report.
// Each match is one indented line beginning with the occurrence it names.
func reportedOccurrences(stdout string) []string {
	found := []string{}
	for _, line := range strings.Split(stdout, "\n") {
		if !strings.HasPrefix(line, "  s") {
			continue
		}
		found = append(found, strings.Fields(line)[0])
	}
	return found
}

// The whole reproducer delivery, across both entry points. The window extracts
// a reproducer out of a captured incident — the reschedule a person selected,
// the booking its declared identity requires, and one edited field — and the
// command line then verifies that derived case and registers it as a revision
// of the evidence it came from. Neither side reimplements the other, and the
// original is byte-identical afterwards.
func TestDesktopReproducerIsVerifiedAndRegisteredByTheCommandLine(t *testing.T) {
	workspace := t.TempDir()
	evidence := filepath.Join(workspace, "incident")
	if _, stderr, err := run(t, "capture", "../testdata/fixtures/synth-v1-regression.mllp", "--output", evidence); err != nil || stderr != "" {
		t.Fatalf("capture: %v %s", err, stderr)
	}
	before := caseFiles(t, evidence)

	app := desktopApp(t, workspace)
	opened := app.OpenCase(workspace, "incident")
	if opened.State != desktop.Completed {
		t.Fatalf("the case did not verify: %+v", opened)
	}
	build := desktop.ReproducerRequest{Workspace: workspace, Case: "incident", Identity: opened.Case.Identity}
	for _, step := range []reproducer.Step{
		{Operator: reproducer.SelectOccurrence, Occurrence: "s0001-e000002"},
		{Operator: reproducer.IncludePriorIdentity, Identity: []string{"SCH-2.1", "SCH-2.2"}},
		{Operator: reproducer.SetField, Occurrence: "s0001-e000002", Selector: "PID-3.1", Value: "MRN-REPRODUCER"},
	} {
		build.Step = step
		result := app.EditReproducer(build)
		if result.State != desktop.Completed {
			t.Fatalf("the window refused a step it supports: %+v", result)
		}
		build.Plan = result.Reproducer.Plan
	}
	build.Step, build.Output = reproducer.Step{}, "incident-reproducer"
	built := app.BuildReproducer(build)
	if built.State != desktop.Completed || len(built.Reproducer.Resolution.Occurrences) != 2 {
		t.Fatalf("the reproducer was not written: %+v", built)
	}
	if !reflect.DeepEqual(before, caseFiles(t, evidence)) {
		t.Fatal("building a reproducer changed the evidence it was derived from")
	}

	// The command line verifies what the window wrote, through the same reader
	// every other case goes through.
	derived := filepath.Join(workspace, "incident-reproducer", reproducer.CaseName)
	stdout, stderr, err := run(t, "timeline", derived)
	if err != nil || stderr != "" {
		t.Fatalf("timeline: %v %s", err, stderr)
	}
	if !strings.Contains(stdout, built.Reproducer.Identity) || !strings.Contains(stdout, "Occurrences: 2") {
		t.Fatalf("timeline did not report the reproducer the window wrote:\n%s", stdout)
	}

	// And a project records where it came from, reading the operation out of the
	// derivation the derived case declares rather than from anything typed here.
	project := filepath.Join(workspace, "investigation")
	if _, stderr, err := run(t, "project", "init", "--output", project, "--title", "Scheduling", "--interface-version", "v1"); err != nil || stderr != "" {
		t.Fatalf("project init: %v %s", err, stderr)
	}
	copyTree(t, evidence, filepath.Join(project, "incident"))
	copyTree(t, derived, filepath.Join(project, "incident-reproducer"))
	added, stderr, err := run(t, "project", "add", project, "incident", "--title", "Original incident")
	if err != nil || stderr != "" {
		t.Fatalf("project add: %v %s", err, stderr)
	}
	stdout, stderr, err = run(t, "project", "revise", project, "incident-reproducer", "--parent", "incident")
	if err != nil || stderr != "" {
		t.Fatalf("project revise: %v %s", err, stderr)
	}
	for _, want := range []string{
		"Schema: readmit-case/v3",
		"Provenance: derived",
		"Operation: " + reproducer.Derivation,
		"Parent identity: " + field(t, added, "Identity: "),
	} {
		if !strings.Contains(stdout, want) {
			t.Errorf("project revise omitted %q:\n%s", want, stdout)
		}
	}
}

// caseFiles reads every file of a case directory, so a test can assert that
// deriving from it changed nothing.
func caseFiles(t *testing.T, root string) map[string]string {
	t.Helper()
	files := map[string]string{}
	err := filepath.WalkDir(root, func(name string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		data, err := os.ReadFile(name)
		relative, _ := filepath.Rel(root, name)
		files[relative] = string(data)
		return err
	})
	if err != nil {
		t.Fatal(err)
	}
	return files
}

// copyTree copies one artifact directory, which is what an operator does before
// registering derived evidence as a revision of a project.
func copyTree(t *testing.T, from, to string) {
	t.Helper()
	if err := os.CopyFS(to, os.DirFS(from)); err != nil {
		t.Fatal(err)
	}
}

// The whole authoring delivery, across both entry points. The window answers a
// guided flow over a captured incident — what the test is called, which
// occurrences it sends, the target it sends them to, the boundary that decides
// it, where that observation is read from, how the fixture is reset, and what
// the run should have produced — and writes a versioned test. The command line
// then reads and prepares exactly that file. Nobody edited a document, and the
// evidence it was authored from is byte-identical afterwards.
func TestDesktopAuthoredTestIsPreparedByTheCommandLine(t *testing.T) {
	workspace := t.TempDir()
	evidence := filepath.Join(workspace, "incident")
	if _, stderr, err := run(t, "capture", "../testdata/fixtures/synth-v1-regression.mllp", "--output", evidence); err != nil || stderr != "" {
		t.Fatalf("capture: %v %s", err, stderr)
	}
	before := caseFiles(t, evidence)
	target, err := os.ReadFile("../testdata/fixtures/test-target.json")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(workspace, "test-target.json"), target, 0600); err != nil {
		t.Fatal(err)
	}

	app := desktopApp(t, workspace)
	opened := app.OpenCase(workspace, "incident")
	if opened.State != desktop.Completed {
		t.Fatalf("the case did not verify: %+v", opened)
	}
	request := desktop.TestRequest{Workspace: workspace, Case: "incident", Identity: opened.Case.Identity}
	count, accepted := 1, "AA"
	for _, answer := range []testauthor.Answer{
		{Stage: testauthor.StageName, Name: "Rescheduling updates the original appointment"},
		{Stage: testauthor.StageMessages, Messages: []string{"s0001-e000001", "s0001-e000002"}},
		{Stage: testauthor.StageTarget, Target: "test-target.json"},
		{Stage: testauthor.StageBoundary, Boundary: testrunner.LedgerBoundary},
		{Stage: testauthor.StageObservation, Observation: "test-observation.json"},
		{Stage: testauthor.StageReset, Reset: "Stop the prior listener, start a fresh one with an empty ledger, and wait for Listening."},
		{Stage: testauthor.StageExpectations, Expectations: []testauthor.Expectation{
			{ID: "one-appointment", Operator: testauthor.LedgerCount, Count: &count},
			{ID: "booking-ack", Operator: testauthor.ACKFieldEquals, Message: "s0001-e000001", Selector: "MSA-1",
				Field: &testrunner.FieldValue{State: hl7.Present, Text: &accepted}},
		}},
	} {
		request.Answer = answer
		result := app.AuthorTest(request)
		if result.State != desktop.Completed {
			t.Fatalf("the window refused the %s stage: %+v", answer.Stage, result)
		}
		request.Draft = result.Test.Draft
	}
	request.Answer, request.Output = testauthor.Answer{}, "reschedule-test.json"
	saved := app.SaveTest(request)
	if saved.State != desktop.Completed || saved.Test.Output != "reschedule-test.json" {
		t.Fatalf("the test spec was not written: %+v", saved)
	}
	if !reflect.DeepEqual(before, caseFiles(t, evidence)) {
		t.Fatal("authoring a test changed the evidence it was authored from")
	}

	// The command line validates the spec the window wrote, resolving the case
	// and the target it names relative to the document, and connects to
	// nothing: a saved test is a test, not a run.
	spec := filepath.Join(workspace, "reschedule-test.json")
	stdout, stderr, err := run(t, "test", spec)
	if err != nil || stderr != "" {
		t.Fatalf("test: %v %s", err, stderr)
	}
	for _, want := range []string{"no verdict or result artifact produced", "Observation boundary: appointment-ledger", "Messages: 2"} {
		if !strings.Contains(stdout, want) {
			t.Errorf("the command line did not report %q for the authored spec:\n%s", want, stdout)
		}
	}
	// And the identity the window reported is the identity of the bytes the
	// command line just read, because both are the file that was written.
	written, err := os.ReadFile(spec)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(written)
	if saved.Test.Identity != hex.EncodeToString(sum[:]) {
		t.Fatalf("the window reported an identity the saved spec does not have: %s", saved.Test.Identity)
	}
}

// comparisonLine is one row of a comparison, reduced to what both entry points
// have to agree on: what the row is, the occurrence on each side, the outcome,
// and the positions that differ.
type comparisonLine struct {
	kind, left, right, status, reason string
	fields                            []string
}

func reportedLines(report diff.Report) []comparisonLine {
	lines := []comparisonLine{}
	for _, pair := range report.Pairs {
		selectors := []string{}
		for _, field := range pair.Fields {
			selectors = append(selectors, field.Selector+" "+field.Status)
		}
		lines = append(lines, comparisonLine{"paired", pair.Left.Occurrence, pair.Right.Occurrence, pair.Status, "", selectors})
	}
	for _, missing := range report.Missing {
		lines = append(lines, comparisonLine{"missing", missing.Occurrence, "", "", "", []string{}})
	}
	for _, inserted := range report.Inserted {
		lines = append(lines, comparisonLine{"inserted", "", inserted.Occurrence, "", "", []string{}})
	}
	for _, ambiguity := range report.Ambiguous {
		for _, candidate := range ambiguity.Left {
			lines = append(lines, comparisonLine{"ambiguous", candidate.Occurrence, "", "", ambiguity.Reason, []string{}})
		}
		for _, candidate := range ambiguity.Right {
			lines = append(lines, comparisonLine{"ambiguous", "", candidate.Occurrence, "", ambiguity.Reason, []string{}})
		}
	}
	for _, unaligned := range report.Unaligned {
		line := comparisonLine{"unaligned", "", "", "", unaligned.Reason, []string{}}
		if unaligned.Side == "left" {
			line.left = unaligned.Reference.Occurrence
		} else {
			line.right = unaligned.Reference.Occurrence
		}
		lines = append(lines, line)
	}
	return lines
}

func renderedLines(comparison *desktop.Comparison) []comparisonLine {
	lines := []comparisonLine{}
	for _, row := range comparison.Rows {
		line := comparisonLine{kind: string(row.Kind), status: row.Status, reason: row.Reason, fields: []string{}}
		if row.Left != nil {
			line.left = row.Left.Occurrence
		}
		if row.Right != nil {
			line.right = row.Right.Occurrence
		}
		for _, field := range row.Fields {
			line.fields = append(line.fields, field.Selector+" "+field.Status)
		}
		lines = append(lines, line)
	}
	return lines
}

// The desktop shell and the command line are two entry points into one
// comparison. The window names two entries of a workspace and gets rows back;
// `readmit diff` prints the same report as a document. Neither aligns evidence
// of its own, so what the panes draw is exactly what the command line reports —
// including the record only one side holds. The window shows no value while the
// command line can be asked for them explicitly.
func TestDesktopComparisonRendersExactlyWhatTheCommandLineDiffReports(t *testing.T) {
	workspace := t.TempDir()
	for name, fixture := range map[string]string{"before": "diff-before.mllp", "after": "diff-after.mllp"} {
		if _, stderr, err := run(t, "capture", "../testdata/fixtures/"+fixture, "--output", filepath.Join(workspace, name)); err != nil || stderr != "" {
			t.Fatalf("capture %s: %v %s", fixture, err, stderr)
		}
	}
	left, right := filepath.Join(workspace, "before"), filepath.Join(workspace, "after")
	report, _ := diffJSON(t, left, right, "--key", "MSH-10")
	if report.Summary.Paired == 0 || report.Summary.Inserted == 0 || report.Summary.FieldChanges == 0 {
		t.Fatalf("the fixtures no longer exercise a pairing, an insertion and a field change: %+v", report.Summary)
	}

	app := desktopApp(t, workspace)
	opened := app.OpenCase(workspace, "before")
	if opened.State != desktop.Completed || opened.Case == nil {
		t.Fatalf("the left collection was not verified: %+v", opened)
	}
	result := app.Compare(desktop.CompareRequest{
		Workspace: workspace, Left: "before", Identity: opened.Case.Identity, Right: "after",
		Keys: []string{"MSH-10"}, Limit: desktop.MaxComparisonRows,
	})
	if result.State != desktop.Completed || result.Comparison == nil {
		t.Fatalf("the window did not compare the two collections: %+v", result)
	}
	if result.Comparison.Alignment != report.Alignment || !reflect.DeepEqual(result.Comparison.Summary, report.Summary) {
		t.Fatalf("the window counted %+v %q and the command line %+v %q",
			result.Comparison.Summary, result.Comparison.Alignment, report.Summary, report.Alignment)
	}
	if rendered, reported := renderedLines(result.Comparison), reportedLines(report); !reflect.DeepEqual(rendered, reported) {
		t.Fatalf("the window drew %+v and the command line reported %+v", rendered, reported)
	}

	// Values are the one thing the two entry points deliberately differ on: the
	// command line displays them when it is asked to, and the window never does.
	shown, _ := diffJSON(t, left, right, "--key", "MSH-10", "--show-values")
	encoded, err := json.Marshal(result)
	if err != nil {
		t.Fatal(err)
	}
	displayed := 0
	for _, pair := range shown.Pairs {
		for _, field := range pair.Fields {
			if field.Left.Display == nil {
				continue
			}
			displayed++
			value, err := strconv.Unquote(*field.Left.Display)
			if err != nil {
				t.Fatal(err)
			}
			if value != "" && bytes.Contains(encoded, []byte(value)) {
				t.Fatalf("the window disclosed a compared value: %s", encoded)
			}
		}
	}
	if displayed == 0 {
		t.Fatal("the command line displayed no value, so nothing was checked")
	}
}

// rescheduleSpec is the committed reschedule test, read once per use so a test
// that varies an expectation never edits the fixture.
func rescheduleSpec(t *testing.T) []byte {
	t.Helper()
	spec, err := os.ReadFile("../testdata/fixtures/test-reschedule.json")
	if err != nil {
		t.Fatal(err)
	}
	return spec
}

// runRevision executes one test spec against a reproducer revision's derived
// case and returns the retained result directory.
//
// Only the case the spec names is rebound onto this revision: what a verdict
// depends on — the selected occurrences, the boundary and every expectation —
// is whatever the caller passed, which is what lets one test vary exactly one
// of them. mode is the fixture receiver's behaviour; the empty string starts no
// receiver at all and points the target at a port nothing is listening on,
// which is how a run that reached no expectation is produced.
func runRevision(t *testing.T, workspace, revision, output, mode string, spec []byte, want int) string {
	t.Helper()
	dir := t.TempDir()
	specPath := filepath.Join(dir, "test-reschedule.json")
	if err := os.WriteFile(specPath, spec, 0600); err != nil {
		t.Fatal(err)
	}
	copyTree(t, filepath.Join(workspace, revision, reproducer.CaseName), filepath.Join(dir, "test-case"))
	wait := func() {}
	if mode == "" {
		testTarget(t, dir, "127.0.0.1:1")
		if err := os.WriteFile(filepath.Join(dir, "test-observation.json"), []byte("[]"), 0600); err != nil {
			t.Fatal(err)
		}
	} else {
		wait = testListener(t, dir, mode)
	}
	stdout, stderr, err := run(t, "test", specPath, "--send", "--output", filepath.Join(workspace, output))
	if exitCode(t, err) != want || stderr != "" {
		t.Fatalf("this revision's test did not reach the expected outcome: %v %s %s", err, stdout, stderr)
	}
	wait()
	return output
}

// revisionWorkspace captures one incident and writes two reproducer revisions
// of it through the window: both keep the booking and the reschedule that
// depends on it, and the second also replaces a patient name on the way out — a
// testing transformation of customer evidence, and no de-identification claim
// about it.
func revisionWorkspace(t *testing.T) (*desktop.App, string, string, string, string) {
	t.Helper()
	workspace := t.TempDir()
	evidence := filepath.Join(workspace, "incident")
	if _, stderr, err := run(t, "capture", "../testdata/fixtures/listen-s12.hl7", "../testdata/fixtures/listen-s13.hl7", "--output", evidence); err != nil || stderr != "" {
		t.Fatalf("capture: %v %s", err, stderr)
	}
	before := caseFiles(t, evidence)
	app := desktopApp(t, workspace)
	opened := app.OpenCase(workspace, "incident")
	if opened.State != desktop.Completed {
		t.Fatalf("the case did not verify: %+v", opened)
	}
	build := func(output string, steps ...reproducer.Step) string {
		t.Helper()
		request := desktop.ReproducerRequest{Workspace: workspace, Case: "incident", Identity: opened.Case.Identity}
		for _, step := range steps {
			request.Step = step
			result := app.EditReproducer(request)
			if result.State != desktop.Completed {
				t.Fatalf("the window refused a step it supports: %+v", result)
			}
			request.Plan = result.Reproducer.Plan
		}
		request.Step, request.Output = reproducer.Step{}, output
		if result := app.BuildReproducer(request); result.State != desktop.Completed {
			t.Fatalf("the reproducer was not written: %+v", result)
		}
		return output
	}
	selection := []reproducer.Step{
		{Operator: reproducer.SelectOccurrence, Occurrence: "s0001-e000001"},
		{Operator: reproducer.SelectOccurrence, Occurrence: "s0002-e000001"},
	}
	original := build("incident-reproducer", selection...)
	transformed := build("incident-reproducer-2", append(slices.Clone(selection),
		reproducer.Step{Operator: reproducer.SetField, Occurrence: "s0002-e000001", Selector: "PID-5.1", Value: "REPRODUCER"})...)
	if !reflect.DeepEqual(before, caseFiles(t, evidence)) {
		t.Fatal("building reproducers changed the evidence they were derived from")
	}
	return app, workspace, original, transformed, opened.Case.Identity
}

// The whole of R09.4 across both entry points: two revisions of one incident,
// the lineage that relates them, the setup dependency the second one stopped
// retaining, and the proof that the selected expectation failed the same way
// before and after the transformation.
//
// The runs are real. Each revision's derived case is sent at a fixture receiver
// by the command line, each result is retained where the workspace can find it,
// and the window compares what those results decided rather than deciding
// anything itself.
func TestDesktopRevisionComparisonProvesTheSameFailureBeforeAndAfter(t *testing.T) {
	app, workspace, original, transformed, identity := revisionWorkspace(t)
	spec := rescheduleSpec(t)
	originalRun := runRevision(t, workspace, original, "incident-reproducer-run", "defective", spec, 1)
	transformedRun := runRevision(t, workspace, transformed, "incident-reproducer-2-run", "defective", spec, 1)

	compared := app.CompareReproducers(desktop.ReproducerComparisonRequest{
		Workspace: workspace, Left: original, Right: transformed,
		LeftResult: originalRun, RightResult: transformedRun,
	})
	if compared.State != desktop.Completed || compared.Comparison == nil {
		t.Fatalf("two revisions of one incident were not compared: %+v", compared)
	}
	comparison := compared.Comparison
	if comparison.Lineage != reproducer.SiblingOf || comparison.Left.Parent.Identity != identity {
		t.Fatalf("the lineage of two revisions of one case was reported as %q", comparison.Lineage)
	}
	// Transformed customer evidence is reported as the transformation it
	// declares, never as generated material.
	if comparison.Right.Provenance != "derived" || comparison.Right.Derivation != reproducer.Derivation {
		t.Fatalf("a revision was not reported as the derived evidence it declares: %+v", comparison.Right)
	}
	// Both revisions retain the same two occurrences, and the transformation is
	// the one authored step and the one edited position that follow from it.
	if len(comparison.Retention) != 0 {
		t.Fatalf("two revisions retaining the same occurrences reported a retention change: %+v", comparison.Retention)
	}
	if len(comparison.Steps) != 1 || comparison.Steps[0].Change != reproducer.Added ||
		comparison.Steps[0].Step.Operator != reproducer.SetField {
		t.Fatalf("the authored transformation was not reported: %+v", comparison.Steps)
	}
	if len(comparison.Edits) != 1 || comparison.Edits[0].Change != reproducer.Added ||
		comparison.Edits[0].Selector != "PID[1]-5[1].1" || comparison.Edits[0].RightOperator != reproducer.SetField {
		t.Fatalf("the edited position was not reported: %+v", comparison.Edits)
	}
	// The proof: both runs evaluated the same expectations, each against the
	// revision it is offered as proof of, and the selected expectation failed
	// the same way on both sides.
	if comparison.Proof.State != reproducer.ProofCompared {
		t.Fatalf("two real runs of the same test were not compared: %+v", comparison.Proof)
	}
	if comparison.Proof.Left.Case != comparison.Left.Derived.Identity ||
		comparison.Proof.Right.Case != comparison.Right.Derived.Identity {
		t.Fatal("a retained run was not bound to the revision it is proof of")
	}
	outcomes := map[string]string{}
	for _, assertion := range comparison.Proof.Assertions {
		outcomes[assertion.Assertion] = assertion.Outcome
	}
	if len(outcomes) != 4 || outcomes["one-appointment"] != reproducer.SameFailure {
		t.Fatalf("the selected failure did not survive the transformation: %+v", comparison.Proof.Assertions)
	}
	if outcomes["booking-ack"] != reproducer.SamePass || outcomes["rescheduling-ack"] != reproducer.SamePass {
		t.Fatalf("the acknowledgement expectations changed across the transformation: %+v", outcomes)
	}

	// A run of one revision is not proof of the other, and swapping them is
	// refused rather than reported as a comparison.
	swapped := app.CompareReproducers(desktop.ReproducerComparisonRequest{
		Workspace: workspace, Left: original, Right: transformed,
		LeftResult: transformedRun, RightResult: originalRun,
	})
	if swapped.State != desktop.Failed || swapped.Comparison != nil {
		t.Fatalf("a run of other evidence was accepted as proof of a revision: %+v", swapped)
	}
	// A revision with no retained run claims nothing, rather than reading as a
	// revision that passed.
	partial := app.CompareReproducers(desktop.ReproducerComparisonRequest{
		Workspace: workspace, Left: original, Right: transformed, LeftResult: originalRun,
	})
	if partial.State != desktop.Completed || partial.Comparison.Proof.State != reproducer.ProofNotAttempted ||
		len(partial.Comparison.Proof.Assertions) != 0 || partial.Comparison.Proof.Right != nil {
		t.Fatalf("a revision nobody has run was reported as proved: %+v", partial)
	}
	// The run that was named is still read and bound to the revision it belongs
	// to, so naming one is never silently ignored.
	if partial.Comparison.Proof.Left == nil || partial.Comparison.Proof.Left.Case != comparison.Left.Derived.Identity {
		t.Fatalf("the one retained run that was named was not read: %+v", partial.Comparison.Proof)
	}
	// No value of the evidence crosses this boundary, including the name the
	// second revision replaced and the identifiers the expectations compare.
	reported, err := json.Marshal(compared, json.Deterministic(true))
	if err != nil {
		t.Fatal(err)
	}
	for _, private := range []string{"EXAMPLE", "SYNTH-001", "APPT-001", "FILL-001", "LISTEN-BOOK", "20260103110000", "Rescheduling updates"} {
		if bytes.Contains(reported, []byte(private)) {
			t.Fatalf("the comparison disclosed %q", private)
		}
	}
}

// The desktop shell and the command line are two entry points into one
// transformation engine. The window names a case and two authored documents of
// a workspace and gets a preview back; `readmit transform --format json` prints
// the same preview as a document. Neither previews a transformation of its own,
// so what the panel draws is exactly what the command line reports over the
// same evidence — and neither of them records a value byte.
func TestDesktopTransformationPreviewMatchesTheCommandLine(t *testing.T) {
	workspace := t.TempDir()
	casePath := filepath.Join(workspace, "incident")
	if _, stderr, err := run(t, "capture",
		"../testdata/fixtures/listen-s12.hl7", "../testdata/fixtures/listen-s13.hl7", "--output", casePath); err != nil || stderr != "" {
		t.Fatalf("capture: %v %s", err, stderr)
	}
	// Both documents are authored beside the evidence, which is how the window
	// reaches them: one entry of the folder the person opened, never a path.
	declared, err := os.ReadFile(correlateRules)
	if err != nil {
		t.Fatal(err)
	}
	rules := filepath.Join(workspace, "rules.json")
	if err := os.WriteFile(rules, declared, 0o600); err != nil {
		t.Fatal(err)
	}
	reported, stderr, err := run(t, "correlate", casePath, "--rules", rules, "--format", "json")
	if err != nil || stderr != "" {
		t.Fatalf("correlate: %v %s", err, stderr)
	}
	report := readStrictOutput[correlate.Report](t, reported)
	plan := filepath.Join(workspace, "plan.json")
	if err := os.WriteFile(plan, []byte(`{"schema":"`+transform.PlanSchema+`","case":"`+report.CaseIdentity+
		`","rules":"`+report.RulesSHA256+`","steps":[`+
		`{"operator":"rebase-identifiers/v1","rule":"patient"},`+
		`{"operator":"shift-dates/v1","shift":"24h"},`+
		`{"operator":"duplicate-occurrence/v1","entry":"t000001"}]}`), 0o600); err != nil {
		t.Fatal(err)
	}

	printed, stderr, err := run(t, "transform", casePath, "--rules", rules, "--plan", plan, "--format", "json")
	if err != nil || stderr != "" {
		t.Fatalf("transform: %v %s", err, stderr)
	}
	previewed := readStrictOutput[transform.Preview](t, printed)

	app := desktopApp(t, workspace)
	opened := app.OpenCase(workspace, "incident")
	if opened.State != desktop.Completed || opened.Case == nil {
		t.Fatalf("the case was not verified: %+v", opened)
	}
	result := app.PreviewTransformation(desktop.TransformRequest{
		Workspace: workspace, Case: "incident", Identity: opened.Case.Identity,
		Rules: "rules.json", Plan: "plan.json",
	})
	if result.State != desktop.Completed || result.Transformation == nil {
		t.Fatalf("the window did not preview the plan: %+v", result)
	}
	if !reflect.DeepEqual(result.Transformation.Preview, previewed) {
		t.Fatalf("the window previewed %+v and the command line %+v", result.Transformation.Preview, previewed)
	}
	// The one thing this panel must never do. The plan renames an identifier and
	// shifts every supported timestamp; neither the value that was there nor the
	// surrogate that would replace it crosses the boundary.
	encoded, err := json.Marshal(result)
	if err != nil {
		t.Fatal(err)
	}
	for _, value := range []string{"SYNTH-001", "LISTEN-BOOK", "READMIT000001", "20260102100000"} {
		if strings.Contains(string(encoded), value) {
			t.Fatalf("the window disclosed a transformed or original value: %s", encoded)
		}
	}
}

// Every outcome a comparison of retained runs refuses to call proof, against
// real runs. A verdict that moved is not a surviving failure, two runs of
// different expectations are not comparable at all, and an execution error
// leaves every expectation unevaluated rather than passing or failing it.
func TestDesktopRevisionProofNamesWhatItCannotCallProof(t *testing.T) {
	app, workspace, original, transformed, _ := revisionWorkspace(t)
	spec := rescheduleSpec(t)
	// The same expectations, the corrected receiver on one side and the
	// defective one on the other.
	failing := runRevision(t, workspace, original, "failing-run", "defective", spec, 1)
	fixed := runRevision(t, workspace, transformed, "fixed-run", "fixed", spec, 0)
	// The same receiver, one expectation changed: a test that expects the two
	// appointments the defect produces is a different test, not a fixed one.
	expectsTwo := bytes.Replace(spec, []byte(`"expected": {"count": 1}`), []byte(`"expected": {"count": 2}`), 1)
	if bytes.Equal(expectsTwo, spec) {
		t.Fatal("the committed spec no longer carries the expectation this test varies")
	}
	other := runRevision(t, workspace, transformed, "other-test-run", "defective", expectsTwo, 1)
	// A target nothing is listening on: the run is retained, it is bound to this
	// revision, and it reached no expectation at all.
	unreached := runRevision(t, workspace, transformed, "unreached-run", "", spec, 2)

	outcomes := func(left, right string) (reproducer.Proof, map[string]string) {
		t.Helper()
		result := app.CompareReproducers(desktop.ReproducerComparisonRequest{
			Workspace: workspace, Left: original, Right: transformed,
			LeftResult: left, RightResult: right,
		})
		if result.State != desktop.Completed || result.Comparison == nil {
			t.Fatalf("two revisions with retained runs were not compared: %+v", result)
		}
		named := map[string]string{}
		for _, assertion := range result.Comparison.Proof.Assertions {
			named[assertion.Assertion] = assertion.Outcome
		}
		return result.Comparison.Proof, named
	}

	moved, named := outcomes(failing, fixed)
	if moved.State != reproducer.ProofCompared || named["one-appointment"] != reproducer.VerdictMoved {
		t.Fatalf("a verdict that moved was not reported as one: %+v", moved)
	}
	if named["booking-ack"] != reproducer.SamePass {
		t.Fatalf("an unchanged expectation was reported as moved: %+v", named)
	}

	different, named := outcomes(failing, other)
	if different.State != reproducer.ProofDifferentTest || len(named) != 0 {
		t.Fatalf("two runs of different expectations were paired anyway: %+v", different)
	}
	// Both runs are still reported, because which one decided what is the answer
	// in that case.
	if different.Left == nil || different.Right == nil || different.Right.Status != string(testrunner.AssertionFailure) {
		t.Fatalf("an incomparable pair hid the runs it read: %+v", different)
	}

	errored, named := outcomes(failing, unreached)
	if errored.State != reproducer.ProofCompared || errored.Right.Status != string(testrunner.ExecutionError) {
		t.Fatalf("an execution error was not reported as one: %+v", errored)
	}
	if errored.Right.ErrorClass == "" {
		t.Fatal("an execution error was reported without the class it recorded")
	}
	for _, expectation := range []string{"one-appointment", "original-record-moved", "booking-ack", "rescheduling-ack"} {
		if named[expectation] != reproducer.NotEvaluated {
			t.Fatalf("an execution error read as a verdict on %s: %q", expectation, named[expectation])
		}
	}
}

// The proof the window shows for two revisions is the command line's reading of
// the same two runs. Each side names the result identity and outcome `readmit
// diff` reads out of that run's directory and the case identity the run
// recorded as its input, and each expectation carries the verdict the result
// reader re-derives from what that run retained, in the order the test
// declared them. The window decides none of it.
func TestRevisionProofIsWhatTheCommandLineReadsFromEachRun(t *testing.T) {
	app, workspace, original, transformed, _ := revisionWorkspace(t)
	spec := rescheduleSpec(t)
	failing := runRevision(t, workspace, original, "failing-run", "defective", spec, 1)
	fixed := runRevision(t, workspace, transformed, "fixed-run", "fixed", spec, 0)

	compared := app.CompareReproducers(desktop.ReproducerComparisonRequest{
		Workspace: workspace, Left: original, Right: transformed,
		LeftResult: failing, RightResult: fixed,
	})
	if compared.State != desktop.Completed || compared.Comparison == nil || compared.Comparison.Proof.State != reproducer.ProofCompared {
		t.Fatalf("two revisions with runs of the same test were not compared: %+v", compared)
	}
	proof := compared.Comparison.Proof
	report, _ := diffJSON(t, filepath.Join(workspace, failing), filepath.Join(workspace, fixed), "--key", "MSH-10")
	for _, side := range []struct {
		run    string
		window *reproducer.ProofSide
		read   diff.InputSummary
	}{{failing, proof.Left, report.Left}, {fixed, proof.Right, report.Right}} {
		retained, err := testrunner.Open(filepath.Join(workspace, side.run))
		if err != nil {
			t.Fatal(err)
		}
		if side.read.Kind != "result" || side.window.Identity != side.read.Identity || side.window.Status != side.read.ResultStatus ||
			side.window.Case != retained.Result.InputBundleIdentity {
			t.Fatalf("the window names %s as %+v; readmit diff read %+v and the run recorded input %s",
				side.run, side.window, side.read, retained.Result.InputBundleIdentity)
		}
	}
	left, err := testrunner.Open(filepath.Join(workspace, failing))
	if err != nil {
		t.Fatal(err)
	}
	right, err := testrunner.Open(filepath.Join(workspace, fixed))
	if err != nil {
		t.Fatal(err)
	}
	if len(proof.Assertions) != len(left.Result.Assertions) || len(proof.Assertions) != len(right.Result.Assertions) {
		t.Fatalf("the window reported %d expectations of runs that evaluated %d and %d",
			len(proof.Assertions), len(left.Result.Assertions), len(right.Result.Assertions))
	}
	for i, assertion := range proof.Assertions {
		declared := left.Result.Assertions[i].Assertion
		if assertion.Assertion != declared.ID || assertion.Operator != declared.Operator ||
			assertion.LeftVerdict != left.Result.Assertions[i].Status || assertion.RightVerdict != right.Result.Assertions[i].Status {
			t.Fatalf("expectation %d reads %+v in the window; the runs recorded %s and %s for %s",
				i, assertion, left.Result.Assertions[i].Status, right.Result.Assertions[i].Status, declared.ID)
		}
	}
}

// The whole disclosure-review delivery, across both entry points. The command
// line derives a reviewed extract from a synthetic planted-identifier corpus;
// the window reads that review back, inventories every export surface it found,
// and states the reviewer's decision. The identity the window approves is
// exactly the identity the export gate requires, and nothing else approves it.
func TestDesktopReviewApprovesExactlyWhatTheExportGateRequires(t *testing.T) {
	workspace := t.TempDir()
	request := redactFixture(t)
	request.Output = filepath.Join(workspace, "review")
	if _, out, err := run(t, "redact", request.CasePath, "--spec", request.SpecPath,
		"--policy", request.PolicyPath, "--inventory", request.InventoryPath,
		"--local-state", request.LocalState, "--output", request.Output); err != nil {
		t.Fatalf("redact: %v %s", err, out)
	}
	created, err := redact.OpenReview(request.Output)
	if err != nil || created.State != "ready-for-approval" {
		t.Fatalf("review: %+v %v", created, err)
	}

	app := desktopApp(t, workspace)
	read := func(approve string) *desktop.Review {
		t.Helper()
		result := app.OpenReview(desktop.ReviewRequest{
			Workspace: workspace, Review: "review", Approve: approve,
			Offset: 0, Limit: desktop.MaxReviewFindings,
		})
		if result.State != desktop.Completed || result.Review == nil {
			t.Fatalf("the window did not read the review: %+v", result)
		}
		return result.Review
	}

	undecided := read("")
	if undecided.Decision != desktop.NotDecided || undecided.Identity != created.Identity {
		t.Fatalf("an unapproved review was not reported as undecided: %+v", undecided)
	}
	// Every surface of the corpus is inventoried, and the counts are the whole
	// of what the review found rather than a selection of it.
	counted := 0
	for _, surface := range undecided.Surfaces {
		counted += surface.Findings
	}
	if counted != undecided.Total || undecided.Total != len(created.Findings) {
		t.Fatalf("the window inventoried %d of the review's %d findings", counted, len(created.Findings))
	}
	if undecided.Establishes != desktop.DisclosureReviewed {
		t.Fatalf("a ready review did not say what it establishes: %q", undecided.Establishes)
	}

	// An approval of anything but these exact bytes is stale, because the review
	// identity binds the input, the policy, the specification and the output.
	stale := read(strings.Repeat("0", 64))
	if stale.Decision != desktop.StaleApproval {
		t.Fatalf("an approval of other bytes was accepted: %+v", stale)
	}

	approved := read(created.Identity)
	if approved.Decision != desktop.Approved {
		t.Fatalf("the exact identity did not approve the review: %+v", approved)
	}

	// And the identity the window approved is the one the export gate requires:
	// the command line exports under it, and the packet records it as approved.
	packet := filepath.Join(t.TempDir(), "packet")
	if _, out, err := run(t, "redact", "export", request.Output,
		"--local-state", request.LocalState, "--approve", approved.Identity, "--output", packet); err != nil {
		t.Fatalf("export: %v %s", err, out)
	}
	manifest := readStrictDocument[redact.ExportManifest](t, filepath.Join(packet, "export-review.json"))
	if manifest.ApprovedReview != approved.Identity {
		t.Fatalf("the packet was approved under %s and the window under %s", manifest.ApprovedReview, approved.Identity)
	}

	// A reviewed extract is ordinary verified evidence, so the transformed values
	// a reviewer has to read are read where every other value in this window is
	// read: the review folder opens as a workspace, its derived case is verified
	// by the same reader, and the inspector reveals one position of it. The
	// planted original is not there, and the review itself carried no value to
	// get here.
	derived := desktopApp(t, request.Output)
	listed := derived.OpenWorkspace(request.Output)
	if listed.State != desktop.Completed || listed.Workspace == nil {
		t.Fatalf("the review folder did not open as a workspace: %+v", listed)
	}
	extract := derived.OpenCase(request.Output, "case")
	if extract.State != desktop.Completed || extract.Case == nil {
		t.Fatalf("the derived case of the review was not verified: %+v", extract)
	}
	if extract.Case.Identity != approved.DerivedIdentity {
		t.Fatalf("the window verified %s and the review named %s", extract.Case.Identity, approved.DerivedIdentity)
	}
	inspected := derived.InspectOccurrence(desktop.InspectRequest{
		Workspace: request.Output, Case: "case", Identity: extract.Case.Identity,
		Occurrence: "s0001-e000001", Path: "PID-3.1", ByteOffset: -1,
	})
	if inspected.State != desktop.Completed || inspected.Inspection == nil {
		t.Fatalf("the transformed value of the extract could not be read: %+v", inspected)
	}
	if inspected.Inspection.Decoded == "" || strings.Contains(inspected.Inspection.Decoded, "PLANTED-PATIENT-7391") {
		t.Fatalf("the derived case did not hold a transformed value in place of the planted one: %q", inspected.Inspection.Decoded)
	}

	// The corpus plants a value on every surface a review inventories. None of
	// them reaches the window, and the private state directory holding the
	// mappings and the offsets is never named, opened or read.
	encoded, err := json.Marshal(approved)
	if err != nil {
		t.Fatal(err)
	}
	for _, planted := range []string{
		"PLANTED-PATIENT-7391", "PLANTED-NAME-ORCHID", "PLANTED-NTE-ALDER",
		"PLANTED-ERR-BIRCH", "PLANTED-ACK-WILLOW", "PLANTED-EMBEDDED-ELM",
		"PLANTED-UNKNOWN-ASH", "PLANTED-FILENAME-CEDAR", "PLANTED-SPEC-JUNIPER",
		"PLANTED-RESET-SPRUCE",
	} {
		if strings.Contains(string(encoded), planted) {
			t.Fatalf("the window disclosed the planted value %s", planted)
		}
	}
}

func desktopApp(t *testing.T, folder string) *desktop.App {
	t.Helper()
	app := unlicensedDesktopApp(t, folder)
	if result := app.SelectOperationPolicy(testlicense.New(t)); result.State != desktop.Completed {
		t.Fatal(result)
	}
	return app
}
