package tests

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/bharm16/readmit/internal/testrunner"
)

// These bytes were retained by the installed macOS native UI, not generated by
// this test. Reopening them verifies every result/run/payload and re-evaluates
// the assertions offline. It does not claim today's UI was exercised by Go.
func TestRetainedNativeDesktopJourneyIsIndependentlyReadable(t *testing.T) {
	root := "../testdata/acceptance/native-109"
	for _, row := range []struct {
		name   string
		status testrunner.Status
		count  int
	}{
		{"baseline", testrunner.AssertionFailure, 2}, {"post-fix", testrunner.Pass, 1},
	} {
		artifact, err := testrunner.Open(filepath.Join(root, row.name))
		if err != nil {
			t.Fatal(err)
		}
		if artifact.Result.Status != row.status || len(artifact.Result.Assertions) != 1 {
			t.Fatalf("wrong retained verdict: %+v", artifact.Result)
		}
		observed := artifact.Result.Assertions[0].Observed
		if observed == nil || observed.Count == nil || *observed.Count != row.count {
			t.Fatalf("wrong ledger count: %+v", observed)
		}
	}
	report, _ := diffJSON(t, filepath.Join(root, "baseline"), filepath.Join(root, "post-fix"))
	if report.Left.ResultStatus != "assertion_failure" || report.Right.ResultStatus != "pass" || report.Summary.Paired != 2 || report.Summary.Unchanged != 2 || report.Summary.FieldChanges != 0 {
		t.Fatalf("native retained comparison: %+v", report)
	}
	broken := filepath.Join(t.TempDir(), "interrupted")
	copyTree(t, filepath.Join(root, "post-fix"), broken)
	if err := os.Remove(filepath.Join(broken, "observation.json")); err != nil {
		t.Fatal(err)
	}
	if _, _, err := run(t, "diff", filepath.Join(root, "baseline"), broken); err == nil {
		t.Fatal("missing native observation passed")
	}
}
