package tests

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// The certificates below are generated by the test that uses them, for one test
// process, under a temporary directory it removes. None is committed, and every
// listener here is on loopback, on port 0, and closed by the test.
const testOnlyServerName = "lab.example.invalid"

// testOnlyTLS returns a PEM CA and a server configuration presenting one leaf
// certificate that CA issued for testOnlyServerName.
func testOnlyTLS(t *testing.T) ([]byte, *tls.Config) {
	t.Helper()
	authorityKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	authority := &x509.Certificate{
		SerialNumber:          serialNumber(t),
		Subject:               pkix.Name{CommonName: "readmit test-only authority"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(time.Hour),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}
	authorityDER, err := x509.CreateCertificate(rand.Reader, authority, authority, authorityKey.Public(), authorityKey)
	if err != nil {
		t.Fatal(err)
	}
	signer, err := x509.ParseCertificate(authorityDER)
	if err != nil {
		t.Fatal(err)
	}
	leafKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	leaf := &x509.Certificate{
		SerialNumber: serialNumber(t),
		Subject:      pkix.Name{CommonName: testOnlyServerName},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     []string{testOnlyServerName},
	}
	leafDER, err := x509.CreateCertificate(rand.Reader, leaf, signer, leafKey.Public(), authorityKey)
	if err != nil {
		t.Fatal(err)
	}
	encodedKey, err := x509.MarshalECPrivateKey(leafKey)
	if err != nil {
		t.Fatal(err)
	}
	pair, err := tls.X509KeyPair(
		pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: leafDER}),
		pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: encodedKey}),
	)
	if err != nil {
		t.Fatal(err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: authorityDER}),
		&tls.Config{Certificates: []tls.Certificate{pair}}
}

func serialNumber(t *testing.T) *big.Int {
	t.Helper()
	number, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 96))
	if err != nil {
		t.Fatal(err)
	}
	return number
}

// quietEndpoint accepts on loopback, completes TLS when a configuration is
// given, never answers, and counts every byte it was sent.
func quietEndpoint(t *testing.T, config *tls.Config) (string, *atomic.Int64) {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	received := &atomic.Int64{}
	done := make(chan struct{})
	go func() {
		defer close(done)
		for {
			connection, err := listener.Accept()
			if err != nil {
				return
			}
			go func() {
				defer connection.Close()
				var stream net.Conn = connection
				if config != nil {
					server := tls.Server(connection, config)
					if err := server.Handshake(); err != nil {
						return
					}
					stream = server
				}
				buffer := make([]byte, 512)
				for {
					n, err := stream.Read(buffer)
					received.Add(int64(n))
					if err != nil {
						return
					}
				}
			}()
		}
	}()
	t.Cleanup(func() {
		listener.Close()
		<-done
	})
	return listener.Addr().String(), received
}

// One environment is recorded, validated and reached through the command line,
// and the endpoint is sent nothing at all while that happens.
func TestTargetRecordsValidatesAndReachesANamedEnvironment(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "lab.json")
	address, received := quietEndpoint(t, nil)
	stdout, stderr, err := run(t, "target", "set", "--target", path,
		"--name", "lab-siu", "--classification", "nonproduction", "--address", address,
		"--connect-timeout", "2s", "--message-timeout", "200ms")
	if err != nil || stderr != "" {
		t.Fatalf("target set: %v %s", err, stderr)
	}
	for _, want := range []string{"Environment recorded: lab-siu", "Classification: nonproduction", "readmit-target/v3", "Timeouts: connect=2s message=200ms"} {
		if !strings.Contains(stdout, want) {
			t.Errorf("target set output is missing %q:\n%s", want, stdout)
		}
	}
	stdout, stderr, err = run(t, "target", "show", "--target", path)
	if err != nil || stderr != "" || !strings.Contains(stdout, "Configuration: valid; no connection was opened") {
		t.Fatalf("target show: %v %s %s", err, stdout, stderr)
	}
	stdout, stderr, err = run(t, "target", "check", "--target", path)
	if err != nil || stderr != "" {
		t.Fatalf("target check: %v %s", err, stderr)
	}
	for _, want := range []string{"Diagnosis: reachable", "Reached: " + address, "No HL7 payload was sent"} {
		if !strings.Contains(stdout, want) {
			t.Errorf("target check output is missing %q:\n%s", want, stdout)
		}
	}
	if got := received.Load(); got != 0 {
		t.Fatalf("a connectivity check sent %d bytes to the endpoint; it must send none", got)
	}

	// Editing keeps everything the same run did not restate.
	stdout, stderr, err = run(t, "target", "set", "--target", path, "--classification", "production")
	if err != nil || stderr != "" {
		t.Fatalf("target set edit: %v %s", err, stderr)
	}
	if !strings.Contains(stdout, "Classification: production") || !strings.Contains(stdout, "Environment: lab-siu") {
		t.Fatalf("an edited configuration lost what it did not restate:\n%s", stdout)
	}
}

// A CA and a server name are configured explicitly, the negotiated session is
// reported in full, and a name the certificate was not issued to is refused by
// its own name rather than accepted.
func TestTargetCheckReportsTLSStatusAndNamesACertificateFailure(t *testing.T) {
	directory := t.TempDir()
	authority, server := testOnlyTLS(t)
	caFile := filepath.Join(directory, "ca.pem")
	if err := os.WriteFile(caFile, authority, 0600); err != nil {
		t.Fatal(err)
	}
	address, received := quietEndpoint(t, server)
	path := filepath.Join(directory, "tls.json")
	if _, stderr, err := run(t, "target", "set", "--target", path,
		"--name", "lab-tls", "--classification", "nonproduction", "--address", address,
		"--transport", "tls", "--ca", caFile, "--server-name", testOnlyServerName,
		"--connect-timeout", "2s", "--message-timeout", "200ms"); err != nil || stderr != "" {
		t.Fatalf("target set: %v %s", err, stderr)
	}
	stdout, stderr, err := run(t, "target", "check", "--target", path)
	if err != nil || stderr != "" {
		t.Fatalf("target check: %v %s", err, stderr)
	}
	for _, want := range []string{"Diagnosis: reachable", "Certificate authority: explicitly configured", "TLS: TLS 1.", "server_name=" + testOnlyServerName, "certificate 1: subject=CN=" + testOnlyServerName, "not_after="} {
		if !strings.Contains(stdout, want) {
			t.Errorf("target check output is missing %q:\n%s", want, stdout)
		}
	}
	if got := received.Load(); got != 0 {
		t.Fatalf("a TLS check sent %d bytes to the endpoint; it must send none", got)
	}

	if _, stderr, err := run(t, "target", "set", "--target", path, "--server-name", "other.example.invalid"); err != nil || stderr != "" {
		t.Fatalf("target set: %v %s", err, stderr)
	}
	stdout, stderr, err = run(t, "target", "check", "--target", path)
	if err == nil {
		t.Fatal("a certificate issued to another name was accepted")
	}
	if !strings.Contains(stdout, "Diagnosis: tls_hostname_mismatch") || !strings.Contains(stderr, "was not reached") {
		t.Fatalf("a hostname mismatch was not named:\n%s\n%s", stdout, stderr)
	}
}

// Every configuration the contract refuses is refused through the command line
// too, and an earlier contract version is reported rather than rewritten.
func TestTargetSetRefusesWhatTheContractRefuses(t *testing.T) {
	directory := t.TempDir()
	previous := filepath.Join(directory, "v1.json")
	if err := os.WriteFile(previous, []byte(`{"schema":"readmit-target/v1","test_endpoint":true,"address":"127.0.0.1:2575","transport":"plain","approved_transport":false,"connect_timeout":"2s","message_timeout":"5s","max_ack_bytes":4096}`), 0600); err != nil {
		t.Fatal(err)
	}
	before, err := os.ReadFile(previous)
	if err != nil {
		t.Fatal(err)
	}
	for name, testCase := range map[string]struct {
		args []string
		want string
	}{
		"a classification outside the closed set": {
			args: []string{"target", "set", "--target", filepath.Join(directory, "a.json"), "--name", "lab", "--classification", "staging", "--address", "127.0.0.1:2575"},
			want: "requires an explicit classification",
		},
		"no classification at all": {
			args: []string{"target", "set", "--target", filepath.Join(directory, "b.json"), "--name", "lab", "--address", "127.0.0.1:2575"},
			want: "requires an explicit classification",
		},
		"a client certificate with no private key reference": {
			args: []string{"target", "set", "--target", filepath.Join(directory, "c.json"), "--name", "lab", "--classification", "nonproduction", "--address", "127.0.0.1:2575", "--transport", "tls", "--client-certificate", "client.pem"},
			want: "private key",
		},
		"a nonloopback address without explicit approval": {
			args: []string{"target", "set", "--target", filepath.Join(directory, "d.json"), "--name", "lab", "--classification", "nonproduction", "--address", "10.0.0.1:2575"},
			want: "approved_transport",
		},
		"an earlier contract version": {
			args: []string{"target", "set", "--target", previous, "--name", "lab", "--classification", "nonproduction"},
			want: "readmit-target/v1",
		},
	} {
		stdout, stderr, err := run(t, testCase.args...)
		if err == nil {
			t.Errorf("%s was accepted:\n%s", name, stdout)
			continue
		}
		if !strings.Contains(stderr, testCase.want) {
			t.Errorf("%s was refused as %q, want %q", name, stderr, testCase.want)
		}
	}
	after, err := os.ReadFile(previous)
	if err != nil || string(after) != string(before) {
		t.Fatalf("an earlier contract version was rewritten: %v", err)
	}
	for _, name := range []string{"a.json", "b.json", "c.json", "d.json"} {
		if _, err := os.Lstat(filepath.Join(directory, name)); !os.IsNotExist(err) {
			t.Errorf("a refused configuration left %s behind", name)
		}
	}
}

// A replay states the environment it is pointed at before it reports anything
// else, so nobody has to open the configuration to see what it is.
func TestReplayShowsTheRecordedClassification(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "lab.json")
	address, _ := quietEndpoint(t, nil)
	if _, stderr, err := run(t, "target", "set", "--target", path,
		"--name", "lab-siu", "--classification", "production", "--address", address,
		"--connect-timeout", "1s", "--message-timeout", "200ms"); err != nil || stderr != "" {
		t.Fatalf("target set: %v %s", err, stderr)
	}
	stdout, stderr, err := run(t, "replay", replayCase(t), "--target", path)
	if err != nil || stderr != "" {
		t.Fatalf("replay preview: %v %s", err, stderr)
	}
	if !strings.Contains(stdout, "Environment: lab-siu") || !strings.Contains(stdout, "Classification: production") {
		t.Fatalf("a replay preview did not state the environment it is pointed at:\n%s", stdout)
	}
	previous, _, err := run(t, "replay", replayCase(t), "--target", replayTarget(t, address))
	if err != nil {
		t.Fatalf("replay preview of readmit-target/v1: %v", err)
	}
	if !strings.Contains(previous, "Classification: unclassified") {
		t.Fatalf("a configuration with no recorded classification was not reported as unclassified:\n%s", previous)
	}
}
