package observesource_test

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"net"
	"net/http"
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/bharm16/readmit/internal/observesource"
	"github.com/bharm16/readmit/internal/observewindow"
	"github.com/bharm16/readmit/internal/sendpolicy"
)

// providerSwitch re-enters this test binary as the operator-declared program
// that prints a credential. A locator is an argument; a value never is.
const providerSwitch = "READMIT_TEST_ONLY_OBSERVE_PROVIDER"

func TestMain(m *testing.M) {
	if _, declared := os.LookupEnv(providerSwitch); declared {
		os.Exit(provider(os.Args[1:]))
	}
	os.Exit(m.Run())
}

func provider(arguments []string) int {
	if len(arguments) != 1 {
		return 4
	}
	data, err := os.ReadFile(arguments[0])
	if err != nil {
		return 5
	}
	if _, err := os.Stdout.Write(data); err != nil {
		return 6
	}
	return 0
}

// Every certificate and key below is generated by the test that uses them, for
// one test process, under a temporary directory it removes. None is committed,
// every listener is on loopback, on port 0, and closed by the test, and nothing
// here reaches a host outside this machine.
type authority struct {
	certificate *x509.Certificate
	key         *ecdsa.PrivateKey
	pem         []byte
}

func newAuthority(t *testing.T) *authority {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	template := &x509.Certificate{
		SerialNumber: serialNumber(t), Subject: pkix.Name{CommonName: "readmit test-only observation authority"},
		NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().Add(time.Hour),
		KeyUsage: x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		IsCA:     true, BasicConstraintsValid: true,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, key.Public(), key)
	if err != nil {
		t.Fatal(err)
	}
	signed, err := x509.ParseCertificate(der)
	if err != nil {
		t.Fatal(err)
	}
	return &authority{certificate: signed, key: key, pem: pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})}
}

// leaf signs one server certificate. The identity is explicit, so a test that
// needs a certificate naming the wrong host generates exactly that one.
func (a *authority) leaf(t *testing.T, addresses []net.IP, names []string) tls.Certificate {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	template := &x509.Certificate{
		SerialNumber: serialNumber(t), Subject: pkix.Name{CommonName: "readmit test-only observation endpoint"},
		NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().Add(time.Hour),
		KeyUsage: x509.KeyUsageDigitalSignature, ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		IPAddresses: addresses, DNSNames: names,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, a.certificate, key.Public(), a.key)
	if err != nil {
		t.Fatal(err)
	}
	encoded, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		t.Fatal(err)
	}
	pair, err := tls.X509KeyPair(pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}),
		pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: encoded}))
	if err != nil {
		t.Fatal(err)
	}
	return pair
}

func serialNumber(t *testing.T) *big.Int {
	t.Helper()
	number, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 96))
	if err != nil {
		t.Fatal(err)
	}
	return number
}

// endpoint starts one loopback TLS listener on port 0 and closes it when the
// test ends. No listener outlives the test that started it.
func endpoint(t *testing.T, pair tls.Certificate, handler http.Handler) string {
	t.Helper()
	listener, err := tls.Listen("tcp", "127.0.0.1:0", &tls.Config{MinVersion: tls.VersionTLS12, Certificates: []tls.Certificate{pair}})
	if err != nil {
		t.Fatal(err)
	}
	server := &http.Server{Handler: handler, ReadHeaderTimeout: 5 * time.Second}
	done := make(chan struct{})
	go func() {
		defer close(done)
		_ = server.Serve(listener)
	}()
	t.Cleanup(func() {
		_ = server.Close()
		<-done
	})
	return listener.Addr().String()
}

const declaredHTTPWindow = `{
  "schema": "readmit-observation-window/v1",
  "source": {"kind": "http-api", "identity": "scheduling-api", "scope": "appointments"},
  "watermark": {"kind": "none", "position": ""},
  "pre_existing_state": {"declaration": "declared-empty", "baseline_identity": ""},
  "completion": {"deadline": "5s", "quiet_period": "10ms", "stable_samples": 2, "max_records": 100, "max_samples": 64}
}`

const declaredHTTPSource = `{
  "schema": "readmit-observation-source/v1",
  "source": {"kind": "http-api", "identity": "scheduling-api", "scope": "appointments"},
  "enabled": true,
  "freshness": {"max_age": "1h"},
  "extraction": {
    "envelope": "json",
    "encoding": "utf-8",
    "json": {"record_path": ["appointments"]},
    "record_key": ["id"]
  },
  "file": null,
  "http": {
    "url": "ENDPOINT",
    "classification": "nonproduction",
    "ca_file": "ca.pem",
    "server_name": "",
    "timeout": "3s",
    "max_bytes": 65536,
    "retry": {"attempts": 0, "delay": "5ms"},
    "credential": null
  }
}`

const appointmentBody = `{"appointments":[{"id":"A1"},{"id":"A2"}]}`

// declaredHTTP writes one source document beside the certificate authority it
// names and reads it back through the same public reader a command uses.
func declaredHTTP(t *testing.T, ca []byte, address, document string) (observesource.Source, string) {
	t.Helper()
	directory := t.TempDir()
	write(t, directory, "ca.pem", string(ca))
	document = strings.Replace(document, "ENDPOINT", "https://"+address+"/appointments", 1)
	path := write(t, directory, "source.json", document)
	source, err := observesource.ReadSource(path)
	if err != nil {
		t.Fatal(err)
	}
	return source, filepath.Join(t.TempDir(), "snapshot")
}

func loopback(t *testing.T, handler http.Handler) ([]byte, string) {
	t.Helper()
	ca := newAuthority(t)
	return ca.pem, endpoint(t, ca.leaf(t, []net.IP{net.ParseIP("127.0.0.1")}, nil), handler)
}

func answer(body string, prepare func(http.Header)) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		if prepare != nil {
			prepare(w.Header())
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(body))
	})
}

func TestAnApprovedEndpointCompletesTheWindowOverTLS(t *testing.T) {
	ca, address := loopback(t, answer(appointmentBody, nil))
	source, snapshot := declaredHTTP(t, ca, address, declaredHTTPSource)
	completion := collect(t, source, window(t, declaredHTTPWindow), snapshot, "A1")
	if err := completion.Err(); err != nil {
		t.Fatalf("collection did not complete: %v", err)
	}
	if completion.RecordsObserved != 2 {
		t.Fatalf("records observed = %d, want 2", completion.RecordsObserved)
	}
	if err := completion.Correlated("A1"); err != nil {
		t.Fatalf("A1 was observed exactly once: %v", err)
	}
	// The destination decision is retained beside the material it governed.
	if _, err := os.Stat(filepath.Join(snapshot, "decision.json")); err != nil {
		t.Fatalf("the destination decision was not retained: %v", err)
	}
}

func TestAnHTTPReadThatFailedIsNeverAPassingAbsenceAssertion(t *testing.T) {
	for _, test := range []struct {
		name    string
		source  func(string) string
		handler http.Handler
		status  observewindow.Status
	}{
		{
			name:    "unauthorized",
			handler: http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusUnauthorized) }),
			status:  observewindow.Failed,
		},
		{
			name:    "not found",
			handler: http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusNotFound) }),
			status:  observewindow.Failed,
		},
		{
			name: "server error past every retry",
			source: func(document string) string {
				return strings.Replace(document, `"attempts": 0`, `"attempts": 2`, 1)
			},
			handler: http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusServiceUnavailable) }),
			status:  observewindow.Failed,
		},
		{
			name: "redirection",
			handler: http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				w.Header().Set("Location", "/elsewhere")
				w.WriteHeader(http.StatusFound)
			}),
			status: observewindow.Ambiguous,
		},
		{
			name: "response stating neither its age nor when it was generated",
			handler: http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				w.Header()["Date"] = nil
				_, _ = w.Write([]byte(appointmentBody))
			}),
			status: observewindow.Ambiguous,
		},
		{
			name:    "cached response past the declared freshness bound",
			handler: answer(appointmentBody, func(header http.Header) { header.Set("Age", "7200") }),
			status:  observewindow.Stale,
		},
		{
			name: "response larger than the declared read bound",
			source: func(document string) string {
				return strings.Replace(document, `"max_bytes": 65536`, `"max_bytes": 8`, 1)
			},
			handler: answer(appointmentBody, nil),
			status:  observewindow.Truncated,
		},
		{
			name:    "response that is not the declared schema",
			handler: answer(`{"other":[{"id":"A1"}]}`, nil),
			status:  observewindow.Ambiguous,
		},
		{
			name:    "connection lost before the body arrived",
			handler: http.HandlerFunc(lostConnection),
			status:  observewindow.Failed,
		},
		{
			name: "read that ran out of its own time",
			source: func(document string) string {
				return strings.Replace(document, `"timeout": "3s"`, `"timeout": "50ms"`, 1)
			},
			handler: http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
				select {
				case <-request.Context().Done():
				case <-time.After(3 * time.Second):
				}
			}),
			status: observewindow.Failed,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			document := declaredHTTPSource
			if test.source != nil {
				document = test.source(document)
			}
			ca, address := loopback(t, test.handler)
			source, snapshot := declaredHTTP(t, ca, address, document)
			completion := collect(t, source, window(t, declaredHTTPWindow), snapshot)
			if completion.Status != test.status {
				t.Fatalf("status = %q, want %q", completion.Status, test.status)
			}
			if err := completion.AbsenceEvidence(); err == nil {
				t.Fatal("a failed read supported an absence assertion")
			}
			if completion.RecordsObserved != 0 {
				t.Fatal("a window that did not complete reported a settled count")
			}
			if completion.Status.RunState() != "execution_error" {
				t.Fatalf("run state = %q, want execution_error", completion.Status.RunState())
			}
		})
	}
}

// lostConnection promises more bytes than it sends and then drops the socket,
// which is what a read that lost its connection mid-body sees.
func lostConnection(w http.ResponseWriter, _ *http.Request) {
	hijacker, ok := w.(http.Hijacker)
	if !ok {
		return
	}
	connection, _, err := hijacker.Hijack()
	if err != nil {
		return
	}
	_, _ = connection.Write([]byte("HTTP/1.1 200 OK\r\nDate: " + time.Now().UTC().Format(http.TimeFormat) +
		"\r\nContent-Length: 400\r\n\r\n{\"appointments\":["))
	_ = connection.Close()
}

func TestARetryRecoversOnlyWhatProducedNoAnswerAtAll(t *testing.T) {
	var attempts atomic.Int64
	ca, address := loopback(t, http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		if attempts.Add(1) == 1 {
			w.WriteHeader(http.StatusServiceUnavailable)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(appointmentBody))
	}))
	source, snapshot := declaredHTTP(t, ca, address, strings.Replace(declaredHTTPSource, `"attempts": 0`, `"attempts": 2`, 1))
	completion := collect(t, source, window(t, declaredHTTPWindow), snapshot)
	if err := completion.Err(); err != nil {
		t.Fatalf("a bounded retry of a read that produced no answer did not recover: %v", err)
	}
	// The retry is recorded rather than invisible: the first read's own record
	// states that it took two attempts.
	record, err := os.ReadFile(filepath.Join(snapshot, "read-0000", "read.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(record), `"attempts":2`) || !strings.Contains(string(record), `"retries":1`) {
		t.Fatalf("the retained read does not record its retries: %s", record)
	}
}

func TestARetryNeverTurnsAnUncertainReadIntoAConfidentOne(t *testing.T) {
	var attempts atomic.Int64
	ca, address := loopback(t, http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		// A stale answer first, then a fresh one. A collector that retried the
		// stale answer would report the source as current when it is not.
		if attempts.Add(1) == 1 {
			w.Header().Set("Age", "7200")
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(appointmentBody))
	}))
	source, snapshot := declaredHTTP(t, ca, address, strings.Replace(declaredHTTPSource, `"attempts": 0`, `"attempts": 4`, 1))
	completion := collect(t, source, window(t, declaredHTTPWindow), snapshot)
	if completion.Status != observewindow.Stale {
		t.Fatalf("status = %q, want stale", completion.Status)
	}
	if attempts.Load() != 1 {
		t.Fatalf("the stale answer was read %d times; an answer is not retried", attempts.Load())
	}
}

func TestAnEndpointReadmitCannotVerifyIsRefused(t *testing.T) {
	for _, test := range []struct {
		name     string
		document func(string) string
		certify  func(t *testing.T) ([]byte, string)
	}{
		{
			name: "certificate from an authority the source does not trust",
			certify: func(t *testing.T) ([]byte, string) {
				_, address := loopback(t, answer(appointmentBody, nil))
				return newAuthority(t).pem, address
			},
		},
		{
			name: "certificate naming another host",
			document: func(document string) string {
				return strings.Replace(document, `"server_name": ""`, `"server_name": "elsewhere.example.invalid"`, 1)
			},
			certify: func(t *testing.T) ([]byte, string) {
				return loopback(t, answer(appointmentBody, nil))
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			document := declaredHTTPSource
			if test.document != nil {
				document = test.document(document)
			}
			ca, address := test.certify(t)
			source, snapshot := declaredHTTP(t, ca, address, document)
			completion := collect(t, source, window(t, declaredHTTPWindow), snapshot)
			if completion.Status != observewindow.Failed {
				t.Fatalf("status = %q, want failed", completion.Status)
			}
			if err := completion.AbsenceEvidence(); err == nil {
				t.Fatal("an unverified endpoint supported an absence assertion")
			}
		})
	}
}

func TestAProductionClassificationRefusesTheReadBeforeAnythingOpens(t *testing.T) {
	ca, address := loopback(t, answer(appointmentBody, nil))
	document := strings.Replace(declaredHTTPSource, `"classification": "nonproduction"`, `"classification": "production"`, 1)
	source, snapshot := declaredHTTP(t, ca, address, document)
	_, err := observesource.Collect(context.Background(), source, window(t, declaredHTTPWindow), observesource.Options{Snapshot: snapshot})
	if err == nil {
		t.Fatal("a production-classified endpoint was read")
	}
	if !strings.Contains(err.Error(), string(sendpolicy.ProductionClassification)) {
		t.Fatalf("refusal = %v, want the recorded production classification", err)
	}
	if _, statErr := os.Stat(filepath.Join(snapshot, "decision.json")); statErr != nil {
		t.Fatalf("the refusal was not retained: %v", statErr)
	}
}

func TestANonloopbackDestinationNeedsAnExplicitlySelectedPolicy(t *testing.T) {
	ca, address := loopback(t, answer(appointmentBody, nil))
	_, port, err := net.SplitHostPort(address)
	if err != nil {
		t.Fatal(err)
	}
	document := strings.Replace(declaredHTTPSource, "ENDPOINT", "https://lab.example.invalid:"+port+"/appointments", 1)
	source, snapshot := declaredHTTP(t, ca, "unused", document)
	_, err = observesource.Collect(context.Background(), source, window(t, declaredHTTPWindow), observesource.Options{
		Snapshot: snapshot,
		Resolve: func(context.Context, string) ([]netip.Addr, error) {
			t.Error("a destination was resolved although no policy was selected")
			return nil, nil
		},
	})
	if err == nil {
		t.Fatal("a nonloopback destination was read with no policy selected")
	}
	if !strings.Contains(err.Error(), string(sendpolicy.PolicyRequired)) {
		t.Fatalf("refusal = %v, want a policy requirement", err)
	}
}

// A read the caller cancels never completed, so it is not recorded as an
// observation that failed. The window reports the cancellation, which is
// cancellation in the durable run's own vocabulary and never a negative
// application result.
func TestCancellingDuringAReadIsCancellationRatherThanAFailedRead(t *testing.T) {
	ca, address := loopback(t, http.HandlerFunc(func(_ http.ResponseWriter, request *http.Request) {
		<-request.Context().Done()
	}))
	source, snapshot := declaredHTTP(t, ca, address, declaredHTTPSource)
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		time.Sleep(50 * time.Millisecond)
		cancel()
	}()
	completion, err := observesource.Collect(ctx, source, window(t, declaredHTTPWindow), observesource.Options{Snapshot: snapshot})
	if err != nil {
		t.Fatal(err)
	}
	if completion.Status != observewindow.Cancelled {
		t.Fatalf("status = %q, want cancelled", completion.Status)
	}
	if completion.Status.RunState() != "cancelled" {
		t.Fatalf("run state = %q, want cancelled", completion.Status.RunState())
	}
	if err := completion.AbsenceEvidence(); err == nil {
		t.Fatal("a cancelled window supported an absence assertion")
	}
}

// A retry is bounded by the window it is retried inside, not only by its own
// count: a source that never answers cannot make a read outlast the deadline.
func TestARetryNeverOutlastsTheWindowItIsRetriedInside(t *testing.T) {
	ca, address := loopback(t, http.HandlerFunc(func(_ http.ResponseWriter, request *http.Request) {
		<-request.Context().Done()
	}))
	document := strings.Replace(declaredHTTPSource, `"attempts": 0`, `"attempts": 4`, 1)
	document = strings.Replace(document, `"timeout": "3s"`, `"timeout": "5m"`, 1)
	brief := strings.Replace(declaredHTTPWindow, `"deadline": "5s"`, `"deadline": "300ms"`, 1)
	source, snapshot := declaredHTTP(t, ca, address, document)
	started := time.Now()
	completion := collect(t, source, window(t, brief), snapshot)
	if elapsed := time.Since(started); elapsed > 5*time.Second {
		t.Fatalf("the read outlasted its window by %s", elapsed)
	}
	if completion.Trustworthy() {
		t.Fatal("a window whose reads never answered reported itself as trustworthy")
	}
	if err := completion.AbsenceEvidence(); err == nil {
		t.Fatal("a window whose reads never answered supported an absence assertion")
	}
}

func TestACredentialIsPresentedFromItsReferenceAndNeverRendered(t *testing.T) {
	t.Setenv(providerSwitch, "1")
	const testOnlyValue = "Bearer test-only-not-a-real-credential"
	var presented atomic.Value
	ca, address := loopback(t, http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
		presented.Store(request.Header.Get("Authorization"))
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(appointmentBody))
	}))
	directory := t.TempDir()
	material := write(t, directory, "test-only-material", testOnlyValue+"\n")
	program, err := filepath.Abs(os.Args[0])
	if err != nil {
		t.Fatal(err)
	}
	document := strings.Replace(declaredHTTPSource, `"credential": null`,
		`"credential": {"store": "os-keychain", "address": "`+address+`", "header": "Authorization", "command": "`+program+`", "arguments": ["`+material+`"]}`, 1)
	source, snapshot := declaredHTTP(t, ca, address, document)
	completion := collect(t, source, window(t, declaredHTTPWindow), snapshot)
	if err := completion.Err(); err != nil {
		t.Fatalf("collection did not complete: %v", err)
	}
	if presented.Load() != testOnlyValue {
		t.Fatalf("the endpoint received %q", presented.Load())
	}
	// Nothing readmit retained holds the value it presented.
	retained, err := os.ReadFile(filepath.Join(snapshot, "read-0000", "read.json"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(retained), "test-only-not-a-real-credential") {
		t.Fatal("a retained record holds the credential it presented")
	}
	encoded, err := observewindow.EncodeCompletion(completion)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(encoded), "test-only-not-a-real-credential") {
		t.Fatal("a completion record holds the credential it presented")
	}
}

func TestACredentialScopedToAnotherEndpointIsRefused(t *testing.T) {
	ca, address := loopback(t, answer(appointmentBody, nil))
	program, err := filepath.Abs(os.Args[0])
	if err != nil {
		t.Fatal(err)
	}
	document := strings.Replace(declaredHTTPSource, `"credential": null`,
		`"credential": {"store": "os-keychain", "address": "elsewhere.example.invalid:8443", "header": "Authorization", "command": "`+program+`", "arguments": ["/dev/null"]}`, 1)
	source, snapshot := declaredHTTP(t, ca, address, document)
	_, err = observesource.Collect(context.Background(), source, window(t, declaredHTTPWindow), observesource.Options{Snapshot: snapshot})
	if err == nil {
		t.Fatal("a credential scoped to another endpoint was presented")
	}
}

func TestACredentialThatCannotBeReadIsAFailedReadRatherThanAnEmptyOne(t *testing.T) {
	ca, address := loopback(t, answer(appointmentBody, nil))
	document := strings.Replace(declaredHTTPSource, `"credential": null`,
		`"credential": {"store": "customer-managed", "address": "`+address+`", "header": "Authorization", "command": "`+filepath.Join(t.TempDir(), "absent-provider")+`", "arguments": []}`, 1)
	source, snapshot := declaredHTTP(t, ca, address, document)
	completion := collect(t, source, window(t, declaredHTTPWindow), snapshot)
	if completion.Status != observewindow.Failed {
		t.Fatalf("status = %q, want failed", completion.Status)
	}
	if err := completion.AbsenceEvidence(); err == nil {
		t.Fatal("an unreadable credential supported an absence assertion")
	}
}
