import {afterEach,beforeEach,expect,test} from "vitest";
import {screen,within,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {Journey,enter,press} from "../testkit/journey";
import {page,details,sidebar} from "../testkit/navigation";
import {licensedProject,importExport,EXPORTED_BOOKING} from "./steps";
let journey:Journey;beforeEach(()=>{journey=Journey.create();});afterEach(async()=>{await journey.dispose();});

async function openSourceContext(user: ReturnType<typeof userEvent.setup>) {
 const direct=page().queryByRole("button",{name:"Source context"});
 if(direct){await waitFor(()=>expect(direct.hasAttribute("disabled")).toBe(false));await press(user,direct);return;}
 await press(user,page().getByRole("button",{name:"More case actions"}));
 const action=await waitFor(()=>{const offered=screen.getByRole("menuitem",{name:"Source context"});expect(offered.hasAttribute("disabled")).toBe(false);return offered;});await press(user,action);
}
test("partial source corrections and specification association survive Back and actual restart until acknowledged discard or save",async()=>{
 const user=userEvent.setup();journey.writeFile("exports/owned.hl7",EXPORTED_BOOKING);const doc=journey.writeFile("exports/authored.md","Explicit authored partner documentation.");await licensedProject(journey,user);await importExport(user,journey,"exports/owned.hl7","Owned draft source");const original=journey.digest("exports/owned.hl7");
 await openSourceContext(user);await press(user,await screen.findByRole("button",{name:"Correct source context"}));let correction=within(await screen.findByRole("dialog",{name:"Correct source context"}));await enter(user,correction.getByLabelText("Source"),"Authored partial source");await press(user,correction.getByRole("button",{name:"Cancel"}));await press(user,await screen.findByRole("button",{name:"Close capture source context"}));
 const messages=await screen.findByRole("table",{name:"Messages"});await waitFor(()=>expect(messages.querySelectorAll("tbody tr[data-row-id]")).toHaveLength(1));await press(user,messages.querySelector<HTMLElement>("tbody tr[data-row-id]")!);await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Interface requirements"}));const requirements=within(await screen.findByRole("region",{name:"Interface requirements"}));await press(user,requirements.getByRole("button",{name:"Add specification"}));let association=within(await screen.findByRole("dialog",{name:"Interface specification"}));await enter(user,association.getByLabelText("Name"),"Unfinished authored association");await journey.chooseFiles([doc],"Add interface specification document");await press(user,association.getByRole("button",{name:"Add document"}));await association.findByText(/authored.md/,{selector:"span"});expect((association.getByRole("button",{name:"Save specification"}) as HTMLButtonElement).disabled).toBe(true);await press(user,association.getByRole("button",{name:"Cancel"}));await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Interface specification"})).toBeNull());await press(user,requirements.getByRole("button",{name:"Return to selected message"}));
 await journey.close();await journey.launch();await screen.findByRole("region",{name:"Details"});await details().findByRole("button",{name:"More message actions"});await openSourceContext(user);correction=within(await screen.findByRole("dialog",{name:"Correct source context"}));expect(await correction.findByDisplayValue("Authored partial source")).toBeTruthy();expect(correction.getByLabelText("Channel")).toHaveProperty("value","");await press(user,correction.getByRole("button",{name:"Discard draft"}));await screen.findByRole("dialog",{name:"Capture source context"});await press(user,await screen.findByRole("button",{name:"Close capture source context"}));
 await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Interface requirements"}));association=within(await screen.findByRole("dialog",{name:"Interface specification"}));expect(await association.findByDisplayValue("Unfinished authored association")).toBeTruthy();expect(association.getByText(/authored.md/,{selector:"span"})).toBeTruthy();expect((association.getByRole("button",{name:"Save specification"}) as HTMLButtonElement).disabled).toBe(true);await press(user,association.getByRole("button",{name:"Discard draft"}));await press(user,screen.getByRole("button",{name:"Return to selected message"}));
 const projects=sidebar().queryByRole("button",{name:"Projects"});if(projects)await press(user,projects);else{await press(user,sidebar().getByRole("button",{name:/^Source:/}));await press(user,await screen.findByRole("menuitem",{name:"Projects"}));}await journey.settled();const ids=new Set(journey.callsTo("SaveEditorDraft").flatMap(call=>(call.result as {drafts?:import("../bindings").EditorDraft[]})?.drafts??[]).filter(draft=>["capture-source-context","interface-association"].includes(draft.kind)).map(draft=>draft.id));const owned=journey.callsTo("DiscardEditorDraft").filter(call=>ids.has(String(call.args[0])));expect(owned).toHaveLength(2);expect(journey.callsTo("SaveInterfaceSpec")).toHaveLength(0);expect(journey.callsTo("SaveCaptureContext")).toHaveLength(0);expect(journey.callsTo("ExecuteReviewedAction")).toHaveLength(0);expect(journey.digest("exports/owned.hl7")).toBe(original);
});
