import { readFileSync } from "node:fs";
import { afterEach,beforeEach,expect,test } from "vitest";
import { screen,within,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { enter,Journey,press } from "../testkit/journey";
import { details,page,sidebar,goTo } from "../testkit/navigation";
import { licensedProject } from "./steps";
let journey:Journey;beforeEach(()=>{journey=Journey.create();});afterEach(async()=>{await journey.dispose();});
function fixture(name:string){const module=decodeURIComponent(new URL(import.meta.url).pathname);return readFileSync(module.slice(0,module.lastIndexOf("/"))+"/../../../../testdata/casegen/"+name,"utf8");}

test("field requirements associate documents and exact profile revisions edit evaluate and return without rewriting evidence",async()=>{
 const user=userEvent.setup();const pack=journey.writeFile("exports/pack.json",fixture("owned/pack.json"));const profile=journey.writeFile("exports/profile.json",fixture("owned/profile-siu.json"));
 const input=journey.writeFile("exports/requirements.mllp","\x0bMSH|^~\\&|READMIT|TEST|RECV|LAB|20260101||SIU^S12|owned-1|P|2.5.1\rSCH|OWNED\r\x1c\r");const sourceSHA=journey.digest("exports/requirements.mllp");const doc=journey.writeFile("exports/spec.md","Owned partner narrative. <script>window.__specInjected=true</script>");
 await licensedProject(journey,user);await goTo(user,"Tests");await goTo(user,"Library");await press(user,screen.getByRole("tab",{name:"Profiles"}));await journey.settled();
 await press(user,screen.getByRole("button",{name:"More library actions"}));await press(user,screen.getByRole("menuitem",{name:"Metadata packs"}));const packs=within(await screen.findByRole("dialog",{name:"Metadata packs"}));await journey.chooseFiles([pack],"Import metadata pack");await press(user,packs.getByRole("button",{name:"Import metadata pack"}));await screen.findByRole("button",{name:"Save"});await journey.settled();await press(user,screen.getByRole("button",{name:"Save"}));await journey.settled();expect(journey.callsTo("SaveItem").at(-1)?.result).toMatchObject({state:"completed",outcome:"saved"});await press(user,screen.getByRole("button",{name:"Back to library"}));
 await journey.chooseFiles([profile],"Import profile");await press(user,screen.getAllByRole("button",{name:"Import profile"})[0]!);await screen.findByRole("button",{name:"Save"});await journey.settled();await press(user,screen.getByRole("button",{name:"Save"}));await journey.settled();expect(journey.callsTo("SaveItem").at(-1)?.result).toMatchObject({state:"completed",outcome:"saved"});
 await press(user,sidebar().getByRole("button",{name:"Messages"}));await journey.chooseFiles([input],"Open HL7 file");await press(user,page().getByRole("button",{name:"Open file"}));const loose=await screen.findByRole("table",{name:"Messages in this file"});await press(user,loose.querySelector<HTMLElement>('[data-row-id="0"]')!);await press(user,page().getByRole("button",{name:"Retain capture"}));
 const importing=within(await screen.findByRole("dialog",{name:"Import"}));await enter(user,importing.getByLabelText("Case"),"Requirement source");await journey.settled();await press(user,importing.getByRole("button",{name:"Next"}));await importing.findByRole("table",{name:"Preview"});await press(user,importing.getByRole("button",{name:/^Import$/}));await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Import"})).toBeNull());await journey.settled();
 const messages=screen.getByRole("table",{name:"Messages"});await press(user,messages.querySelector<HTMLElement>('[data-row-id="s0001-e000001"]')!);await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Go to field…"}));const go=within(await screen.findByRole("dialog",{name:"Go to field"}));await enter(user,go.getByLabelText("Field path"),"MSH-10");await press(user,go.getByRole("button",{name:"Go"}));await journey.settled();
 await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Interface requirements"}));let spec=within(await screen.findByRole("region",{name:"Interface requirements"}));await journey.settled();await press(user,spec.getByRole("button",{name:"Add specification"}));
 const dialog=within(await screen.findByRole("dialog",{name:"Interface specification"}));await enter(user,dialog.getByLabelText("Name"),"Owned interface specification");await user.selectOptions(dialog.getByLabelText("Local profile revision"),await dialog.findByRole("option",{name:/owned.*siu.*1/i}));await journey.chooseFiles([doc],"Add interface specification document");await press(user,dialog.getByRole("button",{name:"Add document"}));await journey.settled();await press(user,dialog.getByRole("button",{name:"Save specification"}));await journey.settled();
 expect(await spec.findByText(/catalog revision 1/)).toBeTruthy();await press(user,spec.getByText("spec.md",{selector:"summary"}));expect(spec.getByText(/Owned partner narrative/)).toBeTruthy();expect(document.querySelector("script")?.textContent||"").not.toContain("__specInjected");
 const editor=within(await spec.findByRole("region",{name:"Supported profile editor"}));await press(user,editor.getByRole("button",{name:"Edit"}));await journey.settled();await press(user,editor.getByRole("button",{name:"Add to profile"}));await press(user,screen.getByRole("menuitem",{name:"Edit JSON"}));const json=within(await screen.findByRole("dialog",{name:"Edit JSON"}));await journey.settled();const text=json.getByLabelText<HTMLTextAreaElement>("Document");expect(text.value).toMatch(/"usage"\s*:\s*"R"/);const revised=text.value.replace(/"usage"\s*:\s*"R"/,'"usage": "O"');await user.clear(text);await user.click(text);await user.paste(revised);await press(user,json.getByRole("button",{name:"Apply"}));await journey.settled();await press(user,editor.getByRole("button",{name:"Save"}));await journey.settled();
 expect(await spec.findByText(/profile edit created revision 2/)).toBeTruthy();expect(spec.getByText(/catalog revision 1/)).toBeTruthy();await press(user,editor.getByRole("button",{name:"More profile actions"}));await press(user,screen.getByRole("menuitem",{name:"Evaluate a case…"}));const evaluation=within(await screen.findByRole("dialog",{name:"Evaluate a case"}));await journey.settled();expect((evaluation.getByLabelText("Case") as HTMLSelectElement).value).not.toBe("");await press(user,evaluation.getByRole("button",{name:"Evaluate"}));await journey.settled();expect(journey.callsTo("EvaluateProfile").at(-1)?.result).toMatchObject({state:"completed"});await press(user,evaluation.getByRole("button",{name:/Close evaluate a case/i}));
 await press(user,spec.getByRole("button",{name:"Return to selected message"}));await journey.settled();expect(journey.callsTo("InspectOccurrence").at(-1)?.args[0]).toMatchObject({occurrence:"s0001-e000001",path:"MSH[1]-10",reveal:false});expect(journey.digest("exports/requirements.mllp")).toBe(sourceSHA);
 await journey.close();await journey.launch();await journey.settled();expect(journey.digest("exports/requirements.mllp")).toBe(sourceSHA);
 await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Interface requirements"}));spec=within(await screen.findByRole("region",{name:"Interface requirements"}));await journey.settled();expect(await spec.findByText(/catalog revision 1/)).toBeTruthy();await press(user,spec.getByText("spec.md",{selector:"summary"}));expect(spec.getByText(/Owned partner narrative/)).toBeTruthy();expect(journey.callsTo("ReadInterfaceRequirements").at(-1)?.result).toMatchObject({state:"completed",profile:{revision:"1"}});
});
