import { afterEach, beforeEach, expect, test } from "vitest";
import { screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { enter, Journey, press } from "../testkit/journey";
import { page } from "../testkit/navigation";
import { EXPORTED_BOOKING, EXPORTED_RESCHEDULE, importExport, licensedProject } from "./steps";
let journey:Journey;
beforeEach(()=>{journey=Journey.create();});
afterEach(async()=>{await journey.dispose();});

test("an ordered named draft is discoverable before target setup, survives restart and failed publication, then publishes through existing validation",async()=>{
 const user=userEvent.setup();
 journey.writeFile("exports/feed.hl7",EXPORTED_BOOKING+EXPORTED_RESCHEDULE);
 await licensedProject(journey,user);await importExport(user,journey,"exports/feed.hl7","Ordered source");
 const table=await screen.findByRole("table",{name:"Messages"});
 await waitFor(()=>expect(table.querySelectorAll('tbody tr[data-row-id]')).toHaveLength(2));
 await user.click(table.querySelector<HTMLInputElement>('tbody tr[data-row-id]:nth-child(2) input[type="checkbox"]')!);
 await user.click(table.querySelector<HTMLInputElement>('tbody tr[data-row-id]:nth-child(1) input[type="checkbox"]')!);
 expect([...table.querySelectorAll<HTMLInputElement>('tbody tr[data-row-id] input[type="checkbox"]')].every(box=>box.checked)).toBe(true);
 const ordered=[...table.querySelectorAll<HTMLElement>('tbody tr[data-row-id]')].map(row=>row.dataset.rowId!).reverse();
 const messages=within(screen.getByRole("region",{name:"Messages"}));
 await press(user,messages.getByRole("button",{name:"Filter messages"}));
 const filter=within(await screen.findByRole("dialog",{name:"Filter"}));
 await user.selectOptions(filter.getByLabelText("Field of rule 1"),"field");
 await waitFor(()=>expect(within(filter.getByLabelText("Message field of rule 1")).getByRole("option",{name:"MSH-9 · Message Type"})).toBeTruthy());
 await user.selectOptions(filter.getByLabelText("Message field of rule 1"),"MSH-9 · Message Type");
 await user.selectOptions(filter.getByLabelText("Operator of rule 1"),"contains");await enter(user,filter.getByLabelText("Value of rule 1"),"S99");
 await press(user,filter.getByRole("button",{name:"Apply"}));
 await waitFor(()=>expect(screen.queryByRole('table',{name:'Messages'})).toBeNull());
 await press(user,within(screen.getByRole("group",{name:"Selected messages"})).getByRole("button",{name:"Create test"}));
 await enter(user,await page().findByRole("textbox",{name:"Name"}),"Draft before configuration");
 await press(user,page().getByRole("button",{name:"Save draft"}));
 const drafts=within(await page().findByRole("table",{name:"Test drafts"}));
 await drafts.findByText("Draft before configuration");expect(drafts.getByText("Draft")).toBeTruthy();
 const retained=journey.callsTo("SaveEditorDraft").at(-1)?.args[0] as {content:{draft:{test:{messages:string[];target:string}}}};
 expect(retained.content.draft.test.messages).toEqual(ordered);expect(retained.content.draft.test.target).toBe("");
 expect(journey.callsTo("SaveItem").filter(call=>(call.args[0] as {kind:string}).kind==="test")).toHaveLength(0);
 await journey.settled();await journey.close();await journey.launch();
 await page().findByRole("table",{name:"Test drafts"});
 await press(user,screen.getByRole("button",{name:"Resume Draft before configuration"}));
 expect(await page().findByRole("textbox",{name:"Name"})).toHaveProperty("value","Draft before configuration");
 await press(user,page().getByRole("button",{name:"Next"}));await press(user,page().getByRole("button",{name:"Review"}));
 await page().findByLabelText("Setup",{selector:"dl"});
 await press(user,page().getByRole("button",{name:"Create test"}));
 await waitFor(()=>expect(journey.callsTo("SaveItem").at(-1)?.settled).toBe(true));
 expect(journey.callsTo("SaveItem").at(-1)?.result).toMatchObject({outcome:"invalid"});
 expect(page().getByRole("textbox",{name:"Name"})).toHaveProperty("value","Draft before configuration");
 await press(user,page().getByRole("button",{name:"Add environment"}));
 const target=within(await screen.findByRole("dialog",{name:"Add environment"}));
 await enter(user,await target.findByLabelText("Name"),"Explicit draft target");await enter(user,target.getByLabelText("Host"),"127.0.0.1");await enter(user,target.getByLabelText("Port"),"65530");
 await user.selectOptions(target.getByLabelText("Classification"),"nonproduction");await press(user,target.getByRole("radio",{name:"TCP/MLLP"}));await press(user,target.getByRole("button",{name:"Save"}));
 await page().findByRole("textbox",{name:"Name"});
 await waitFor(()=>expect(within(page().getByRole("combobox",{name:"Environment"})).getByRole("option",{name:"Explicit draft target"})).toBeTruthy());
 await user.selectOptions(page().getByRole("combobox",{name:"Environment"}),"Explicit draft target");
 await press(user,page().getByRole("radio",{name:"Acknowledgements"}));
 await user.selectOptions(page().getByRole("combobox",{name:"Reset"}),"manual");
 const reset=within(await screen.findByRole("dialog",{name:"Reset instructions"}));await enter(user,reset.getByRole("textbox"),"Operator prepares the owned receiver before execution.");await press(user,reset.getByRole("button",{name:"Apply"}));
 await press(user,page().getByRole("button",{name:"Next"}));await press(user,page().getByRole("button",{name:"Add check"}));await press(user,screen.getByRole("menuitem",{name:"ACK field"}));
 const check=within(await screen.findByRole("dialog",{name:"Add ack field check"}));await user.selectOptions(check.getByLabelText("Message"),ordered[0]!);await user.selectOptions(check.getByLabelText("Field"),"MSA-1");await enter(user,check.getByLabelText("Expected value"),"AA");await press(user,check.getByRole("button",{name:"Apply"}));
 await press(user,page().getByRole("button",{name:"Review"}));await page().findByLabelText("Setup",{selector:"dl"});await press(user,page().getByRole("button",{name:"Create test"}));
 await waitFor(()=>expect(journey.callsTo("SaveItem").at(-1)?.result).toMatchObject({outcome:"saved"}));
 const saved=journey.callsTo("SaveItem").at(-1)?.args[0] as {draft:{test:{messages:string[];expectations:{message:string}[]}}};expect(saved.draft.test.messages).toEqual(ordered);expect(saved.draft.test.expectations[0]?.message).toBe(ordered[0]);
 expect(journey.callsTo("CheckEnvironment")).toHaveLength(0);expect(journey.callsTo("ExecuteReviewedAction")).toHaveLength(0);
});
