import {afterEach,beforeEach,expect,test} from "vitest";
import {screen,within} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {Journey,press} from "../testkit/journey";
import {sidebar} from "../testkit/navigation";
let journey:Journey;
beforeEach(()=>{journey=Journey.create();});
afterEach(async()=>{await journey.dispose();});
test("parser values start visible and PHI masking covers patient values across navigation without changing evidence",async()=>{
 const user=userEvent.setup();
 const source=journey.writeFile("source.mllp","\x0bMSH|^~\\&|SENDER|FAC|RECEIVER|FAC|20260101||ADT^A01|control|P|2.5.1\rPID|1||OWNED_ID||OWNED_NAME^GIVEN~SECOND^NAME||19800101|F\r\x1c\r");
 const identity=journey.digest("source.mllp");
 await journey.launch();await press(user,sidebar().getByRole("button",{name:"Messages"}));
 await journey.chooseFiles([source],"Open HL7 file");await press(user,screen.getByRole("button",{name:"Open file"}));
 let reader=within(await screen.findByRole("region",{name:"Message details"}));
 const original=()=>reader.getByRole("region",{name:"Original message"});
 expect(original().textContent).toContain("OWNED_NAME");
 expect(reader.queryByRole("button",{name:"Show values"})).toBeNull();
 await press(user,reader.getByRole("button",{name:"Enable PHI masking"}));
 await reader.findByRole("button",{name:"Disable PHI masking"});
 expect(original().textContent).not.toContain("OWNED_NAME");expect(original().textContent).toContain("**********^*****~******^****");
 expect(original().textContent).toContain("SENDER");
 await press(user,reader.getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Go to field…"}));
 const go=within(await screen.findByRole("dialog",{name:"Go to field"}));await user.type(go.getByLabelText("Field path"),"PID-5[2].1");await press(user,go.getByRole("button",{name:"Go"}));
 await journey.settled();
 const masked=journey.callsTo("InspectFileMessage").at(-1)!;
 expect(masked.args[0]).toMatchObject({reveal:true,mask_phi:true});
 expect(JSON.stringify(masked.result)).not.toContain("SECOND");
 expect(reader.getByRole("button",{name:"Disable PHI masking"}).getAttribute("aria-pressed")).toBe("true");
 await press(user,reader.getByRole("button",{name:"Disable PHI masking"}));await reader.findByRole("button",{name:"Enable PHI masking"});
 expect(original().textContent).toContain("OWNED_NAME");
 await journey.close();await journey.launch();reader=within(await screen.findByRole("region",{name:"Message details"}));
 expect(original().textContent).toContain("OWNED_NAME");
 expect(journey.digest("source.mllp")).toBe(identity);
});
