import { readFileSync } from "node:fs";
import { beforeEach,afterEach,expect,test } from "vitest";
import { screen,within,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { enter,Journey,press } from "../testkit/journey";
import { page,details,goTo } from "../testkit/navigation";
import { licensedProject } from "./steps";
let journey:Journey;beforeEach(()=>{journey=Journey.create();});afterEach(async()=>{await journey.dispose();});

test("author import revise export and reopen field maps without rewriting messages or inventing unmapped destinations",async()=>{
 const user=userEvent.setup();const input=journey.writeFile("exports/map-source.mllp","\x0bMSH|^~\\&|READMIT|TEST|RECV|LAB|20260101||SIU^S12|owned-map-1|P|2.5.1\rSCH|OWNED\r\x1c\r");const sha=journey.digest("exports/map-source.mllp");
 await licensedProject(journey,user);await journey.chooseFiles([input],"Open HL7 file");await press(user,page().getByRole("button",{name:"Open file"}));const loose=await screen.findByRole("table",{name:"Messages in this file"});await press(user,loose.querySelector<HTMLElement>('[data-row-id="0"]')!);await press(user,page().getByRole("button",{name:"Retain capture"}));
 const importing=within(await screen.findByRole("dialog",{name:"Import"}));await enter(user,importing.getByLabelText("Case"),"Map source");await journey.settled();await press(user,importing.getByRole("button",{name:"Next"}));await importing.findByRole("table",{name:"Preview"});await press(user,importing.getByRole("button",{name:/^Import$/}));await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Import"})).toBeNull());await journey.settled();
 await press(user,screen.getByRole("table",{name:"Messages"}).querySelector<HTMLElement>('[data-row-id="s0001-e000001"]')!);await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Go to field…"}));const go=within(await screen.findByRole("dialog",{name:"Go to field"}));await enter(user,go.getByLabelText("Field path"),"MSH-3");await press(user,go.getByRole("button",{name:"Go"}));await journey.settled();
 await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Value maps"}));let maps=within(await screen.findByRole("region",{name:"Field value maps"}));await journey.settled();await press(user,maps.getByRole("button",{name:"Create value map"}));await enter(user,maps.getByLabelText("Name"),"Owned sending application map");await enter(user,maps.getByLabelText("Source field meaning"),"Declared sending application");await enter(user,maps.getByLabelText("Destination field meaning"),"Recorded local application name");await enter(user,maps.getByLabelText("Map provenance"),"Owned owner declaration");
 await press(user,maps.getByRole("button",{name:"Add entry"}));let entry=within(await screen.findByRole("form",{name:"Value map entry"}));for(const [label,value]of [["Source value","READMIT"],["Destination value","LOCAL"],["Source value meaning","Owned test sender"],["Destination value meaning","Owned test receiver"],["Entry provenance","Owned mapping note"]])await enter(user,entry.getByLabelText(label!),value!);await press(user,entry.getByRole("button",{name:"Save entry"}));await press(user,maps.getByRole("button",{name:"Save map revision"}));await journey.settled();expect(journey.callsTo("SaveValueMap").at(-1)?.result).toMatchObject({state:"completed",ref:{revision:"1"}});expect(await maps.findByText("hidden · present")).toBeTruthy();expect(journey.callsTo("InspectValueMap").at(-1)?.args[0]).toMatchObject({reveal:false,occurrence:"s0001-e000001",selector:"MSH[1]-3[1]"});
 await press(user,maps.getByRole("button",{name:"Show contextual mapping for this source"}));await journey.settled();expect(await maps.findByText(/Recorded destination: LOCAL/)).toBeTruthy();
 const csv=journey.path("exports","owned-map.csv");await journey.nameNewFolder(csv,"Export value map CSV");await press(user,maps.getByRole("button",{name:"Export CSV"}));await journey.settled();const exported=readFileSync(csv,"utf8");expect(exported).toContain("source_selector");expect(exported).toContain("READMIT,LOCAL");
 await press(user,maps.getByRole("button",{name:"Edit map"}));const rows=maps.getByRole("table",{name:"Recorded mapping entries"});await user.dblClick(rows.querySelector<HTMLElement>('[data-row-id="READMIT"]')!);entry=within(await screen.findByRole("form",{name:"Value map entry"}));await enter(user,entry.getByLabelText("Source value"),"OTHER");await enter(user,entry.getByLabelText("Destination value"),"REVISED");await press(user,entry.getByRole("button",{name:"Save entry"}));await press(user,maps.getByRole("button",{name:"Save map revision"}));await journey.settled();expect(journey.callsTo("SaveValueMap").at(-1)?.result).toMatchObject({state:"completed",ref:{revision:"2"}});await press(user,maps.getByRole("button",{name:"Show contextual mapping for this source"}));await journey.settled();expect(await maps.findByText("unmapped · present")).toBeTruthy();expect(maps.queryByText(/Recorded destination:/)).toBeNull();
 await journey.chooseFiles([csv],"Import value map CSV");await press(user,maps.getByRole("button",{name:"Import CSV"}));await journey.settled();expect(maps.getByText(/CSV validated into an unsaved draft/)).toBeTruthy();await press(user,maps.getByRole("button",{name:"Save map revision"}));await journey.settled();expect(journey.callsTo("SaveValueMap").at(-1)?.result).toMatchObject({state:"completed",ref:{revision:"3"}});
 await press(user,maps.getByRole("button",{name:"Return to selected message"}));await journey.settled();expect(journey.callsTo("InspectOccurrence").at(-1)?.args[0]).toMatchObject({occurrence:"s0001-e000001",path:"MSH[1]-3",reveal:true});expect(journey.digest("exports/map-source.mllp")).toBe(sha);
 await journey.close();await journey.launch();await journey.settled();await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Value maps"}));maps=within(await screen.findByRole("region",{name:"Field value maps"}));await journey.settled();expect(await maps.findByText("Saved revision 3 · 2.5.1 · destination MSH[1]-3[1]")).toBeTruthy();expect(journey.callsTo("InspectValueMap").at(-1)?.result).toMatchObject({state:"completed",mapping:"hidden",revealed:false});expect(journey.digest("exports/map-source.mllp")).toBe(sha);
 await press(user,maps.getByRole("button",{name:"Edit map"}));await enter(user,maps.getByLabelText("Name"),"Unfinished owned map");await press(user,maps.getByRole("button",{name:"Add entry"}));entry=within(await screen.findByRole("form",{name:"Value map entry"}));await enter(user,entry.getByLabelText("Source value"),"PARTIAL AUTHORED SOURCE");await journey.settled();expect(journey.callsTo("SaveEditorDraft").at(-1)?.result).toMatchObject({state:"completed"});await press(user,entry.getByRole("button",{name:"Cancel"}));await journey.settled();
 await goTo(user,"Tests");await journey.settled();await user.keyboard("{Control>}k{/Control}");let commands=within(await screen.findByRole("dialog",{name:"Commands"}));await enter(user,commands.getByLabelText("Search commands"),"Projects");await press(user,commands.getByRole("option",{name:"Projects"}));await press(user,within(await screen.findByRole("group",{name:"Drafts to restore"})).getByRole("button",{name:"Review"}));let recovery=within(await screen.findByRole("dialog",{name:"Drafts to restore"}));await press(user,recovery.getByRole("button",{name:"Value map · Unfinished owned map"}));await journey.settled();maps=within(await screen.findByRole("region",{name:"Field value maps"}));expect((await maps.findByLabelText("Name") as HTMLInputElement).value).toBe("Unfinished owned map");
 await press(user,maps.getByRole("button",{name:"Add entry"}));entry=within(await screen.findByRole("form",{name:"Value map entry"}));await enter(user,entry.getByLabelText("Source value"),"PARTIAL AUTHORED SOURCE");await journey.settled();await journey.close();await journey.launch();await journey.settled();await press(user,details().getByRole("button",{name:"More message actions"}));await press(user,screen.getByRole("menuitem",{name:"Value maps"}));maps=within(await screen.findByRole("region",{name:"Field value maps"}));entry=within(await screen.findByRole("form",{name:"Value map entry"}));expect((entry.getByLabelText("Source value") as HTMLInputElement).value).toBe("PARTIAL AUTHORED SOURCE");await journey.settled();expect(journey.callsTo("ReadValueMapDraft").at(-1)?.result).toMatchObject({state:"completed"});
 const sourceRequest=journey.callsTo("InspectOccurrence").at(-1)?.args[0] as {workspace:string;case:string};await journey.close();const manifest=[sourceRequest.workspace,sourceRequest.case,"manifest.json"].join("/").slice(journey.root.length+1);journey.changeFile(manifest,journey.readFile(manifest).replace("readmit-case/v1","readmit-case/v999"));await journey.launch();await journey.settled();await user.keyboard("{Control>}k{/Control}");commands=within(await screen.findByRole("dialog",{name:"Commands"}));await enter(user,commands.getByLabelText("Search commands"),"Projects");await press(user,commands.getByRole("option",{name:"Projects"}));await press(user,within(await screen.findByRole("group",{name:"Drafts to restore"})).getByRole("button",{name:"Review"}));recovery=within(await screen.findByRole("dialog",{name:"Drafts to restore"}));await press(user,recovery.getByRole("button",{name:"Value map · Unfinished owned map"}));const unavailable=within(await screen.findByRole("dialog",{name:"Retained value map draft"}));expect(unavailable.getByText(/original source changed|original source is missing/i)).toBeTruthy();expect(unavailable.getByText(/PARTIAL AUTHORED SOURCE/)).toBeTruthy();expect(journey.digest("exports/map-source.mllp")).toBe(sha);
});
