// Package reportshare prepares one report version for sharing (#560): the
// inventory of what a share holds, the redaction of every value it restates
// under a named disclosure template (readmit-redact-policy/v1) and the exact
// output bytes, generated whole so a preview is the output itself.
//
// Nothing here is a claim the caller did not earn. A value no rule handled
// keeps its original text and is Unresolved; unmapped free text, attachments
// and original evidence are never quietly dropped or called redacted; a
// residual scan of the generated bytes for every original value the
// derivation replaced turns a hit back into an unresolved issue. Surrogates
// and date shifts come from a customer-local key, so the report's values
// agree with the messages they came from and the same draft generates the
// same bytes again.
package reportshare

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"fmt"
	"slices"
	"strings"
	"unicode/utf8"

	"github.com/bharm16/readmit/internal/bundle"
	"github.com/bharm16/readmit/internal/exportreview"
	"github.com/bharm16/readmit/internal/hl7"
	"github.com/bharm16/readmit/internal/observation"
	"github.com/bharm16/readmit/internal/redact"
	"github.com/bharm16/readmit/internal/report"
	"github.com/bharm16/readmit/internal/testrunner"
)

// Contents are what a share holds beside its report.
type Contents struct {
	Messages    bool
	Attachments bool
	Original    bool
	// Removed are the item keys taken out of this share only.
	Removed []string
}

// Attachment is one file attached to the report's case, as the project
// holds it. Unreadable says why its bytes could not be read.
type Attachment struct {
	Name       string
	Data       []byte
	Unreadable string
}

// ValueTreatment is a draft's own treatment of one restated value row that
// no template rule reaches.
type ValueTreatment struct {
	Row     string  `json:"row"`
	Remove  bool    `json:"remove,omitzero"`
	Replace *string `json:"replace,omitzero"`
}

// Overrides are one draft's treatments beyond its template. Fields replace
// the template's rule for the same selector or add one; Packet turns on
// packet policies; Title replaces the report title and Notes removes or
// replaces its notes; Values treat rows no rule reaches.
type Overrides struct {
	Fields []redact.FieldRule `json:"fields,omitzero"`
	Packet []string           `json:"packet,omitzero"`
	Title  *string            `json:"title,omitzero"`
	Notes  *ValueTreatment    `json:"notes,omitzero"`
	Values []ValueTreatment   `json:"values,omitzero"`
}

// Request is one share to prepare.
type Request struct {
	Packet      *report.RetainedPacket
	Authored    report.Authored
	Template    *redact.Policy
	Overrides   Overrides
	Key         []byte
	Contents    Contents
	Attachments []Attachment
	// Format is html, pdf, pdf-a4, markdown, json or junit.
	Format string
}

// Item is one thing the share holds, as the Contents step lists it.
type Item struct {
	Key      string `json:"key"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	Included bool   `json:"included"`
	// Removable is false for the report itself.
	Removable bool `json:"removable"`
	// Problem is why the item cannot be read.
	Problem string `json:"problem,omitzero"`
}

// Item types.
const (
	ReportType     = "report"
	NotesType      = "notes"
	MessageType    = "message"
	AttachmentType = "attachment"
	OriginalType   = "original"
)

// Row is one redaction row: a category and field, how many occurrences the
// share holds, the treatment and its result. Kind says which treatments its
// sheet offers.
type Row struct {
	Key         string `json:"key"`
	Kind        string `json:"kind"`
	Category    string `json:"category"`
	Field       string `json:"field"`
	Selector    string `json:"selector,omitzero"`
	Occurrences int    `json:"occurrences"`
	Treatment   string `json:"treatment"`
	Result      string `json:"result"`
	// Rule is the field rule in force for a field row.
	Rule *redact.FieldRule `json:"rule,omitzero"`
	// Examples are up to three original values of the row and what the
	// share holds instead. They are source values: shown only on request.
	Examples []redact.Example `json:"examples,omitzero"`
}

// Row kinds.
const (
	FieldRow      = "field"
	FreeTextRow   = "free-text"
	MetadataRow   = "metadata"
	ValueRow      = "value"
	AttachmentRow = "attachment"
	OriginalRow   = "original"
)

// Treatments and results.
const (
	TreatNone       = "none"
	TreatRemove     = "remove"
	TreatReplace    = "replace"
	TreatSurrogate  = "surrogate"
	TreatShift      = "shift"
	TreatKeep       = "keep"
	TreatRegenerate = "regenerate"

	Removed     = "removed"
	Replaced    = "replaced"
	Surrogated  = "surrogate"
	Shifted     = "shifted"
	Kept        = "kept"
	Regenerated = "regenerated"
	Unresolved  = "unresolved"
	Original    = "original"
)

// Issue is something the share cannot claim. Blocking issues stop every
// output; the others stop only a redacted share.
type Issue struct {
	Key      string `json:"key"`
	Text     string `json:"text"`
	Blocking bool   `json:"blocking,omitzero"`
}

// File is one generated output file, by its name inside the output.
type File struct {
	Name string
	Kind string
	Data []byte
}

// Share is one prepared share.
type Share struct {
	Items  []Item
	Rows   []Row
	Issues []Issue
	// Document is the report as shared.
	Document *report.Document
	// Files are the generated files, report first; original evidence is
	// written by its own exporter when Original is set.
	Files    []File
	Original bool
	// SourceValues says the output holds original values: unresolved rows,
	// attachments or original evidence.
	SourceValues bool
	// Redacted says a template was applied, nothing is unresolved and the
	// output holds no original values.
	Redacted bool
	// RunCheck says the template requires a derived re-execution of the
	// messages this share holds before it can be shared.
	RunCheck bool
	// Derived are the included messages as shared, by their occurrence.
	Derived map[string][]byte
}

// Folder reports whether the output is several files, written as one new
// folder, rather than the report file alone.
func (s *Share) Folder() bool { return len(s.Files) > 1 || s.Original }

var formatExtensions = map[string]string{"html": ".html", "pdf": ".pdf", "pdf-a4": ".pdf", "markdown": ".md", "json": ".json", "junit": ".xml"}

// Extension is the file extension of one report format, or empty.
func Extension(format string) string { return formatExtensions[format] }

// Build prepares the share a request describes.
func Build(ctx context.Context, request Request) (*Share, error) {
	extension := Extension(request.Format)
	if extension == "" {
		return nil, errors.New("a report is shared as HTML, PDF, Markdown, JSON or JUnit")
	}
	policy, err := EffectivePolicy(request.Template, request.Overrides)
	if err != nil {
		return nil, err
	}
	doc, err := request.Packet.Document(ctx, request.Authored)
	if err != nil {
		return nil, err
	}
	source, err := request.Packet.Case()
	if err != nil {
		return nil, errors.New("the report's retained case cannot be read")
	}
	b := &builder{request: request, policy: policy, removed: map[string]bool{}, rows: map[string]*Row{}, seen: map[string]bool{}, share: &Share{}}
	for _, key := range request.Contents.Removed {
		b.removed[key] = true
	}
	if policy != nil {
		if b.deriver, err = redact.NewDeriver(*policy, request.Key); err != nil {
			return nil, err
		}
	}
	b.inventory(doc)
	messages, err := b.messages(doc, source)
	if err != nil {
		return nil, err
	}
	shared := b.document(doc)
	b.share.Document = shared
	data, err := report.RenderDocument(shared, request.Format)
	if err != nil {
		return nil, err
	}
	b.share.Files = append(b.share.Files, File{Name: fileName(shared.Title) + extension, Kind: ReportType, Data: data})
	if len(messages) > 0 {
		b.share.Files = append(b.share.Files, File{Name: "Messages.hl7", Kind: MessageType, Data: messages})
	}
	b.attachments()
	b.original()
	b.residual()
	b.finish()
	return b.share, nil
}

// EffectivePolicy is the template with the draft's own rules and packet
// policies applied, or nil when neither names anything.
func EffectivePolicy(template *redact.Policy, overrides Overrides) (*redact.Policy, error) {
	if template == nil && len(overrides.Fields) == 0 && len(overrides.Packet) == 0 {
		return nil, nil
	}
	policy := redact.Policy{Schema: redact.PolicySchema, Fields: []redact.FieldRule{}, RemoveSegments: []string{}, PacketPolicies: []string{}, SpecBindings: []redact.LiteralBinding{}, RequiredFailures: []int{}}
	if template != nil {
		policy = *template
		policy.Fields = slices.Clone(template.Fields)
		policy.PacketPolicies = slices.Clone(template.PacketPolicies)
	}
	for _, rule := range overrides.Fields {
		if err := redact.ValidateFieldRule(rule); err != nil {
			return nil, err
		}
		selector, _ := hl7.ParseSelector(rule.Selector)
		rule.Selector = selector.String()
		at := slices.IndexFunc(policy.Fields, func(held redact.FieldRule) bool {
			other, err := hl7.ParseSelector(held.Selector)
			return err == nil && other.String() == selector.String()
		})
		if at >= 0 {
			policy.Fields[at] = rule
		} else {
			policy.Fields = append(policy.Fields, rule)
		}
	}
	for _, name := range overrides.Packet {
		if name != redact.Metadata {
			return nil, errors.New("a share turns on only metadata regeneration")
		}
		if !slices.Contains(policy.PacketPolicies, name) {
			policy.PacketPolicies = append(policy.PacketPolicies, name)
		}
	}
	return &policy, nil
}

type builder struct {
	request Request
	policy  *redact.Policy
	deriver *redact.Deriver
	removed map[string]bool
	rows    map[string]*Row
	seen    map[string]bool
	order   []string
	share   *Share
	// terms are original values the share replaced, beyond the deriver's.
	terms [][]byte
}

func (b *builder) has(packet string) bool {
	return b.policy != nil && slices.Contains(b.policy.PacketPolicies, packet)
}

func (b *builder) item(item Item) {
	if item.Removable {
		item.Included = !b.removed[item.Key]
	} else {
		item.Included = true
	}
	b.share.Items = append(b.share.Items, item)
}

// row counts one located occurrence in a row, once however many findings
// name it, keeping the first treatment and result a row is given unless a
// later occurrence is unresolved.
func (b *builder) example(key, original, shared string) {
	held := b.rows[key]
	example := redact.Example{Original: original, Derived: shared}
	if held != nil && len(held.Examples) < 3 && !slices.Contains(held.Examples, example) {
		held.Examples = append(held.Examples, example)
	}
}

func (b *builder) row(template Row, location string) {
	held := b.rows[template.Key]
	if held == nil {
		copied := template
		copied.Occurrences = 0
		held = &copied
		b.rows[template.Key] = held
		b.order = append(b.order, template.Key)
	}
	if !b.seen[template.Key+"\x00"+location] {
		b.seen[template.Key+"\x00"+location] = true
		held.Occurrences++
	}
	if template.Result == Unresolved {
		held.Result = Unresolved
	}
}

func (b *builder) inventory(doc *report.Document) {
	b.item(Item{Key: "report", Name: doc.Title, Type: ReportType})
	if doc.Notes != nil {
		b.item(Item{Key: "notes", Name: "Notes", Type: NotesType, Removable: true})
	}
}

// messages lists the messages the current run sent and, when the share
// holds them, derives each one; it returns the derived messages as one
// file's bytes. Every message is derived even when not included, so values
// the report restates from it derive the same way.
func (b *builder) messages(doc *report.Document, source *bundle.Bundle) ([]byte, error) {
	var out bytes.Buffer
	for index, message := range doc.Messages {
		event := slices.IndexFunc(source.Events, func(e bundle.Event) bool { return e.ID == message.Source })
		key := "message:" + message.Source
		name := fmt.Sprintf("Message %d", index+1)
		if message.Code != "" {
			name += " · " + strings.Trim(message.Code+"^"+message.Trigger, "^")
		}
		if b.request.Contents.Messages {
			b.item(Item{Key: key, Name: name, Type: MessageType, Removable: true})
		}
		if event < 0 {
			if b.request.Contents.Messages && !b.removed[key] {
				b.issue(Issue{Key: key, Text: name + " is not in the retained case", Blocking: true})
			}
			continue
		}
		raw, err := source.Raw(message.Source)
		if err != nil {
			return nil, errors.New("a message of the retained case cannot be read")
		}
		included := b.request.Contents.Messages && !b.removed[key]
		derived := raw
		if b.deriver != nil {
			var findings []exportreview.Finding
			derived, findings, err = b.deriver.Message(message.Source, raw, source.Events[event].Kind, source.Events[event].Terminator)
			if err != nil {
				return nil, err
			}
			if included {
				b.messageRows(findings)
			}
		} else if included {
			b.row(Row{Key: "messages", Kind: FieldRow, Category: "unassigned", Field: "Message fields", Treatment: TreatNone, Result: Unresolved}, message.Source)
		}
		if !included {
			continue
		}
		if b.share.Derived == nil {
			b.share.Derived = map[string][]byte{}
		}
		b.share.Derived[message.Source] = derived
		out.Write(derived)
		if !bytes.HasSuffix(derived, []byte("\r")) && !bytes.HasSuffix(derived, []byte("\n")) {
			out.WriteByte('\r')
		}
		out.WriteByte('\n')
	}
	if b.request.Contents.Messages && b.policy != nil && slices.Contains(b.policy.PacketPolicies, redact.Rerun) && out.Len() > 0 {
		b.share.RunCheck = true
	}
	return out.Bytes(), nil
}

// messageRows turns one message's located findings into rows: a handled
// named field under its rule, and everything else unresolved under the
// category the finding names.
func (b *builder) messageRows(findings []exportreview.Finding) {
	for _, finding := range findings {
		field, selector := findingField(finding.Location)
		row := Row{Kind: FieldRow, Category: finding.Class, Field: field, Selector: selector}
		switch {
		case finding.Reason == "segment-removed":
			row.Key, row.Treatment, row.Result = "segment:"+field, TreatRemove, Removed
			row.Kind, row.Selector = MetadataRow, ""
		case finding.Resolved:
			rule := b.rule(selector)
			row.Key = "field:" + selector
			row.Treatment, row.Result = treatmentOf(rule)
			row.Rule = rule
		default:
			row.Key = "field:" + selector
			if selector == "" {
				row.Key = "unmapped:" + field
			}
			row.Treatment, row.Result = TreatNone, Unresolved
			if rule := b.rule(selector); rule != nil {
				row.Treatment, _ = treatmentOf(rule)
				row.Rule = rule
			}
			if finding.Class == "" {
				row.Category = "unassigned"
			}
		}
		location := finding.Location
		if selector != "" {
			location = location[:strings.LastIndex(location, "/")+1] + selector
		}
		b.row(row, location)
		if parsed, err := hl7.ParseSelector(selector); err == nil && finding.Resolved {
			for _, example := range b.deriver.Examples(parsed) {
				b.example(row.Key, example.Original, example.Derived)
			}
		}
	}
}

// findingField is the display field and the canonical selector of a
// finding's location: "case/<id>/PID[1]-5[1]" names PID-5, and
// "case/<id>/PID[1]-7" names the whole of PID-7.
func findingField(location string) (string, string) {
	parts := strings.Split(location, "/")
	last := parts[len(parts)-1]
	if selector, err := hl7.ParseSelector(last); err == nil {
		return FieldLabel(selector), selector.String()
	}
	if at := strings.Index(last, "]-"); at > 0 {
		segment := last[:strings.Index(last, "[")]
		return segment + "-" + last[at+2:], ""
	}
	if at := strings.Index(last, "["); at > 0 {
		return last[:at], ""
	}
	return "Message", ""
}

// FieldLabel is a selector as a person writes it: PID-5, OBX[2]-5, PID-3.1.
func FieldLabel(selector hl7.Selector) string {
	p := selector.Parts()
	label := p.Segment
	if p.Occurrence > 1 {
		label += fmt.Sprintf("[%d]", p.Occurrence)
	}
	label += fmt.Sprintf("-%d", p.Field)
	if p.Repetition > 1 {
		label += fmt.Sprintf("[%d]", p.Repetition)
	}
	if p.Component != 0 {
		label += fmt.Sprintf(".%d", p.Component)
	}
	if p.Subcomponent != 0 {
		label += fmt.Sprintf(".%d", p.Subcomponent)
	}
	return label
}

func (b *builder) rule(selector string) *redact.FieldRule {
	if b.policy == nil || selector == "" {
		return nil
	}
	wanted, err := hl7.ParseSelector(selector)
	if err != nil {
		return nil
	}
	for i := range b.policy.Fields {
		if held, err := hl7.ParseSelector(b.policy.Fields[i].Selector); err == nil && held.String() == wanted.String() {
			rule := b.policy.Fields[i]
			return &rule
		}
	}
	return nil
}

func treatmentOf(rule *redact.FieldRule) (string, string) {
	if rule == nil {
		return TreatNone, Unresolved
	}
	switch rule.Policy {
	case redact.Remove:
		return TreatRemove, Removed
	case redact.Replace:
		return TreatReplace, Replaced
	case redact.Surrogate:
		return TreatSurrogate, Surrogated
	case redact.DateShift:
		return TreatShift, Shifted
	case redact.Retain:
		return TreatKeep, Kept
	}
	return TreatNone, Unresolved
}

func (b *builder) issue(issue Issue) {
	if !slices.ContainsFunc(b.share.Issues, func(held Issue) bool { return held.Key == issue.Key }) {
		b.share.Issues = append(b.share.Issues, issue)
	}
}

func (b *builder) replaced(original string) {
	if original != "" {
		b.terms = append(b.terms, []byte(original))
	}
}

// document is the report as shared: every value it restates derived or
// left original and counted, its free text and metadata treated or left.
func (b *builder) document(doc *report.Document) *report.Document {
	shared := *doc
	title := Row{Key: "title", Kind: FreeTextRow, Category: "free-text", Field: "Report title"}
	switch {
	case b.request.Overrides.Title != nil:
		b.replaced(doc.Title)
		shared.Title = *b.request.Overrides.Title
		title.Treatment, title.Result = TreatReplace, Replaced
	case b.has(redact.Metadata):
		b.replaced(doc.Title)
		shared.Title = "Report"
		title.Treatment, title.Result = TreatRegenerate, Regenerated
	default:
		title.Treatment, title.Result = TreatNone, Unresolved
	}
	b.row(title, "title")
	b.example("title", doc.Title, shared.Title)
	if doc.Notes != nil {
		if b.removed["notes"] {
			shared.Notes = nil
		} else {
			notes := Row{Key: "notes", Kind: FreeTextRow, Category: "free-text", Field: "Notes", Treatment: TreatNone, Result: Unresolved}
			if treatment := b.request.Overrides.Notes; treatment != nil {
				b.replaced(*doc.Notes)
				switch {
				case treatment.Remove:
					shared.Notes = nil
					notes.Treatment, notes.Result = TreatRemove, Removed
				case treatment.Replace != nil:
					text := *treatment.Replace
					shared.Notes = &text
					notes.Treatment, notes.Result = TreatReplace, Replaced
				}
			}
			b.row(notes, "notes")
			if shared.Notes != nil {
				b.example("notes", *doc.Notes, *shared.Notes)
			} else {
				b.example("notes", *doc.Notes, "")
			}
		}
	}
	shared.Runs = slices.Clone(doc.Runs)
	for i := range shared.Runs {
		run := &shared.Runs[i]
		if run.Test != "" {
			row := Row{Key: "test-name", Kind: MetadataRow, Category: "metadata", Field: "Test name", Treatment: TreatNone, Result: Unresolved}
			if b.has(redact.Metadata) {
				b.replaced(run.Test)
				run.Test = "Test"
				row.Treatment, row.Result = TreatRegenerate, Regenerated
			}
			b.row(row, fmt.Sprintf("runs/%d/test", i))
		}
		if run.StartedAt != "" || run.CompletedAt != "" {
			row := Row{Key: "run-times", Kind: MetadataRow, Category: "dates-and-ages", Field: "Run times", Treatment: TreatNone, Result: Unresolved}
			if b.has(redact.Metadata) {
				run.StartedAt, run.CompletedAt = "", ""
				row.Treatment, row.Result = TreatRegenerate, Regenerated
			}
			b.row(row, fmt.Sprintf("runs/%d/times", i))
		}
	}
	shared.Checks = slices.Clone(doc.Checks)
	for i := range shared.Checks {
		check := &shared.Checks[i]
		check.Expected = b.value(fmt.Sprintf("checks/%s/expected", check.ID), check.Selector, check.Expected)
		if check.Observed != nil {
			observed := b.value(fmt.Sprintf("checks/%s/observed", check.ID), check.Selector, *check.Observed)
			check.Observed = &observed
		}
	}
	if doc.Comparison != nil {
		comparison := *doc.Comparison
		comparison.Checks = slices.Clone(doc.Comparison.Checks)
		for i := range comparison.Checks {
			change := &comparison.Checks[i]
			if change.BeforeObserved != nil {
				before := b.value(fmt.Sprintf("comparison/%s/before", change.ID), change.Selector, *change.BeforeObserved)
				change.BeforeObserved = &before
			}
			if change.AfterObserved != nil {
				after := b.value(fmt.Sprintf("comparison/%s/after", change.ID), change.Selector, *change.AfterObserved)
				change.AfterObserved = &after
			}
		}
		shared.Comparison = &comparison
	}
	shared.Limitations = slices.Clone(doc.Limitations)
	if b.policy != nil {
		shared.Limitations = append(shared.Limitations, "Values in this report were derived for sharing under a disclosure template; they are not the original values.")
	}
	return &shared
}

// value derives one restated value: field text by the check's own selector,
// appointment records member by member.
func (b *builder) value(location, selector string, value testrunner.Value) testrunner.Value {
	out := value
	if value.Field != nil && value.Field.State == hl7.Present && value.Field.Text != nil && *value.Field.Text != "" {
		label := "Acknowledgement field"
		if parsed, err := hl7.ParseSelector(selector); err == nil {
			label = FieldLabel(parsed)
		}
		text, removed := b.text(*value.Field.Text, selector, "value:"+label, label, location+"/field")
		field := *value.Field
		if removed {
			field.State, field.Text = hl7.Empty, nil
		} else {
			field.Text = &text
		}
		out.Field = &field
	}
	if value.Records != nil {
		records := slices.Clone(*value.Records)
		for i := range records {
			r := &records[i]
			for _, member := range []struct {
				label string
				id    *observation.Identifier
			}{{"Patient ID", &r.PatientID}, {"Placer ID", &r.PlacerID}, {"Filler ID", &r.FillerID}} {
				for p, part := range []*string{&member.id.Value, &member.id.Namespace, &member.id.UniversalID, &member.id.UniversalIDType} {
					if *part != "" {
						*part, _ = b.text(*part, "", "value:"+member.label, member.label, fmt.Sprintf("%s/records/%d/%s/%d", location, i, member.label, p))
					}
				}
			}
			if r.AppointmentStart != "" {
				r.AppointmentStart, _ = b.text(r.AppointmentStart, "", "value:Appointment start", "Appointment start", fmt.Sprintf("%s/records/%d/start", location, i))
			}
		}
		out.Records = &records
	}
	return out
}

// text derives one restated text: what the derived messages made of the
// same source value, else the rule of the check's own selector when it needs
// no message to apply, else the draft's treatment of its row; otherwise it
// stays original and its row is unresolved. removed says it was removed.
func (b *builder) text(original, selector, rowKey, label, location string) (string, bool) {
	row, shared, removed := b.derive(original, selector, rowKey, label)
	b.row(row, location)
	b.example(row.Key, original, shared)
	if shared != original {
		b.replaced(original)
	}
	return shared, removed
}

func (b *builder) derive(original, selector, rowKey, label string) (Row, string, bool) {
	if b.deriver != nil {
		if derived := b.deriver.Lookup(original); derived != nil && !derived.Conflict {
			rule := derived.Rule
			parsed, _ := hl7.ParseSelector(rule.Selector)
			treatment, result := treatmentOf(&rule)
			return Row{Key: "field:" + parsed.String(), Kind: FieldRow, Category: rule.Class, Field: FieldLabel(parsed), Selector: parsed.String(),
				Treatment: treatment, Result: result, Rule: &rule}, derived.Derived, derived.Derived == "" && rule.Policy == redact.Remove
		}
		if rule := b.rule(selector); rule != nil {
			parsed, _ := hl7.ParseSelector(rule.Selector)
			row := Row{Key: "field:" + parsed.String(), Kind: FieldRow, Category: rule.Class, Field: FieldLabel(parsed), Selector: parsed.String(), Rule: rule}
			row.Treatment, row.Result = treatmentOf(rule)
			switch {
			case rule.Policy == redact.Remove:
				return row, "", true
			case rule.Policy == redact.Replace:
				return row, *rule.Replacement, false
			case rule.Policy == redact.Retain && slices.Contains(rule.Allowed, original):
				return row, original, false
			}
			// A surrogate or date shift needs the message the value came
			// from; a value no message held stays original.
			row.Result = Unresolved
			return row, original, false
		}
	}
	row := Row{Key: rowKey, Kind: ValueRow, Category: "unassigned", Field: label, Treatment: TreatNone, Result: Unresolved}
	for _, treatment := range b.request.Overrides.Values {
		switch {
		case treatment.Row != rowKey:
		case treatment.Remove:
			row.Treatment, row.Result = TreatRemove, Removed
			return row, "", true
		case treatment.Replace != nil:
			row.Treatment, row.Result = TreatReplace, Replaced
			return row, *treatment.Replace, false
		}
	}
	return row, original, false
}

func (b *builder) attachments() {
	if !b.request.Contents.Attachments {
		return
	}
	for _, attachment := range b.request.Attachments {
		key := "attachment:" + attachment.Name
		b.item(Item{Key: key, Name: attachment.Name, Type: AttachmentType, Removable: true, Problem: attachment.Unreadable})
		if b.removed[key] {
			continue
		}
		if attachment.Unreadable != "" {
			b.issue(Issue{Key: key, Text: attachment.Name + " cannot be read; remove it from contents", Blocking: true})
			continue
		}
		b.row(Row{Key: key, Kind: AttachmentRow, Category: "attachments", Field: attachment.Name, Treatment: TreatNone, Result: Unresolved}, key)
		b.share.Files = append(b.share.Files, File{Name: "Attachments/" + attachment.Name, Kind: AttachmentType, Data: attachment.Data})
	}
}

func (b *builder) original() {
	if !b.request.Contents.Original {
		return
	}
	b.item(Item{Key: "original", Name: "Original evidence", Type: OriginalType, Removable: true})
	if b.removed["original"] {
		return
	}
	b.share.Original = true
	b.row(Row{Key: "original", Kind: OriginalRow, Category: "original-evidence", Field: "Original evidence", Treatment: TreatNone, Result: Original}, "original")
}

// residual scans every generated file for each original value the share
// replaced; a hit is an unresolved issue whatever the rows said.
func (b *builder) residual() {
	if b.policy == nil {
		return
	}
	terms := append(b.deriver.Terms(), b.terms...)
	files := map[string][]byte{}
	for _, file := range b.share.Files {
		if file.Kind != AttachmentType {
			files[file.Name] = file.Data
		}
	}
	scan := exportreview.Residual(files, terms)
	for _, location := range scan.Locations {
		b.issue(Issue{Key: "residual:" + location, Text: "An original value remains in " + location})
	}
}

// finish orders the rows, drops empty ones, and states what the share can
// claim.
func (b *builder) finish() {
	for _, key := range b.order {
		if row := b.rows[key]; row.Occurrences > 0 {
			b.share.Rows = append(b.share.Rows, *row)
		}
	}
	slices.SortStableFunc(b.share.Rows, func(x, y Row) int { return cmp.Compare(rank(x.Result), rank(y.Result)) })
	unresolved := false
	for _, row := range b.share.Rows {
		switch row.Result {
		case Unresolved:
			unresolved = true
			b.issue(Issue{Key: row.Key, Text: row.Field + " is unresolved"})
		case Original:
			unresolved = true
		}
	}
	for _, issue := range b.share.Issues {
		if strings.HasPrefix(issue.Key, "residual:") {
			unresolved = true
		}
	}
	if b.share.RunCheck {
		b.issue(Issue{Key: "run-check", Text: "The template requires a check run of the derived messages"})
	}
	b.share.SourceValues = unresolved
	b.share.Redacted = b.policy != nil && !unresolved
}

func rank(result string) int {
	switch result {
	case Unresolved:
		return 0
	case Original:
		return 1
	}
	return 2
}

// fileName is a report title as a file name offers it.
func fileName(title string) string {
	name := strings.Map(func(r rune) rune {
		if r < 0x20 || strings.ContainsRune(`/\:*?"<>|`, r) {
			return '-'
		}
		return r
	}, strings.TrimSpace(title))
	name = strings.Trim(name, ". ")
	for len(name) > 120 {
		// Shortened by whole characters, never inside one.
		_, size := utf8.DecodeLastRuneInString(name)
		name = name[:len(name)-size]
	}
	return cmp.Or(name, "Report")
}
