package fhirr4_test

import (
	"slices"
	"testing"

	"github.com/bharm16/readmit/internal/fhirr4"
)

// These fixtures are independently authored from the fixed R4 4.0.1 identity
// rules, rather than generated by the resolver under test:
// https://hl7.org/fhir/R4/bundle.html#references
// https://hl7.org/fhir/R4/references.html#contained
func referenceDocument(t *testing.T, raw string) *fhirr4.Document {
	t.Helper()
	d, err := fhirr4.Decode(t.Context(), []byte(raw), contextR4())
	if err != nil {
		t.Fatal(err)
	}
	return d
}

func referenceOccurrence(t *testing.T, d *fhirr4.Document, pointer string) string {
	t.Helper()
	for _, r := range d.Resources() {
		if r.Pointer == pointer {
			return r.Occurrence
		}
	}
	t.Fatalf("no resource at fixture pointer %q", pointer)
	return ""
}

func requireResolution(t *testing.T, got fhirr4.Resolution, state string, occurrences ...string) {
	t.Helper()
	if got.State != state || !slices.Equal(got.Occurrences, occurrences) {
		t.Fatalf("resolution = %+v, want %s %v", got, state, occurrences)
	}
}

func TestFHIRReferenceContractVersionedBundleIdentity(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Bundle","type":"collection","entry":[
		{"fullUrl":"https://clinic.test/r4/Patient/shared","resource":{"resourceType":"Patient","id":"shared","meta":{"versionId":"v1"}}},
		{"fullUrl":"https://clinic.test/r4/Patient/shared","resource":{"resourceType":"Patient","id":"shared","meta":{"versionId":"v2"}}},
		{"fullUrl":"https://clinic.test/r4/Observation/result","resource":{"resourceType":"Observation","id":"result","status":"final","code":{"text":"Synthetic result"},"subject":{"reference":"Patient/shared"}}}
	]}`)
	old := referenceOccurrence(t, d, "/entry/0/resource")
	newer := referenceOccurrence(t, d, "/entry/1/resource")
	source := referenceOccurrence(t, d, "/entry/2/resource")
	if old == newer {
		t.Fatal("resource versions collapsed to one occurrence")
	}
	requireResolution(t, d.Resolve(source, "Patient/shared"), "ambiguous", old, newer)
	requireResolution(t, d.Resolve(source, "https://clinic.test/r4/Patient/shared"), "ambiguous", old, newer)
	requireResolution(t, d.Resolve(source, "Patient/shared/_history/v1"), "resolved", old)
	requireResolution(t, d.Resolve(source, "https://clinic.test/r4/Patient/shared/_history/v2"), "resolved", newer)
	requireResolution(t, d.Resolve(source, "Patient/shared/_history/v3"), "external")
}

func TestFHIRReferenceContractRelativeBaseBelongsToEntry(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Bundle","type":"collection","entry":[
		{"fullUrl":"https://east.test/r4/Patient/shared","resource":{"resourceType":"Patient","id":"shared"}},
		{"fullUrl":"https://west.test/r4/Patient/shared","resource":{"resourceType":"Patient","id":"shared"}},
		{"fullUrl":"https://east.test/r4/Observation/east","resource":{"resourceType":"Observation","id":"east","status":"final","code":{"text":"Synthetic result"},"subject":{"reference":"Patient/shared"}}},
		{"fullUrl":"https://west.test/r4/Observation/west","resource":{"resourceType":"Observation","id":"west","status":"final","code":{"text":"Synthetic result"},"subject":{"reference":"Patient/shared"}}},
		{"fullUrl":"urn:uuid:ffffffff-ffff-4fff-8fff-ffffffffffff","resource":{"resourceType":"Observation","id":"unlocated","status":"final","code":{"text":"Synthetic result"},"subject":{"reference":"Patient/shared"}}},
		{"fullUrl":"https://example.test/fhir/Patient/shared","resource":{"resourceType":"Patient","id":"shared"}}
	]}`)
	east := referenceOccurrence(t, d, "/entry/0/resource")
	west := referenceOccurrence(t, d, "/entry/1/resource")
	eastSource := referenceOccurrence(t, d, "/entry/2/resource")
	westSource := referenceOccurrence(t, d, "/entry/3/resource")
	urnSource := referenceOccurrence(t, d, "/entry/4/resource")
	requireResolution(t, d.Resolve(eastSource, "Patient/shared"), "resolved", east)
	requireResolution(t, d.Resolve(westSource, "Patient/shared"), "resolved", west)
	requireResolution(t, d.Resolve(urnSource, "Patient/shared"), "missing")
	requireResolution(t, d.Resolve(urnSource, "https://west.test/r4/Patient/shared"), "resolved", west)
	requireResolution(t, d.Resolve(eastSource, "urn:uuid:ffffffff-ffff-4fff-8fff-ffffffffffff"), "resolved", urnSource)
	if got := d.MatchingResources("Patient", nil); len(got) != 3 {
		t.Fatalf("equal unqualified IDs collapsed across bases: %+v", got)
	}
}

func TestFHIRReferenceContractContainedScopeAndParent(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Bundle","type":"collection","entry":[
		{"fullUrl":"https://clinic.test/r4/Patient/first","resource":{"resourceType":"Patient","id":"first","contained":[{"resourceType":"Observation","id":"local","status":"final","code":{"text":"Synthetic result"},"subject":{"reference":"#"}}]}},
		{"fullUrl":"https://clinic.test/r4/Patient/second","resource":{"resourceType":"Patient","id":"second","contained":[{"resourceType":"Observation","id":"local","status":"final","code":{"text":"Synthetic result"},"subject":{"reference":"#"}}]}}
	]}`)
	first := referenceOccurrence(t, d, "/entry/0/resource")
	firstChild := referenceOccurrence(t, d, "/entry/0/resource/contained/0")
	second := referenceOccurrence(t, d, "/entry/1/resource")
	secondChild := referenceOccurrence(t, d, "/entry/1/resource/contained/0")
	requireResolution(t, d.Resolve(first, "#local"), "resolved", firstChild)
	requireResolution(t, d.Resolve(second, "#local"), "resolved", secondChild)
	requireResolution(t, d.Resolve(firstChild, "#"), "resolved", first)
	requireResolution(t, d.Resolve(secondChild, "#"), "resolved", second)
	requireResolution(t, d.Resolve(firstChild, "#local"), "resolved", firstChild)
	requireResolution(t, d.Resolve(firstChild, "Patient/second"), "resolved", second)
	requireResolution(t, d.Resolve(first, "Observation/local"), "external")
	joined := d.Join(t.Context(), firstChild, path("subject"), "Patient")
	if len(joined) != 1 {
		t.Fatalf("parent join count = %d", len(joined))
	}
	requireResolution(t, joined[0].Resolution, "resolved", first)
}

func TestFHIRReferenceContractDuplicateContainedIDsAreAmbiguous(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Patient","id":"parent","generalPractitioner":[{"reference":"#same"}],"contained":[{"resourceType":"Practitioner","id":"same"},{"resourceType":"Practitioner","id":"same"}]}`)
	parent := referenceOccurrence(t, d, "")
	first := referenceOccurrence(t, d, "/contained/0")
	second := referenceOccurrence(t, d, "/contained/1")
	requireResolution(t, d.Resolve(parent, "#same"), "ambiguous", first, second)
	joined := d.Join(t.Context(), parent, path("generalPractitioner[*]"), "Practitioner")
	if len(joined) != 1 || joined[0].Resolution.State == "resolved" {
		t.Fatalf("duplicate contained ID became a successful join: %+v", joined)
	}
}

func TestFHIRReferenceContractBusinessIdentifierNeverUsesDisplay(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Bundle","type":"collection","entry":[
		{"fullUrl":"urn:uuid:11111111-1111-4111-8111-111111111111","resource":{"resourceType":"Practitioner","id":"one","identifier":[{"system":"urn:clinic:staff","value":"ABC"}],"name":[{"text":"Same display"}]}},
		{"fullUrl":"urn:uuid:22222222-2222-4222-8222-222222222222","resource":{"resourceType":"Practitioner","id":"two","identifier":[{"system":"urn:other:staff","value":"ABC"}],"name":[{"text":"Same display"}]}},
		{"fullUrl":"urn:uuid:33333333-3333-4333-8333-333333333333","resource":{"resourceType":"Patient","id":"patient","generalPractitioner":[
			{"identifier":{"system":"urn:clinic:staff","value":"ABC"},"display":"Different display"},
			{"display":"Same display"},
			{"identifier":{"system":"urn:clinic:staff","value":"abc"}},
			{"identifier":{"value":"ABC"}},
			{"identifier":{"system":"urn:other:staff","value":"ABC"}}
		]}}
	]}`)
	first := referenceOccurrence(t, d, "/entry/0/resource")
	second := referenceOccurrence(t, d, "/entry/1/resource")
	source := referenceOccurrence(t, d, "/entry/2/resource")
	got := d.Join(t.Context(), source, path("generalPractitioner[*]"), "Practitioner")
	if len(got) != 5 {
		t.Fatalf("join count = %d", len(got))
	}
	requireResolution(t, got[0].Resolution, "resolved", first)
	for _, index := range []int{1, 2, 3} {
		requireResolution(t, got[index].Resolution, "missing")
	}
	requireResolution(t, got[4].Resolution, "resolved", second)
	matches := d.MatchingResources("Practitioner", &fhirr4.BusinessID{System: "urn:clinic:staff", Value: "ABC"})
	if len(matches) != 1 || matches[0].Occurrence != first {
		t.Fatalf("business identifier namespace ignored: %+v", matches)
	}
}

func TestFHIRReferenceContractBusinessIdentifierMultiplicity(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Bundle","type":"collection","entry":[
		{"fullUrl":"https://clinic.test/r4/Practitioner/first","resource":{"resourceType":"Practitioner","id":"first","identifier":[{"system":"urn:clinic:staff","value":"same"},{"system":"urn:clinic:staff","value":"same"}]}},
		{"fullUrl":"https://clinic.test/r4/Practitioner/second","resource":{"resourceType":"Practitioner","id":"second","identifier":[{"system":"urn:clinic:staff","value":"same"}]}},
		{"fullUrl":"https://clinic.test/r4/Patient/source","resource":{"resourceType":"Patient","id":"source","generalPractitioner":[{"identifier":{"system":"urn:clinic:staff","value":"same"},"type":"Practitioner"}]}}
	]}`)
	first := referenceOccurrence(t, d, "/entry/0/resource")
	second := referenceOccurrence(t, d, "/entry/1/resource")
	source := referenceOccurrence(t, d, "/entry/2/resource")
	matches := d.MatchingResources("Practitioner", &fhirr4.BusinessID{System: "urn:clinic:staff", Value: "same"})
	if len(matches) != 2 || matches[0].Occurrence != first || matches[1].Occurrence != second {
		t.Fatalf("business identifiers changed resource occurrence multiplicity: %+v", matches)
	}
	joined := d.Join(t.Context(), source, path("generalPractitioner[*]"), "Practitioner")
	if len(joined) != 1 {
		t.Fatalf("join count = %d", len(joined))
	}
	requireResolution(t, joined[0].Resolution, "ambiguous", first, second)
}

func TestFHIRReferenceContractJoinRejectsTypeConflicts(t *testing.T) {
	for _, tc := range []struct {
		name, declared, requested, state string
	}{
		{"matching", "Practitioner", "Practitioner", "resolved"},
		{"canonical type", "http://hl7.org/fhir/StructureDefinition/Practitioner", "Practitioner", "resolved"},
		{"declared mismatch", "Patient", "Practitioner", "invalid"},
		{"requested mismatch", "Practitioner", "Patient", "invalid"},
		{"both mismatch", "Patient", "Patient", "invalid"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			d := referenceDocument(t, `{"resourceType":"Patient","id":"parent","contained":[{"resourceType":"Practitioner","id":"staff"}],"generalPractitioner":[{"reference":"#staff","type":"`+tc.declared+`"}]}`)
			parent := referenceOccurrence(t, d, "")
			child := referenceOccurrence(t, d, "/contained/0")
			got := d.Join(t.Context(), parent, path("generalPractitioner[*]"), tc.requested)
			if len(got) != 1 {
				t.Fatalf("join count = %d", len(got))
			}
			if tc.state == "resolved" {
				requireResolution(t, got[0].Resolution, "resolved", child)
			} else if got[0].Resolution.State != tc.state {
				t.Fatalf("type conflict did not refuse resolution: %+v", got)
			}
		})
	}
}

// R4 Bundle resolution searches entries in the containing Bundle. Nesting a
// Bundle as a resource does not import its entries into the parent's scope.
func TestFHIRReferenceContractNestedBundleScope(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Bundle","type":"collection","entry":[
		{"fullUrl":"urn:uuid:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","resource":{"resourceType":"Practitioner","id":"outside","identifier":[{"system":"urn:readmit:staff","value":"outside"}]}},
		{"fullUrl":"urn:uuid:bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb","resource":{"resourceType":"Patient","id":"outer-patient","generalPractitioner":[{"reference":"urn:uuid:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"},{"identifier":{"system":"urn:readmit:staff","value":"inside"}}]}},
		{"fullUrl":"urn:uuid:cccccccc-cccc-4ccc-8ccc-cccccccccccc","resource":{"resourceType":"Bundle","type":"collection","entry":[
			{"fullUrl":"urn:uuid:dddddddd-dddd-4ddd-8ddd-dddddddddddd","resource":{"resourceType":"Practitioner","id":"inside","identifier":[{"system":"urn:readmit:staff","value":"inside"}]}},
			{"fullUrl":"urn:uuid:eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee","resource":{"resourceType":"Patient","id":"inner-patient","generalPractitioner":[
				{"reference":"urn:uuid:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"},
				{"identifier":{"system":"urn:readmit:staff","value":"outside"}},
				{"reference":"urn:uuid:dddddddd-dddd-4ddd-8ddd-dddddddddddd"},
				{"identifier":{"system":"urn:readmit:staff","value":"inside"}},
				{"reference":"urn:uuid:ffffffff-ffff-4fff-8fff-ffffffffffff"}
			]}}
		]}}
	]}`)
	outerTarget := referenceOccurrence(t, d, "/entry/0/resource")
	outerSource := referenceOccurrence(t, d, "/entry/1/resource")
	innerTarget := referenceOccurrence(t, d, "/entry/2/resource/entry/0/resource")
	innerSource := referenceOccurrence(t, d, "/entry/2/resource/entry/1/resource")
	t.Run("inner cannot borrow outer URN", func(t *testing.T) {
		requireResolution(t, d.Resolve(innerSource, "urn:uuid:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"), "missing")
	})
	t.Run("outer cannot borrow inner URN", func(t *testing.T) {
		requireResolution(t, d.Resolve(outerSource, "urn:uuid:dddddddd-dddd-4ddd-8ddd-dddddddddddd"), "missing")
	})
	t.Run("each scope resolves its own URN", func(t *testing.T) {
		requireResolution(t, d.Resolve(outerSource, "urn:uuid:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"), "resolved", outerTarget)
		requireResolution(t, d.Resolve(innerSource, "urn:uuid:dddddddd-dddd-4ddd-8ddd-dddddddddddd"), "resolved", innerTarget)
	})
	t.Run("inner joins stay in their Bundle", func(t *testing.T) {
		got := d.Join(t.Context(), innerSource, path("generalPractitioner[*]"), "Practitioner")
		if len(got) != 5 {
			t.Fatalf("join count = %d", len(got))
		}
		for index, want := range []struct {
			name, state string
			ids         []string
		}{
			{"outer literal", "missing", nil},
			{"outer identifier", "missing", nil},
			{"local literal", "resolved", []string{innerTarget}},
			{"local identifier", "resolved", []string{innerTarget}},
			{"absent literal", "missing", nil},
		} {
			t.Run(want.name, func(t *testing.T) {
				requireResolution(t, got[index].Resolution, want.state, want.ids...)
			})
		}
	})
	t.Run("outer logical join cannot borrow inner identifier", func(t *testing.T) {
		got := d.Join(t.Context(), outerSource, path("generalPractitioner[*]"), "Practitioner")
		if len(got) != 2 {
			t.Fatalf("join count = %d", len(got))
		}
		requireResolution(t, got[0].Resolution, "resolved", outerTarget)
		requireResolution(t, got[1].Resolution, "missing")
	})
}

func TestFHIRReferenceContractSiblingBundlesDoNotCreateAmbiguity(t *testing.T) {
	d := referenceDocument(t, `{"resourceType":"Bundle","type":"collection","entry":[
		{"fullUrl":"urn:uuid:11111111-1111-4111-8111-111111111111","resource":{"resourceType":"Bundle","type":"collection","entry":[
			{"fullUrl":"urn:uuid:33333333-3333-4333-8333-333333333333","resource":{"resourceType":"Practitioner","id":"east","identifier":[{"system":"urn:readmit:staff","value":"shared"}]}},
			{"fullUrl":"urn:uuid:44444444-4444-4444-8444-444444444444","resource":{"resourceType":"Patient","id":"east-patient","generalPractitioner":[{"reference":"urn:uuid:33333333-3333-4333-8333-333333333333"},{"identifier":{"system":"urn:readmit:staff","value":"shared"}}]}}
		]}},
		{"fullUrl":"urn:uuid:22222222-2222-4222-8222-222222222222","resource":{"resourceType":"Bundle","type":"collection","entry":[
			{"fullUrl":"urn:uuid:33333333-3333-4333-8333-333333333333","resource":{"resourceType":"Practitioner","id":"west","identifier":[{"system":"urn:readmit:staff","value":"shared"}]}},
			{"fullUrl":"urn:uuid:55555555-5555-4555-8555-555555555555","resource":{"resourceType":"Patient","id":"west-patient","generalPractitioner":[{"reference":"urn:uuid:33333333-3333-4333-8333-333333333333"},{"identifier":{"system":"urn:readmit:staff","value":"shared"}}]}}
		]}}
	]}`)
	for _, tc := range []struct{ name, entry string }{{"east", "/entry/0/resource"}, {"west", "/entry/1/resource"}} {
		t.Run(tc.name, func(t *testing.T) {
			target := referenceOccurrence(t, d, tc.entry+"/entry/0/resource")
			source := referenceOccurrence(t, d, tc.entry+"/entry/1/resource")
			t.Run("URN", func(t *testing.T) {
				requireResolution(t, d.Resolve(source, "urn:uuid:33333333-3333-4333-8333-333333333333"), "resolved", target)
			})
			got := d.Join(t.Context(), source, path("generalPractitioner[*]"), "Practitioner")
			if len(got) != 2 {
				t.Fatalf("join count = %d", len(got))
			}
			t.Run("literal join", func(t *testing.T) { requireResolution(t, got[0].Resolution, "resolved", target) })
			t.Run("logical join", func(t *testing.T) { requireResolution(t, got[1].Resolution, "resolved", target) })
		})
	}
}
