// Synthetic result shapes from the adjacent production component tests. These
// are visual examples only; no fixture is submitted to an engine or a network.
const HASH = "a".repeat(64);
const STAMP = "2026-09-26T12:00:00Z";
const decision = {
  schema: "readmit-send-decision/v1",
  allowed: false,
  reason: "send_not_explicit",
  address: "synthetic-test-endpoint",
  classification: "nonproduction",
  explicit_send: false,
  policy_selected: true,
  approved_destinations: ["synthetic-approved-prefix"],
  resolved_addresses: ["synthetic-resolved-endpoint"],
  decided_at: STAMP,
};
const replayRun = {
  output: "replay-001",
  decision_file: "replay-001.decision.json",
  identity: HASH,
  schema: "readmit-run/v1",
  state: "complete",
  contains_source_values: true,
  export_policy: "customer-local-only",
  successful: false,
  uncertain: 1,
  messages: [
    {
      source: "s0001-e000001",
      outbound: "o000001",
      outcome: "cancelled",
      delivery: "uncertain",
      sent_bytes: 312,
      received_bytes: 0,
      ack: "",
      correlation: "none",
      elapsed: "1.2s",
      error_class: "cancelled",
      error_phase: "read",
    },
  ],
};
const scheduleEntry = {
  id: "nightly",
  zone: "America/New_York",
  at: "02:30",
  window_seconds: 900,
  runner_config: "/synthetic-runner/config.json",
  spec: "/synthetic-workspace/spec.json",
  input_sha256: HASH,
  route: "https://alerts.example/",
  approved: true,
};
const evidence = [
  {
    path: "sample-case",
    class: "canonical-evidence",
    state: "verified",
    explanation: "Canonical registered synthetic evidence.",
  },
];
export const privateData = {
  suiteHandoff: {
    handoff: {
      entry: "nightly-suite.json",
      environment: "synthetic-lab",
      prepared: "synthetic-prepared",
      releases: "nightly-releases.json",
    },
  },
  policyReview: {
    file: "receiver-policy.json",
    enhanced: false,
    policy: {
      schema: "readmit-receiver-policy/v3",
      name: "synthetic-receiver",
      source_label: "synthetic-source",
      acknowledgement: { operator: "original-mode-fixed-code", code: "AA" },
      accepted_message_types: {
        operator: "message-type-in",
        values: ["SIU^S12", "SIU^S13"],
      },
      enhanced_acknowledgement: {
        operator: "unsupported",
        accept_code: "",
        application_code: "",
        application_delivery: "",
        application_endpoint: "",
        approved_transport: false,
      },
    },
  },
  sourceReview: {
    file: "sources/synthetic.json",
    source: {
      schema: "readmit-source/v1",
      name: "synthetic-export",
      kind: "transfer",
      scope: "appointments",
      quota: {
        max_entries: 64,
        max_entry_bytes: 4194304,
        max_total_bytes: 33554432,
      },
      retry: { attempts: 2, backoff: "250ms" },
      address: "synthetic-source-address",
      classification: "nonproduction",
      command: "synthetic-transfer-program",
      arguments: ["--path", "appointments"],
      secrets_file: "synthetic-reference-document",
      credential: "synthetic-reference",
    },
  },
  inventoryList: { title: "Evidence", entries: evidence },
  backupReport: {
    result: {
      state: "completed",
      report: {
        root: "/synthetic-workspace/backup",
        complete: true,
        files: 2,
        bytes: 40,
        evidence,
        mutable: [
          {
            path: "project.json",
            class: "mutable-project-document",
            explanation: "Mutable project document.",
          },
        ],
        exclusions: [
          {
            path: "search.index.json",
            class: "declared-exclusion",
            retention: "states",
            explanation: "Derived index declarations only.",
          },
        ],
        credentials: [
          {
            path: "secrets.json",
            class: "credential-reference",
            explanation: "Credential reference document.",
          },
        ],
        protection: [],
        other: [],
      },
    },
  },
  progressLine: {
    progress: {
      state: "busy",
      operation: "scan",
      records: 300,
      occurrences: 300,
      batches: 43,
      bytes: 91200,
      phase: "scanning",
      complete: false,
    },
  },
  scanReport: {
    state: "completed",
    scan: {
      plan: {
        schema: "readmit-import-plan/v1",
        framing: "mllp",
        terminator: "cr",
        encoding: "us-ascii",
        direction: "inbound",
        members: [],
      },
      bytes: 91200,
      sha256: HASH,
      records: 300,
      occurrences: 300,
      decoded: 299,
      undecodable: 1,
      batches: 43,
      peak_resident_bytes: 65536,
      bounds: {
        batch_records: 7,
        batch_bytes: 8388608,
        record_bytes: 16777216,
        resident_bound: 42008576,
      },
      case_bounds: "exceeded",
      exceeded: ["sources (128)"],
      window_offset: 150,
      window_limit: 4,
      rows: [151, 152, 153, 154].map((ordinal) => ({
        ordinal,
        offset: ordinal * 304,
        size: 304,
        occurrences: 1,
        decoded: ordinal === 153 ? 0 : 1,
        undecodable: ordinal === 153 ? 1 : 0,
      })),
      elapsed_milliseconds: 12,
      targets:
        "Synthetic engineering targets, not measured customer requirements.",
    },
  },
  rawRow: {
    row: {
      kind: "field",
      message: 1,
      segment: "PID",
      field: 3,
      label: "Patient Identifier List",
      state: "present",
      start: 70,
      end: 82,
    },
    selection: "auto",
  },
  decision,
  replayRun,
  transformPreview: {
    transformation: {
      case: "sample-case",
      rules: "synthetic.rules.json",
      plan: "synthetic.plan.json",
      boundary: "Synthetic preview of the sequence a replay would send.",
      preview: {
        schema: "readmit-transform-preview/v1",
        case: { schema: "readmit-case/v3", identity: HASH },
        plan: {
          schema: "readmit-transform-plan/v1",
          case: HASH,
          rules: HASH,
          steps: [{ operator: "rebase-identifiers/v1", rule: "patient" }],
        },
        summary: {
          occurrences: 2,
          entries: 2,
          copies: 0,
          changes: 2,
          relations: 1,
          preserved: 1,
          unsupported: 1,
        },
        sequence: [],
        changes: [
          {
            entry: "t000001",
            parent: "s0001-e000001",
            operator: "rebase-identifiers/v1",
            rule: "patient",
            selector: "PID-3.1",
            state: "present",
            group: 1,
            length: 12,
          },
        ],
        relations: [
          {
            rule: "patient",
            operator: "identifier",
            linkage: "observed",
            occurrences: ["s0001-e000001", "s0002-e000001"],
            entries: ["t000001", "t000002"],
            preserved: true,
          },
        ],
        profile: [],
        unsupported: [
          {
            code: "unshifted-positions",
            detail: "Every other date field remains unchanged.",
          },
        ],
        scope: "A preview writes nothing into evidence.",
      },
    },
  },
  reviewInventory: {
    review: {
      name: "synthetic-review",
      report: "readmit-export-review/v1",
      state: "blocked",
      data_origin: "derived-testing-data",
      identity: HASH,
      input_commitment: HASH,
      local_state_commitment: HASH,
      policies_applied: [],
      surfaces: [
        { name: "case", content: "unmapped-field", findings: 1, unresolved: 1 },
      ],
      coverage: [
        {
          class: "identifiers",
          status: "unresolved",
          handled_locations: 0,
          unresolved_locations: 1,
        },
      ],
      uncovered_classes: ["identifiers"],
      residual_scan: {
        status: "not-run",
        files_checked: 0,
        known_values_checked: 0,
        unresolved_locations: [],
        limitations: "Unresolved findings block generation and scanning.",
      },
      required_failures: [],
      original_failed_assertions: [],
      decision: "incomplete-review",
      decision_reason: "An incomplete review cannot authorize disclosure.",
      unresolved: 1,
      offset: 0,
      limit: 200,
      total: 1,
      findings: [
        {
          surface: "case",
          location: "sample-case / PID-3",
          class: "identifiers",
          reason: "Synthetic unmapped identifier location.",
          resolved: false,
          policy: "",
        },
      ],
      scope: "Synthetic review fixture.",
      boundary: "No disclosure approval or source authenticity claim.",
    },
  },
  explanation: {
    explanation: {
      run: "post-fix",
      bundle: "post-fix/run",
      verdict: "pass",
      declared: 1,
      passed: 1,
      failed: 0,
      undecided: 0,
      skipped: 0,
      set_name: "Reschedule accepted downstream",
      set_schema: "readmit-assertion-set/v1",
      set_identity: HASH,
      run_schema: "readmit-run/v1",
      run_state: "complete",
      run_identity: HASH,
      source_identity: HASH,
      contains_source_values: true,
      export_policy: "customer-local-only",
      target: "",
      transport: "plain",
      target_identity: HASH,
      started_at: STAMP,
      completed_at: STAMP,
      elapsed: "1s",
      messages: [
        {
          source: "s0001-e000001",
          outbound: "o000001",
          outcome: "application_accepted",
          delivery: "acknowledged",
          ack_code: "AA",
          ack_correlation: "matched",
          elapsed: "10ms",
          input: "payloads/o000001-sent.bin",
          observed: "payloads/o000001-received.bin",
        },
      ],
      observations: [],
      assertions: [
        {
          id: "booking-accepted",
          operator: "field_equals",
          outcome: "passed",
          reads: "MSA-1 of observed message s0001-e000001",
          expected: "present, text hidden",
          observed: "present, text hidden",
          evidence: ["observed MSA-1 of s0001-e000001"],
        },
      ],
      revealed: false,
    },
  },
  scheduleRow: { entry: scheduleEntry },
  schedulePreview: {
    preview: {
      state: "completed",
      identity: HASH,
      concurrency: "serial-skip-missed",
      entries: [
        {
          entry: scheduleEntry,
          pin_state: "computed",
          identity: HASH,
          occurrences: [{ day: "2026-03-08", state: "dst-gap" }],
          notification: "Only the approved fixed alert body may be delivered.",
        },
      ],
    },
  },
  gateVerification: {
    result: {
      state: "completed",
      gate: {
        schema: "readmit-ci-gate/v1",
        state: "passed",
        exit_code: 0,
        approval: "verified",
        pins: "verified",
        coverage: "passed",
        baseline: "verified",
        retention: "verified",
        target_revision: "operator-declared",
      },
      unverified: [],
    },
  },
  syntheticPacket: {
    view: {
      folder: "synthetic-demo-packet",
      identity: HASH,
      schema: "readmit-report/v1",
      state: "complete",
      scenario: "siu-reschedule-v1",
      provenance: "synthetic-only",
      input_identity: HASH,
      spec_identity: HASH,
      observation_boundary: "appointment-ledger",
      input_changed: false,
      receiver_behavior_changed: true,
      runs: [
        {
          path: "baseline",
          receiver_mode: "defective",
          receiver: "readmit built-in SIU fixture",
          status: "assertion_failure",
          ledger_count: 2,
          result_identity: HASH,
        },
        {
          path: "post-fix",
          receiver_mode: "fixed",
          receiver: "readmit built-in SIU fixture",
          status: "pass",
          ledger_count: 1,
          result_identity: HASH,
        },
      ],
      files: 42,
      limitations: ["Synthetic-only demonstration; not customer evidence."],
    },
  },
  syntheticRerun: {
    view: {
      folder: "synthetic-rerun",
      address: "127.0.0.1:2575",
      packet_identity: HASH,
      historical_spec_identity: HASH,
      input_identity: HASH,
      target_sha256: HASH,
      changed_bindings: ["input.case", "target", "observation.path"],
      specs: [
        { path: "baseline/spec.json", sha256: HASH },
        { path: "post-fix/spec.json", sha256: HASH },
        { path: "reintroduced/spec.json", sha256: HASH },
      ],
    },
  },
  lifecycleWrite: {
    result: {
      state: "completed",
      event: {
        schema: "readmit-hub-lifecycle-event/v1",
        project: "synthetic-project",
        sequence: 1,
        issuer: "https://idp.example",
        actor: "synthetic-reviewer",
        at: STAMP,
        kind: "archive",
        reason: "Synthetic screenshot fixture.",
        command_id: "synthetic-archive-command",
        resource: "sample-case",
      },
      replay: false,
    },
  },
};
