package redact

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/bharm16/readmit/internal/artifactdir"
	"github.com/bharm16/readmit/internal/artifactpath"
	"github.com/bharm16/readmit/internal/bundle"
	"github.com/bharm16/readmit/internal/diagnose"
	"github.com/bharm16/readmit/internal/exportreview"
	"github.com/bharm16/readmit/internal/hl7"
	"github.com/bharm16/readmit/internal/testrunner"
)

// Export approves one exact review, reruns only the built-in fixture, and copies
// only a freshly generated allowlisted packet after all gates pass. The private
// source state, original proofs, and original artifacts never enter that packet.
func Export(ctx context.Context, request ExportRequest) (*ExportManifest, error) {
	var err error
	request.ReviewPath, err = artifactpath.Directory(request.ReviewPath)
	if err != nil {
		return nil, err
	}
	request.LocalState, err = artifactpath.Resolve(request.LocalState)
	if err != nil {
		return nil, err
	}
	review, err := OpenReview(request.ReviewPath)
	if err != nil {
		return nil, err
	}
	if request.Approval != review.Identity || review.State != "ready-for-approval" || hasUnresolved(review.Findings) || review.Residual.Status != "passed" || !slices.Equal(review.RequiredFailures, review.OriginalFailedAssertions) {
		return nil, errors.New("export requires approval of an exact fully handled and proven review")
	}
	localBytes, err := readLocal(filepath.Join(request.LocalState, "state.json"), maxReviewBytes)
	if err != nil || digest(localBytes) != review.LocalStateCommitment {
		return nil, errors.New("private state does not match approved review")
	}
	var local localState
	if json.Unmarshal(localBytes, &local, json.RejectUnknownMembers(true)) != nil || local.Schema != PrivateSchema || !slices.Equal(local.OriginalProof.FailedAssertions, review.RequiredFailures) {
		return nil, errors.New("invalid private proof state")
	}
	if err := revalidate(local); err != nil {
		return nil, err
	}
	protected := append(protectedPaths(local), request.ReviewPath, request.LocalState)
	output, err := destination(request.Output, protected)
	if err != nil {
		return nil, err
	}
	if exportreview.Residual(map[string][]byte{"export-root-name": []byte(filepath.Base(output))}, local.ResidualValues).Status != "passed" {
		return nil, errors.New("export directory name contains a known residual")
	}
	derived, err := bundle.Open(filepath.Join(request.ReviewPath, "case"))
	if err != nil {
		return nil, err
	}
	spec, err := testrunner.ReadSpec(filepath.Join(request.ReviewPath, "spec.json"))
	if err != nil {
		return nil, err
	}
	// Proof and residual failures stay private. The requested export directory
	// does not exist until every generated byte has passed the release gates.
	stage, err := os.MkdirTemp(request.LocalState, "derived-proof-")
	if err != nil {
		return nil, errors.New("cannot reserve private derived proof")
	}
	casePath := filepath.Join(stage, "case")
	inputs, err := derivedInputs(derived)
	if err != nil {
		return nil, err
	}
	copy, err := bundle.Write(casePath, inputs, derived.Manifest.Provenance)
	if err != nil || copy.Identity != review.DerivedIdentity {
		return nil, errors.New("approved derived evidence could not be regenerated")
	}
	proof, err := runProof(ctx, spec, casePath, filepath.Join(stage, "proof"), review.OriginalFailedAssertions)
	if err != nil {
		// The located attempt stays the record; the proof's own explanation,
		// which names steps and verdicts but no path or value, is said here only.
		return nil, fmt.Errorf("%w; derived fixture proof: %v", blockedAttempt(stage, review, proofFindings(filepath.Join(stage, "proof"), review.OriginalFailedAssertions), exportreview.Scan{Status: "not-run", Locations: []string{}, Limitations: "Proof failed before final residual review."}), err)
	}
	// Send decisions are local execution records, not part of the approved
	// export contract. Keep them beside the private staging directory before
	// enumerating packet contents; do not weaken the packet allowlist.
	for _, session := range []string{"baseline", "postfix"} {
		from := filepath.Join(stage, "proof", session, "result.decision.json")
		to := stage + "." + session + ".decision.json"
		if err := os.Rename(from, to); err != nil {
			return nil, errors.New("cannot retain private proof send decision")
		}
	}
	report, err := diagnose.Run(casePath, diagnose.DefaultConfig())
	if err != nil {
		return nil, err
	}
	reportJSON, err := diagnose.JSON(report)
	if err != nil {
		return nil, err
	}
	if err := writeFile(stage, "diagnosis.json", reportJSON); err != nil {
		return nil, err
	}
	if err := writeFile(stage, "diagnosis.md", diagnose.Markdown(report)); err != nil {
		return nil, err
	}
	if len(report.Unsupported) > 0 {
		findings := []exportreview.Finding{}
		for i, unsupported := range report.Unsupported {
			findings = append(findings, exportreview.Finding{Location: fmt.Sprintf("diagnosis/unsupported/%d/%s/%s", i+1, unsupported.Occurrence, unsupported.Field), Class: "other-unique-identifiers", Reason: unsupported.Code, Resolved: false})
		}
		return nil, blockedAttempt(stage, review, findings, exportreview.Scan{Status: "not-run", Locations: []string{}, Limitations: "Unsupported diagnosis locations block export."})
	}
	specBytes, err := encode(spec)
	if err != nil {
		return nil, err
	}
	targetBytes, err := encode(fixtureTarget("127.0.0.1:2575"))
	if err != nil {
		return nil, err
	}
	for _, file := range []struct {
		name string
		raw  []byte
	}{{"spec.json", specBytes}, {"target.json", targetBytes}, {"RERUN.md", []byte(rerunInstructions)}} {
		if err := writeFile(stage, file.name, file.raw); err != nil {
			return nil, err
		}
	}
	files, err := tree(stage)
	if err != nil {
		return nil, err
	}
	for name := range files {
		if !exportFile(name) {
			return nil, errors.New("unreviewed generated packet file")
		}
	}
	residual := exportreview.Residual(files, local.ResidualValues)
	if residual.Status != "passed" {
		return nil, blockedAttempt(stage, review, residualFindings(residual), residual)
	}
	manifest := &ExportManifest{Schema: ExportSchema, State: "complete", DataOrigin: "derived-testing-data", ApprovedReview: review.Identity, Review: *review, Proof: proof, Residual: residual, Files: []File{}, Scope: exportreview.Scope + " Proof applies only to fresh built-in readmit-siu-v1 defective/fixed fixtures and the declared appointment-ledger boundary; it establishes no production target behavior or readiness to accept patient data."}
	manifest.Residual.Files = len(files) + 2 // Final scan also includes manifest and completion marker.
	for _, name := range fileNames(files) {
		manifest.Files = append(manifest.Files, File{Path: name, Size: len(files[name]), SHA256: digest(files[name])})
	}
	raw, err := encode(manifest)
	if err != nil || len(raw) > maxReviewBytes {
		return nil, errors.New("export manifest exceeds limit")
	}
	files["export-review.json"] = raw
	// The final scan includes the full public manifest, nested proof runs,
	// generated observations, diagnosis, every spec, and every filename.
	if scan := exportreview.Residual(files, local.ResidualValues); scan.Status != "passed" {
		return nil, blockedAttempt(stage, review, residualFindings(scan), scan)
	}
	files["identity.sha256"] = []byte(identity(ExportSchema, files) + "\n")
	if scan := exportreview.Residual(files, local.ResidualValues); scan.Status != "passed" {
		return nil, blockedAttempt(stage, review, residualFindings(scan), scan)
	}
	if err := revalidate(local); err != nil {
		return nil, err
	}
	current, err := OpenReview(request.ReviewPath)
	if err != nil || current.Identity != review.Identity {
		return nil, errors.New("approved review changed during proof")
	}
	if err := publish(output, files); err != nil {
		return nil, err
	}
	return OpenExport(output)
}

func derivedInputs(derived *bundle.Bundle) ([]bundle.Input, error) {
	inputs := make([]bundle.Input, len(derived.Manifest.Sources))
	for i, source := range derived.Manifest.Sources {
		input := bundle.Input{Options: hl7.Options{Format: source.Format, Terminator: source.Terminator}, Observations: map[int]bundle.Observation{}}
		for _, event := range derived.Events {
			if event.SourceID != source.ID {
				continue
			}
			raw, err := derived.Raw(event.ID)
			if err != nil {
				return nil, err
			}
			input.Data = append(input.Data, raw...)
			input.Observations[event.Sequence] = bundle.Observation{Direction: event.Direction}
		}
		inputs[i] = input
	}
	return inputs, nil
}

func exportFile(name string) bool {
	if slices.Contains([]string{"spec.json", "target.json", "diagnosis.json", "diagnosis.md", "RERUN.md"}, name) {
		return true
	}
	if strings.HasPrefix(name, "case/") {
		return true
	} // Already validated by bundle.Open.
	for _, mode := range []string{"baseline", "postfix"} {
		prefix := "proof/" + mode + "/"
		if !strings.HasPrefix(name, prefix) {
			continue
		}
		rest := strings.TrimPrefix(name, prefix)
		if slices.Contains([]string{"spec.json", "target.json", "observation.json"}, rest) || strings.HasPrefix(rest, "result/") || strings.HasPrefix(rest, "receiver.case/") {
			return true
		}
	}
	return false
}

func publish(output string, files map[string][]byte) error {
	total := 0
	for _, raw := range files {
		total += len(raw)
		if len(raw) > maxReviewBytes || total > maxPacketBytes {
			return errors.New("export exceeds byte limit")
		}
	}
	if len(files) > maxPacketFiles {
		return errors.New("export exceeds file limit")
	}
	parent, root, err := artifactdir.Reserve(output)
	if err != nil {
		return errors.New("cannot create export destination")
	}
	defer parent.Close()
	defer root.Close()
	for _, name := range fileNames(files) {
		if name == "identity.sha256" {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(filepath.Join(output, filepath.FromSlash(name))), 0700); err != nil {
			return errors.New("cannot create export subdirectory")
		}
		if err := writeFile(output, name, files[name]); err != nil {
			return err
		}
	}
	if err := writeFile(output, "identity.sha256", files["identity.sha256"]); err != nil {
		return err
	}
	// Every directory of the packet, the packet and its entry in the folder
	// holding it are synced before the export is reported. Every file is by
	// then, so a failure leaves a packet that may open and says so.
	if artifactdir.SyncEntries(root, parent, artifactdir.Directories(files)) != nil {
		return errors.New("cannot sync export packet; the packet was written in full but a power loss could still lose it")
	}
	return nil
}

const rerunInstructions = `# Derived fixture reproducer

This packet contains transformed testing data. It is separate from synthetic
public demonstrations. Review approval and local execution establish no legal
status or readiness to accept patient data. The proof covers only the built-in
readmit-siu-v1 appointment ledger; ACK acceptance alone is not workflow success.

Keep this sealed packet unchanged. In the operating system's file manager,
create a separate writable folder outside this packet. Copy only case/, spec.json,
and target.json into that folder; do not copy the packet's root identity.sha256.
The copied case remains immutable. Run the following commands from that working
folder. No build tools or scripts are required.

Start a fresh receiver in a separate terminal:

    readmit listen --address 127.0.0.1:2575 --mode defective --output NEW_BASELINE_RECEIVER --observation observation.json --max-messages 2

Wait for Listening, then run:

    readmit test spec.json --send --output NEW_BASELINE

The exact failed assertion positions are listed in the packet's export-review.json.
After the listener exits, rename observation.json to baseline-observation.json in
the working folder using the file manager. Then start a fresh receiver:

    readmit listen --address 127.0.0.1:2575 --mode fixed --output NEW_FIXED_RECEIVER --observation observation.json --max-messages 2

Wait for Listening, then run:

    readmit test spec.json --send --output NEW_POSTFIX

Every assertion must pass. Each startup must
have an empty ledger and processed list. Never reuse an observation snapshot.
Use new output names every time. No reset instructions are executed as code.

The baseline and fixed proof results are under proof/baseline/result and
proof/postfix/result. Their inputs match the derived case; the target changed
between two fresh fixture sessions. Original source artifacts, original proof,
mapping tables, date offsets, and source paths are kept outside this packet.
Known-value scans are one bounded check, not proof that other identifiers or
inferences are absent. See the coverage and uncovered categories in the manifest.
`
