package redact

import (
	"encoding/json/v2"
	"errors"
	"path/filepath"
	"slices"

	"github.com/bharm16/readmit/internal/bundle"
	"github.com/bharm16/readmit/internal/diagnose"
	"github.com/bharm16/readmit/internal/observation"
	"github.com/bharm16/readmit/internal/testrunner"
)

// OpenExport verifies the generated packet's inventory, complete identity, case,
// assertion proofs, and regenerated diagnosis without opening original sources.
// It cannot independently repeat the private known-value scan or confer status.
func OpenExport(path string) (*ExportManifest, error) {
	files, err := tree(path)
	if err != nil {
		return nil, err
	}
	var manifest ExportManifest
	if json.Unmarshal(files["export-review.json"], &manifest, json.RejectUnknownMembers(true)) != nil || manifest.Schema != ExportSchema || manifest.State != "complete" || manifest.DataOrigin != "derived-testing-data" || manifest.ApprovedReview == "" || manifest.Review.State != "ready-for-approval" || hasUnresolved(manifest.Review.Findings) || manifest.Residual.Status != "passed" || manifest.Review.Residual.Status != "passed" {
		return nil, errors.New("invalid completed derived export")
	}
	if string(files["identity.sha256"]) != identity(ExportSchema, files)+"\n" || len(files) != len(manifest.Files)+2 {
		return nil, errors.New("export identity or file inventory changed")
	}
	reviewBytes, err := encode(manifest.Review)
	if err != nil {
		return nil, err
	}
	reviewFiles := map[string][]byte{"review.json": reviewBytes, "spec.json": files["spec.json"]}
	for name, raw := range files {
		if len(name) > 5 && name[:5] == "case/" {
			reviewFiles[name] = raw
		}
	}
	if identity(ReviewSchema, reviewFiles) != manifest.ApprovedReview {
		return nil, errors.New("export does not carry the exact approved review")
	}
	if manifest.Proof.Profile != "readmit-siu-v1" || manifest.Proof.Boundary != testrunner.LedgerBoundary || manifest.Proof.BaselineStatus != testrunner.AssertionFailure || manifest.Proof.PostfixStatus != testrunner.Pass || !slices.Equal(manifest.Proof.FailedAssertions, manifest.Review.RequiredFailures) || !slices.Equal(manifest.Review.OriginalFailedAssertions, manifest.Review.RequiredFailures) {
		return nil, errors.New("export proof claims disagree with approval")
	}
	seen := map[string]bool{}
	for _, file := range manifest.Files {
		raw, exists := files[file.Path]
		if !exists || seen[file.Path] || !exportFile(file.Path) || len(raw) != file.Size || digest(raw) != file.SHA256 {
			return nil, errors.New("export file disagrees with reviewed inventory")
		}
		seen[file.Path] = true
	}
	derived, err := bundle.Open(filepath.Join(path, "case"))
	if err != nil || derived.Identity != manifest.Review.DerivedIdentity || derived.Manifest.Provenance.Mode != bundle.Derived {
		return nil, errors.New("export case disagrees with derived review")
	}
	spec, err := testrunner.DecodeSpec(files["spec.json"])
	if err != nil || digest(files["spec.json"]) != manifest.Review.DerivedSpecSHA256 {
		return nil, errors.New("export spec disagrees with review")
	}
	targetBytes, err := encode(fixtureTarget("127.0.0.1:2575"))
	if err != nil || string(files["target.json"]) != string(targetBytes) || string(files["RERUN.md"]) != rerunInstructions {
		return nil, errors.New("export rerun material was not generated by the fixture workflow")
	}
	for _, mode := range []string{"baseline", "postfix"} {
		result, err := testrunner.Open(filepath.Join(path, "proof", mode, "result"))
		if err != nil {
			return nil, err
		}
		if !sameAssertionContract(&spec, result.Spec) || result.Result.InputBundleIdentity != derived.Identity {
			return nil, errors.New("export proof changed the derived assertions or case")
		}
		if result.Run == nil || !result.Run.Successful() || result.FinalObservation == nil || result.Result.Target == nil {
			return nil, errors.New("export fixture proof is incomplete")
		}
		expectedMode := observation.Defective
		if mode == "postfix" {
			expectedMode = observation.Fixed
		}
		if result.Result.ReceiverMode != expectedMode {
			return nil, errors.New("export fixture mode disagrees")
		}
		prefix := "proof/" + mode + "/"
		expectedSpec := spec
		expectedSpec.Input.Case = "../../case"
		proofSpecBytes, err := encode(expectedSpec)
		if err != nil || string(files[prefix+"spec.json"]) != string(proofSpecBytes) || string(files[prefix+"result/spec.json"]) != string(proofSpecBytes) {
			return nil, errors.New("export proof retained unreviewed spec metadata")
		}
		proofTargetBytes, err := encode(fixtureTarget(result.Result.Target.Address))
		if err != nil || string(files[prefix+"target.json"]) != string(proofTargetBytes) {
			return nil, errors.New("export target config disagrees with new execution")
		}
		snapshotBytes, err := observation.Encode(*result.FinalObservation)
		if err != nil || string(files[prefix+"observation.json"]) != string(snapshotBytes) {
			return nil, errors.New("export observation disagrees with verified result")
		}
		if mode == "baseline" && (result.Identity != manifest.Proof.BaselineIdentity || result.Result.Status != testrunner.AssertionFailure || !slices.Equal(failedAssertions(result), manifest.Review.RequiredFailures)) || mode == "postfix" && (result.Identity != manifest.Proof.PostfixIdentity || result.Result.Status != testrunner.Pass) {
			return nil, errors.New("export proof verdicts disagree")
		}
		received, err := bundle.Open(filepath.Join(path, "proof", mode, "receiver.case"))
		if err != nil {
			return nil, err
		}
		if received.Observation == nil {
			return nil, errors.New("new receiver case lacks observation")
		}
		receivedSnapshot, err := observation.Encode(*received.Observation)
		if err != nil || string(receivedSnapshot) != string(snapshotBytes) {
			return nil, errors.New("new receiver case and result disagree")
		}
	}
	report, err := diagnose.Run(filepath.Join(path, "case"), diagnose.DefaultConfig())
	if err != nil || len(report.Unsupported) > 0 {
		return nil, errors.New("export diagnosis has unresolved coverage")
	}
	reportJSON, err := diagnose.JSON(report)
	if err != nil || string(reportJSON) != string(files["diagnosis.json"]) || string(diagnose.Markdown(report)) != string(files["diagnosis.md"]) {
		return nil, errors.New("export diagnosis was not regenerated from derived case")
	}
	return &manifest, nil
}
