"""Run one disjoint shard of the complete race suite and full connected lab tests.

Go discovers the tests using the same build tags and instrumentation as their
execution. Names, rather than packages, are partitioned so a growing lifecycle
package cannot serialize the whole gate. Identical names in different packages
belong to the same shard. Each selected (package, test) must finish, including
an explicit skip, or the command fails even if Go returned success.
"""

import argparse
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys


RACE = ['-race', '-short', '-tags', 'readmit_nosync']
PACKAGES = ['./internal/connectedrun', './tests', './internal/desktop', './...']
LAB = ['-tags', 'readmit_nosync']
LAB_PACKAGES = ['./internal/connectedrun', './internal/report']
LAB_PATTERN = '^(TestFHIRFlow|TestConnectedRetainedProof|TestConnectedExtractMaps|TestConnectedLab)'


def make_commands(*targets):
    result = subprocess.run(['make', '--no-print-directory', '-n', *targets],
                            text=True, stdout=subprocess.PIPE, check=True)
    commands = []
    for line in result.stdout.splitlines():
        parts = shlex.split(line)
        if not parts:
            continue
        if Path(parts[0]).name in ('make', 'gmake'):
            parts[0] = 'make'
        if parts[0] == 'CGO_ENABLED=1':
            parts = parts[1:]
        commands.append(parts)
    return commands


def validate_make_plan():
    # The Makefile remains the coverage contract. Refuse new/revised commands
    # until the shard plan handles them; never silently narrow automatic CI.
    expected = ([['go', 'test', *RACE, *PACKAGES], ['make', 'test-boundary']]
                + make_commands('test-boundary')
                + [['make', 'test-corpus']] + make_commands('test-corpus')
                + [['make', 'test-fhir-lab'], ['go', 'test', *LAB, *LAB_PACKAGES, '-run', LAB_PATTERN]])
    if make_commands('test') != expected:
        raise RuntimeError('make test coverage changed; update the CI shard plan before running it')


def json_objects(text):
    decoder = json.JSONDecoder()
    position = 0
    while position < len(text):
        if text[position].isspace():
            position += 1
            continue
        value, position = decoder.raw_decode(text, position)
        yield value


def generated_inventory(package):
    """Read the pinned Go toolchain's own generated test registries, fail closed."""
    paths = package.get('GoFiles', [])
    if len(paths) != 1:
        raise RuntimeError('unrecognized Go test-main file inventory')
    source = (Path(package['Dir']) / paths[0]).read_text()
    if "// Code generated by 'go test'. DO NOT EDIT." not in source:
        raise RuntimeError('unrecognized generated Go test main')
    imports = re.findall(r'^\s*testdeps.ImportPath = ("[^"\n]+")$', source, re.M)
    if len(imports) != 1 or json.loads(imports[0]) + '.test' != package['ImportPath']:
        raise RuntimeError('generated Go test-main package identity differs')
    name = json.loads(imports[0])
    found = set()
    for variable, kind, prefix in [('tests', 'Test', 'Test'),
                                   ('fuzzTargets', 'FuzzTarget', 'Fuzz'),
                                   ('examples', 'Example', 'Example')]:
        blocks = re.findall(r'^var ' + variable + r' = \[\]testing\.Internal' + kind
                            + r'\{\n(.*?)^\}', source, re.M | re.S)
        if len(blocks) != 1:
            raise RuntimeError('unrecognized generated Go registry: ' + variable)
        # Example output is a Go quoted string (including \\xNN), not JSON.
        tail = r', "(?:[^"\\]|\\.)*", (?:true|false)' if kind == 'Example' else ''
        row = re.compile(r'\s*\{"(' + prefix + r'\w*)", (?:_test|_xtest)\.(\w+)' + tail + r'\},')
        if row.sub('', blocks[0]).strip():
            raise RuntimeError('unrecognized generated Go registry row: ' + variable)
        for label, function in row.findall(blocks[0]):
            if label != function:
                raise RuntimeError('generated Go test name differs from its function')
            found.add((name, label))
    return name, found


def discover(flags, packages, pattern):
    # go list generates exactly the driver that go test compiles, including
    # build constraints and runnable examples, without compiling first. Keeping
    # compilation in execution avoids a full-suite compilation barrier.
    command = ['go', 'list', '-test', '-json', *[flag for flag in flags if flag != '-short'], *packages]
    print(shlex.join(command), flush=True)
    result = subprocess.run(command, text=True, stdout=subprocess.PIPE, check=True)
    inventory, expected, generated = set(), set(), set()
    source_packages = []
    for package in json_objects(result.stdout):
        is_driver = package.get('Name') == 'main' and 'testing/internal/testdeps' in package.get('Imports', [])
        if not package.get('ForTest') and not is_driver:
            source_packages.append(package['ImportPath'])
        if not package.get('ForTest') and (package.get('TestGoFiles') or package.get('XTestGoFiles')):
            expected.add(package['ImportPath'])
        if is_driver:
            name, entries = generated_inventory(package)
            if name in generated:
                raise RuntimeError('duplicate generated test main: ' + name)
            generated.add(name)
            inventory.update(entries)
    if expected != generated:
        raise RuntimeError('Go test-main inventory differs from packages with test files')
    inventory = {(package, name) for package, name in inventory if re.search(pattern, name)}
    if not inventory:
        raise RuntimeError('Go discovered no tests; refusing an empty gate')
    return inventory, source_packages


def run_mode(flags, packages, pattern, shard, shards):
    inventory, source_packages = discover(flags, packages, pattern)
    names = sorted({name for _, name in inventory})[shard - 1::shards]
    selected = {(package, name) for package, name in inventory if name in names}
    print(f'Shard {shard}/{shards}: {len(selected)} of {len(inventory)} tests, examples and fuzz targets', flush=True)
    if not selected:
        return
    selection = '^(' + '|'.join(re.escape(name) for name in names) + ')$'
    # Keep the deadline-sensitive lifecycle package clear of competing tests
    # and compilers. The remaining race packages can use normal build/test
    # parallelism; limiting all of them serialized their short test processes.
    lifecycle = [p for p in source_packages if p.endswith('/internal/connectedrun')]
    groups = [source_packages]
    if '-race' in flags and lifecycle:
        groups = [lifecycle, [p for p in source_packages if p not in lifecycle]]
    completed = set()
    for group in groups:
        if not group:
            continue
        workers = '4' if '-race' in flags else '2'
        # Fresh test execution avoids hashing the large file-access logs for
        # result caching. Compiler/build caching remains enabled.
        command = ['go', 'test', *flags, '-count=1', '-p', workers, '-parallel', '2', '-json', '-run', selection, *group]
        with subprocess.Popen(command, stdout=subprocess.PIPE, text=True) as process:
            for line in process.stdout:
                event = json.loads(line)
                if event.get('Output') and event.get('OutputType') != 'frame':
                    print(event['Output'], end='', flush=True)
                if event.get('Test') and event['Action'] in ('pass', 'fail', 'skip'):
                    completed.add((event['Package'], event['Test']))
                if event['Action'] == 'fail':
                    name = event['Package'] + ('/' + event['Test'] if event.get('Test') else '')
                    print(f'FAIL: {name} ({event.get("Elapsed", 0)}s)', flush=True)
            if process.wait() != 0:
                raise subprocess.CalledProcessError(process.returncode, ['go', 'test', *flags])
    missing = selected - completed
    if missing:
        raise RuntimeError('selected tests did not finish: ' + ', '.join(f'{p}:{n}' for p, n in sorted(missing)))
    print(f'Shard {shard}/{shards}: verified completion of all {len(selected)} selected tests', flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--shard', type=int, required=True)
    parser.add_argument('--shards', type=int, required=True)
    args = parser.parse_args()
    if not 1 <= args.shard <= args.shards:
        parser.error('shard must be between 1 and shards')
    validate_make_plan()
    os.environ['CGO_ENABLED'] = '1'
    run_mode(RACE, PACKAGES, '^(Test|Fuzz|Example)', args.shard, args.shards)
    if args.shard == 1:
        subprocess.run(['make', 'test-boundary', 'test-corpus'], check=True)
    run_mode(LAB, LAB_PACKAGES, LAB_PATTERN, args.shard, args.shards)
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (RuntimeError, subprocess.CalledProcessError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
