"""Exercise the sharded test gate through its Go command boundary."""

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


TOOL = Path(__file__).with_name("ci_tests.py")


class ShardedTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.calls = self.root / "calls.jsonl"
        self.inventory = {
            "race": {"example/a": ["TestAlpha", "TestBeta", "FuzzDecode", "ExampleRead"],
                     "example/b": ["TestAlpha", "TestGamma", "TestNewlyAdded"]},
            "lab": {"example/a": ["TestFHIRFlowAlpha", "TestFHIRFlowBeta"],
                    "example/b": ["TestConnectedLabGamma", "TestConnectedRetainedProof"]},
        }
        fake = self.root / "go"
        fake.write_text(f"#!{sys.executable}\n" + '''
import json, os, re, sys
from pathlib import Path
args = sys.argv[1:]
with open(os.environ['CALLS'], 'a') as f:
    f.write(json.dumps(args) + '\\n')
mode = 'race' if '-race' in args else 'lab'
data = json.loads(os.environ['INVENTORY'])[mode]
def event(package, action, **fields):
    print(json.dumps(dict(Package=package, Action=action, **fields)), flush=True)
if args[0] == 'list':
    if os.environ.get('FAIL_DISCOVERY'):
        sys.exit(2)
    for package, names in data.items():
        print(json.dumps({'ImportPath': package, 'TestGoFiles': ['fixture_test.go']}))
        if os.environ.get('MISSING_MAIN') == package:
            continue
        source = "// Code generated by 'go test'. DO NOT EDIT.\\npackage main\\n"
        for variable, kind, prefix in [('tests','Test','Test'),('fuzzTargets','FuzzTarget','Fuzz'),('examples','Example','Example')]:
            source += 'var '+variable+' = []testing.Internal'+kind+'{\\n'
            for name in names:
                if name.startswith(prefix):
                    tail = ', "value", false' if kind == 'Example' else ''
                    source += '{"'+name+'", _test.'+name+tail+'},\\n'
            if os.environ.get('BAD_REGISTRY') and variable == 'tests':
                source += 'unexpected new entry format\\n'
            source += '}\\n'
        source += 'func init() {\\n testdeps.ImportPath = "'+package+'"\\n}\\n'
        file = Path(os.environ['CALLS']).with_name(mode+'-'+package.replace('/','_')+'.go')
        file.write_text(source)
        print(json.dumps({'Name':'main', 'ImportPath':package+'.test', 'Dir':str(file.parent),
                          'GoFiles':[str(file)], 'Imports':['testing/internal/testdeps']}))
    sys.exit(0)
pattern = args[args.index('-run') + 1]
failed = False
for package, names in data.items():
    if package not in args:
        continue
    for name in names:
        if not re.search(pattern, name) or name == os.environ.get('OMIT'):
            continue
        action = 'fail' if name == os.environ.get('FAIL_TEST') else 'pass'
        failed |= action == 'fail'
        event(package, action, Test=name, Elapsed=0.01)
        # Subtests and fuzz seeds do not count as independent assignments.
        event(package, 'pass', Test=name+'/child', Elapsed=0.01)
sys.exit(1 if failed else 0)
''')
        fake.chmod(0o755)
        make = self.root / "make"
        make.write_text(f"#!{sys.executable}\n" + '''
import json, os, sys
args = sys.argv[1:]
with open(os.environ['CALLS'], 'a') as f:
    f.write(json.dumps(args)+'\\n')
if '-n' in args:
    if args[-1] == 'test':
        print('CGO_ENABLED=1 go test -race -short -tags readmit_nosync ./internal/connectedrun ./tests ./internal/desktop ./...')
        print('/usr/bin/make test-boundary')
    if args[-1] in ('test', 'test-boundary'):
        print('go test ./receiver -run production-limit')
    if args[-1] == 'test':
        print('/usr/bin/make test-corpus')
    if args[-1] in ('test', 'test-corpus'):
        print('go test ./importer -run production-stream')
    if args[-1] == 'test':
        print('/usr/bin/make test-fhir-lab')
        print("go test -tags readmit_nosync ./internal/connectedrun ./internal/report -run '^(TestFHIRFlow|TestConnectedRetainedProof|TestConnectedExtractMaps|TestConnectedLab)'")
        if os.environ.get('CHANGED_PLAN'):
            print('make test-extra' if os.environ['CHANGED_PLAN'] == 'literal' else 'go test ./new-required-coverage')
    sys.exit(0)
sys.exit(int(os.environ.get('FAIL_BOUNDARY', '0')))
''')
        make.chmod(0o755)
        self.env = dict(os.environ, PATH=str(self.root)+os.pathsep+os.environ["PATH"],
                        CALLS=str(self.calls), INVENTORY=json.dumps(self.inventory))

    def run_shard(self, shard, **env):
        return subprocess.run([sys.executable, str(TOOL), '--shard', str(shard), '--shards', '4'],
                              cwd=self.root, env=dict(self.env, **env), capture_output=True, text=True)

    def test_every_test_example_and_fuzz_seed_runs_once_per_mode(self):
        import re
        observed = {mode: [] for mode in self.inventory}
        for shard in range(1, 5):
            self.calls.write_text('')
            result = self.run_shard(shard)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            for args in map(json.loads, self.calls.read_text().splitlines()):
                if '-run' not in args:
                    continue
                mode = 'race' if '-race' in args else 'lab'
                pattern = args[args.index('-run')+1]
                self.assertIn('readmit_nosync', args)
                self.assertEqual('-short' in args, mode == 'race')
                for package, names in self.inventory[mode].items():
                    observed[mode].extend((package, name) for name in names if package in args and re.search(pattern, name))
        for mode, packages in self.inventory.items():
            expected = [(package, name) for package, names in packages.items() for name in names]
            self.assertCountEqual(observed[mode], expected)

    def test_lifecycle_is_isolated_without_losing_other_packages(self):
        inventory = dict(self.inventory)
        inventory['race'] = {'example/internal/connectedrun': ['TestAlpha'], 'example/b': ['TestBeta']}
        result = self.run_shard(1, INVENTORY=json.dumps(inventory))
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        calls = [args for args in map(json.loads, self.calls.read_text().splitlines())
                 if '-run' in args and '-race' in args]
        self.assertEqual(len(calls), 2)
        self.assertIn('example/internal/connectedrun', calls[0])
        self.assertNotIn('example/b', calls[0])
        self.assertIn('example/b', calls[1])
        self.assertNotIn('example/internal/connectedrun', calls[1])

    def test_discovery_failure_cannot_be_a_green_shard(self):
        result = self.run_shard(1, FAIL_DISCOVERY='1')
        self.assertNotEqual(result.returncode, 0)

    def test_failing_selected_test_fails_its_shard(self):
        results = [self.run_shard(shard, FAIL_TEST='TestAlpha') for shard in range(1, 5)]
        self.assertEqual(sum(result.returncode != 0 for result in results), 1)
        failed = next(result for result in results if result.returncode)
        self.assertIn('FAIL: example/a/TestAlpha', failed.stdout)

    def test_missing_execution_is_refused_even_when_go_exits_successfully(self):
        results = [self.run_shard(shard, OMIT='TestAlpha') for shard in range(1, 5)]
        self.assertEqual(sum(result.returncode != 0 for result in results), 1)
        self.assertTrue(any('did not finish' in r.stderr for r in results))

    def test_missing_driver_and_unknown_registry_rows_fail_closed(self):
        for env in ({'MISSING_MAIN': 'example/b'}, {'BAD_REGISTRY': 'yes'}):
            with self.subTest(env=env):
                self.assertNotEqual(self.run_shard(1, **env).returncode, 0)

    def test_empty_discovery_is_refused(self):
        result = self.run_shard(1, INVENTORY=json.dumps({'race': {}, 'lab': {}}))
        self.assertNotEqual(result.returncode, 0)

    def test_production_boundaries_run_once_and_fail_the_gate(self):
        for shard in range(1, 5):
            self.assertEqual(self.run_shard(shard).returncode, 0)
        calls = list(map(json.loads, self.calls.read_text().splitlines()))
        self.assertEqual(calls.count(['test-boundary', 'test-corpus']), 1)
        self.assertNotEqual(self.run_shard(1, FAIL_BOUNDARY='1').returncode, 0)

    def test_new_make_coverage_cannot_be_silently_omitted(self):
        for change in ('yes', 'literal'):
            with self.subTest(change=change):
                result = self.run_shard(1, CHANGED_PLAN=change)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn('make test coverage changed', result.stderr)

    def test_invalid_shard_is_refused(self):
        self.assertNotEqual(self.run_shard(0).returncode, 0)
        self.assertNotEqual(self.run_shard(5).returncode, 0)


class RealGoInventory(unittest.TestCase):
    def test_real_go_runs_examples_fuzz_seeds_subtests_and_reports_failure(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / 'go.mod').write_text('module shardfixture\n\ngo 1.23.0\n')
            (root / 'fixture_test.go').write_text('''package shardfixture
import ("fmt"; "os"; "testing")
func TestAlpha(t *testing.T) { t.Run("child", func(t *testing.T) {}) }
func TestBeta(t *testing.T) { if os.Getenv("SHARD_FAIL") == "yes" { t.Fatal("deliberate failure") } }
func TestSkipped(t *testing.T) { t.Skip("explicit skip is observed") }
func FuzzDecode(f *testing.F) { f.Add("seed"); f.Fuzz(func(t *testing.T, s string) {}) }
func Example() { fmt.Println("value")
// Output: value
}
func Example_noOutput() { panic("must never run") }
func Example_empty() {
// Output:
}
func Example_escaped() { fmt.Print("\\x7f")
// Output: \x7f
}
''')
            (root / 'external_test.go').write_text('''package shardfixture_test
import "testing"
func TestExternal(t *testing.T) {}
func TestÜnicode(t *testing.T) {}
''')
            program = ("import sys; sys.path.insert(0, sys.argv[1]); import ci_tests; "
                       "ci_tests.run_mode(['-race', '-short'], ['./...'], "
                       "'^(Test|Fuzz|Example)', int(sys.argv[2]), 2)")
            env = dict(os.environ, CGO_ENABLED='1', GOWORK='off')
            comparison = ("import json, subprocess, sys; sys.path.insert(0, sys.argv[1]); import ci_tests; "
                          "actual=ci_tests.discover(['-race','-short'], ['./...'], '^(Test|Fuzz|Example)')[0]; "
                          "result=subprocess.run(['go','test','-race','-short','-json','-list','^(Test|Fuzz|Example)','./...'], "
                          "capture_output=True,text=True,check=True); "
                          "events=[json.loads(line) for line in result.stdout.splitlines()]; "
                          "expected={(e['Package'],e['Output'].strip()) for e in events "
                          "if e.get('Action')=='output' and ci_tests.re.fullmatch(r'(Test|Fuzz|Example)\\w*',e.get('Output','').strip())}; "
                          "assert actual==expected, (actual,expected)")
            result = subprocess.run([sys.executable, '-c', comparison, str(TOOL.parent)],
                                    cwd=root, env=env, capture_output=True, text=True)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            outputs = []
            for shard in (1, 2):
                result = subprocess.run([sys.executable, '-c', program, str(TOOL.parent), str(shard)],
                                        cwd=root, env=env, capture_output=True, text=True)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                outputs.append(result.stdout)
            self.assertIn('verified completion of all 5 selected tests', outputs[0])
            self.assertIn('verified completion of all 4 selected tests', outputs[1])
            # TestBeta belongs to shard 2 in this real inventory.
            result = subprocess.run([sys.executable, '-c', program, str(TOOL.parent), '2'],
                                    cwd=root, env=dict(env, SHARD_FAIL='yes'), capture_output=True, text=True)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn('deliberate failure', result.stdout)
            # go list can discover tests without compiling unrelated packages.
            # Execution must still catch a build failure in a package with none.
            (root / 'broken').mkdir()
            (root / 'broken' / 'broken.go').write_text('package broken\nvar Value = undefinedName\n')
            result = subprocess.run([sys.executable, '-c', program, str(TOOL.parent), '1'],
                                    cwd=root, env=env, capture_output=True, text=True)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn('undefinedName', result.stdout + result.stderr)


if __name__ == '__main__':
    unittest.main()
