package desktop

import (
	"bytes"
	"cmp"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json/v2"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/bharm16/readmit/internal/artifactpath"
	"github.com/bharm16/readmit/internal/catalog"
	"github.com/bharm16/readmit/internal/hl7"
	"github.com/bharm16/readmit/internal/hubprotocol"
	"github.com/bharm16/readmit/internal/operation"
	"github.com/bharm16/readmit/internal/protect"
	"github.com/bharm16/readmit/internal/redact"
	"github.com/bharm16/readmit/internal/report"
	"github.com/bharm16/readmit/internal/reportshare"
)

// Sharing a report (#560) is one started flow over one report version:
// Contents (what the share holds, enumerated by the backend), Redaction
// (the named template and this draft's own treatments, with every value the
// share restates derived or left unresolved) and Preview (the exact
// generated output). The final Export or Send is a reviewed action: its
// token binds the generated bytes, the source versions, the contents, the
// template, the treatments, the reviewer, the destination, the format and
// the encryption control's key generation, so any change withdraws it and
// needs a fresh click on a fresh preview. A local Export never uploads; a
// Send reaches a signed-in team project only, once.

const (
	// ShareReportAction exports one report's share to a new local file,
	// folder or encrypted package.
	ShareReportAction ActionID = "report.share"
	// SendReportAction sends one report's redacted share to a team project
	// of the signed-in customer hub.
	SendReportAction ActionID = "report.send"
)

// ShareContents are what a share holds beside its report, and the items
// taken out of this share only.
type ShareContents struct {
	Messages    bool     `json:"messages,omitzero"`
	Attachments bool     `json:"attachments,omitzero"`
	Original    bool     `json:"original,omitzero"`
	Removed     []string `json:"removed,omitzero"`
}

// ShareEncryption is the encryption control a share's package is written
// under, at the key generation it was chosen at.
type ShareEncryption struct {
	Entry      string `json:"entry"`
	Control    string `json:"control"`
	Generation int    `json:"generation"`
}

// ReportShareOptions are one share draft. Template names a disclosure
// template of the project, or none. Destination is a place chosen through
// ChooseShareDestination, for an Export; Project is the team project a Send
// reaches. Reveal shows, in the review, examples of the original values the
// redaction rows changed; it changes nothing the output holds.
type ReportShareOptions struct {
	Contents    ShareContents         `json:"contents"`
	Template    string                `json:"template,omitzero"`
	Overrides   reportshare.Overrides `json:"overrides"`
	Format      string                `json:"format"`
	Paper       string                `json:"paper,omitzero"`
	Destination string                `json:"destination,omitzero"`
	Project     string                `json:"project,omitzero"`
	Encrypt     *ShareEncryption      `json:"encrypt,omitzero"`
	Reveal      bool                  `json:"reveal,omitzero"`
}

// ShareFile is one generated file of the output, with its exact content for
// the preview: Text for a text format, Data (base64) for a PDF or an
// attachment that is not text.
type ShareFile struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
	Size int    `json:"size"`
	Text string `json:"text,omitzero"`
	Data string `json:"data,omitzero"`
}

// Share output types.
const (
	ShareOutputFile    = "file"
	ShareOutputFolder  = "folder"
	ShareOutputPackage = "encrypted-package"
)

// ShareOutput is what the final action writes or sends.
type ShareOutput struct {
	Type   string      `json:"type"`
	Format string      `json:"format"`
	Paper  string      `json:"paper,omitzero"`
	Name   string      `json:"name"`
	Size   int         `json:"size"`
	Files  []ShareFile `json:"files"`
	// Original is the size of the original evidence the output holds, which
	// its own exporter writes.
	Original int `json:"original,omitzero"`
}

// ShareDestinationView is where the output goes, as values: a chosen local
// file or folder by name and the folder it is in, or a team project.
type ShareDestinationView struct {
	Kind     string `json:"kind"`
	Name     string `json:"name,omitzero"`
	Location string `json:"location,omitzero"`
	Team     string `json:"team,omitzero"`
	Project  string `json:"project,omitzero"`
}

// ShareEncryptionView is the control a package is written under, as its
// registration declares it.
type ShareEncryptionView struct {
	Control    string `json:"control"`
	Reference  string `json:"reference"`
	Generation int    `json:"generation"`
	Retention  string `json:"retention,omitzero"`
}

// ShareRunCheck is the derived re-execution a template requires before the
// derived messages are shared: whether the actual retained evidence exists.
type ShareRunCheck struct {
	Satisfied bool   `json:"satisfied"`
	Reason    string `json:"reason,omitzero"`
}

// ReportShareReview is one prepared share as the flow shows it.
type ReportShareReview struct {
	Report  string `json:"report"`
	Version string `json:"version,omitzero"`
	// Patient is the field the template identifies a patient by, which a
	// date shift is scoped to.
	Patient      string               `json:"patient,omitzero"`
	Template     string               `json:"template,omitzero"`
	Items        []reportshare.Item   `json:"items"`
	Rows         []reportshare.Row    `json:"rows"`
	Issues       []reportshare.Issue  `json:"issues"`
	Output       ShareOutput          `json:"output"`
	Destination  ShareDestinationView `json:"destination"`
	Encryption   *ShareEncryptionView `json:"encryption,omitzero"`
	RunCheck     *ShareRunCheck       `json:"run_check,omitzero"`
	SourceValues bool                 `json:"source_values"`
	Redacted     bool                 `json:"redacted"`
	Revealed     bool                 `json:"revealed"`
	Consequence  string               `json:"consequence,omitzero"`
	Encrypted    bool                 `json:"encrypted"`
	Templates    []ShareTemplate      `json:"templates"`
	Controls     []ShareControl       `json:"controls"`
	Projects     []string             `json:"projects"`
	Attachments  int                  `json:"attachments"`
}

// ShareTemplate is one disclosure template of the project, by its name.
type ShareTemplate struct {
	Entry string `json:"entry"`
	Name  string `json:"name"`
}

// ShareControl is one active encryption control a package can be written
// under.
type ShareControl struct {
	Entry      string `json:"entry"`
	Control    string `json:"control"`
	Generation int    `json:"generation"`
	Retention  string `json:"retention,omitzero"`
}

// ReportShareOutcome is what the final action did: the file, folder or
// package written, or the team project's resource sent, and the handle the
// window opens or shows it by.
type ReportShareOutcome struct {
	Name     string `json:"name"`
	Output   string `json:"output,omitzero"`
	Project  string `json:"project,omitzero"`
	Resource string `json:"resource,omitzero"`
	// Incomplete says a local write stopped part-way; what was written is
	// named as incomplete and never as an export.
	Incomplete bool `json:"incomplete,omitzero"`
}

// reportShareBinding is what a share writes or sends.
type reportShareBinding struct {
	item      string
	revision  string
	title     string
	options   ReportShareOptions
	share     *reportshare.Share
	packetDir string
	packet    *report.RetainedPacket
	authored  report.Authored
	path      string
	encrypt   *protect.File
	control   string
	gen       int
	team      *teamBinding
	resource  string
	derived   *derivedTest
}

// reportShareFormats are the formats a report is shared as.
var reportShareFormats = []string{"pdf", "html", "markdown", "json", "junit"}

func bindReportShare(a *App, ctx context.Context, request PrepareActionRequest, _ bool) (*boundAction, refusal) {
	if len(request.Items) != 1 || request.Items[0].Kind != ReportItem || request.ReportShare == nil {
		return nil, refusal{Failed, "a share is prepared for one report"}
	}
	options := *request.ReportShare
	format := options.Format
	switch {
	case !slices.Contains(reportShareFormats, format):
		return nil, refusal{Failed, "a report is shared as PDF, HTML, Markdown, JSON or JUnit"}
	case format == "pdf" && options.Paper == string(report.A4):
		format = "pdf-a4"
	case options.Paper != "" && (format != "pdf" || options.Paper != string(report.Letter)):
		return nil, refusal{Failed, "a PDF is shared on Letter or A4 paper"}
	}
	send := request.Action == SendReportAction
	loaded, items, records, declined := a.scoped(ctx, request.Context, request.Items)
	if loaded == nil {
		return nil, declined
	}
	backing, err := loaded.reportBacking(records[0], "")
	if err != nil {
		return nil, refusal{Failed, err.Error()}
	}
	display := &ReportShareReview{Report: backing.authored.Title, Version: backing.revision, Templates: shareTemplates(loaded.root),
		Controls: shareControls(loaded.root), Projects: a.shareProjects()}
	var template *redact.Policy
	templateDigest := ""
	if options.Template != "" {
		data, declined := workspaceDocument(loaded.root, options.Template, privacyDocumentLimit, "the template")
		if declined.state != "" {
			return nil, declined
		}
		policy, err := redact.DecodePolicy(data)
		if err != nil {
			return nil, refusal{Failed, "that template cannot be used: " + err.Error()}
		}
		template, templateDigest, display.Template = &policy, digestOf(data), templateName(options.Template)
		if selector, err := hl7.ParseSelector(policy.Patient.Selector); err == nil {
			display.Patient = reportshare.FieldLabel(selector)
		}
	}
	key, err := shareKey(loaded.root)
	if err != nil {
		return nil, refusal{Failed, "the project's sharing key cannot be read or created"}
	}
	attachments := loaded.reportAttachments(backing)
	display.Attachments = len(attachments)
	if !options.Contents.Attachments {
		attachments = nil
	}
	share, err := reportshare.Build(ctx, reportshare.Request{Packet: backing.packet, Authored: backing.authored, Template: template,
		Overrides: options.Overrides, Key: key, Contents: reportshare.Contents(options.Contents), Attachments: attachments, Format: format})
	if err != nil {
		return nil, refusal{Failed, err.Error()}
	}
	bound := &reportShareBinding{item: records[0].ID, revision: backing.revision, title: share.Document.Title, options: options, share: share,
		packetDir: backing.packetDir, packet: backing.packet, authored: backing.authored}
	// Each list is present when empty: a share with every row resolved has
	// no issues, not an unknown set of them.
	display.Items, display.Rows, display.Issues = nonNil(share.Items), nonNil(share.Rows), nonNil(share.Issues)
	display.SourceValues, display.Redacted, display.Revealed = share.SourceValues, share.Redacted, options.Reveal
	if !options.Reveal {
		for i := range display.Rows {
			display.Rows[i].Examples = nil
		}
	}
	display.Output = shareOutput(share, format, options)
	if share.Original {
		// Original evidence is the retained packet byte for byte: its
		// preview is every file it holds, by path and size.
		var listed strings.Builder
		for _, file := range backing.packet.Manifest.Files {
			display.Output.Original += file.Size
			listed.WriteString(file.Path + " · " + strconv.Itoa(file.Size) + " bytes\n")
		}
		display.Output.Size += display.Output.Original
		display.Output.Files = append(display.Output.Files, ShareFile{Name: "Original evidence", Kind: reportshare.OriginalType, Size: display.Output.Original, Text: listed.String()})
	}
	parts := []string{string(request.Action), loaded.root, loaded.document.Project.ID, a.reviewer(), bound.item, bound.revision, backing.packet.Identity,
		options.Template, templateDigest, canonicalJSON(options.Overrides), canonicalJSON(options.Contents), format, strconv.FormatBool(options.Reveal)}
	for _, file := range share.Files {
		parts = append(parts, file.Name, digestOf(file.Data))
	}
	ready, reason := true, ""
	notReady := func(why string) {
		if ready {
			ready, reason = false, why
		}
	}
	for _, issue := range share.Issues {
		if issue.Blocking {
			notReady(issue.Text)
		}
	}
	if share.RunCheck {
		check := loaded.shareRunCheck(backing, bound)
		display.RunCheck = &check
		if !check.Satisfied {
			notReady(cmp.Or(check.Reason, "run the check the template requires before sharing"))
		} else {
			display.Issues = slices.DeleteFunc(slices.Clone(display.Issues), func(issue reportshare.Issue) bool { return issue.Key == "run-check" })
			display.Output.Type = ShareOutputFolder
			display.Output.Files = append(display.Output.Files, ShareFile{Name: derivedTestName, Kind: "derived-test"})
			parts = append(parts, bound.derived.identity)
		}
	}
	if options.Encrypt != nil {
		view, file, declined := shareEncryption(loaded.root, *options.Encrypt)
		if declined.state != "" {
			notReady(declined.reason)
		} else {
			display.Encryption, display.Encrypted = view, true
			display.Output.Type = ShareOutputPackage
			bound.encrypt, bound.control, bound.gen = &file, options.Encrypt.Control, options.Encrypt.Generation
			parts = append(parts, options.Encrypt.Entry, options.Encrypt.Control, strconv.Itoa(view.Generation), fileDigest(file.Path))
		}
	}
	if display.Output.Type != ShareOutputFile {
		display.Output.Name = strings.TrimSuffix(display.Output.Name, filepath.Ext(display.Output.Name))
	}
	if send {
		display.Destination = ShareDestinationView{Kind: "hub", Project: options.Project}
		team, resource, declined := a.bindShareSend(ctx, share, options, display, notReady)
		if declined.state != "" {
			return nil, declined
		}
		bound.team, bound.resource = team, resource
		if team != nil {
			parts = append(parts, team.project, resource, strings.Join(team.parents, ","), strconv.Itoa(team.head), a.teamBindingParts())
		}
		display.Consequence = "Sends the reviewed " + map[bool]string{true: "package", false: "report"}[display.Output.Type != ShareOutputFile] + " to " + cmp.Or(display.Destination.Team, options.Project) + "."
	} else {
		display.Destination = ShareDestinationView{Kind: "local"}
		place, known := a.shareDestination(options.Destination)
		path := place.path
		switch {
		case options.Destination == "":
			notReady("choose where the output is written")
		case !known || place.name != display.Output.Name || place.folder != (display.Output.Type != ShareOutputFile):
			// A place chosen for another output — another format, a file
			// where a folder is now written — is chosen again.
			notReady("choose where the output is written again")
		default:
			display.Destination.Name, display.Destination.Location = filepath.Base(path), filepath.Base(filepath.Dir(path))
			if _, err := os.Lstat(path); !errors.Is(err, fs.ErrNotExist) {
				notReady("something is already there; choose a new name")
			}
			bound.path = path
			parts = append(parts, path)
		}
		switch {
		case share.SourceValues && display.Output.Type == ShareOutputFile:
			display.Consequence = "Exports a file containing patient data."
		case share.SourceValues:
			display.Consequence = "Exports files containing patient data."
		case display.Output.Type == ShareOutputFile:
			display.Consequence = "Exports the reviewed report to a new local file."
		default:
			display.Consequence = "Exports the reviewed package to a new local folder."
		}
	}
	return &boundAction{action: request.Action, origin: request, reportShare: bound, binding: binding(parts...),
		review: ActionReview{Items: items, Ready: ready, Refusal: reason, ReportShare: display, Destination: ReviewDestination{Name: display.Destination.Project,
			Output: display.Destination.Name}}}, noRefusal
}

// shareOutput is the output a share writes, with every generated file's
// exact content for the preview.
func shareOutput(share *reportshare.Share, format string, options ReportShareOptions) ShareOutput {
	output := ShareOutput{Type: ShareOutputFile, Format: options.Format, Files: []ShareFile{}}
	if options.Format == "pdf" {
		output.Paper = cmp.Or(options.Paper, string(report.Letter))
	}
	if share.Folder() {
		output.Type = ShareOutputFolder
	}
	for _, file := range share.Files {
		view := ShareFile{Name: file.Name, Kind: file.Kind, Size: len(file.Data)}
		pdf := file.Kind == reportshare.ReportType && (format == "pdf" || format == "pdf-a4")
		if pdf || !utf8.Valid(file.Data) {
			view.Data = base64.StdEncoding.EncodeToString(file.Data)
		} else {
			view.Text = string(file.Data)
		}
		output.Size += view.Size
		output.Files = append(output.Files, view)
	}
	output.Name = share.Files[0].Name
	if output.Type == ShareOutputFolder {
		output.Name = strings.TrimSuffix(share.Files[0].Name, filepath.Ext(share.Files[0].Name))
	}
	return output
}

func canonicalJSON(value any) string {
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return ""
	}
	return string(data)
}

// reportAttachments are the attachments of the case the report's current
// run sent, as the project holds them now.
func (c *loadedCatalog) reportAttachments(backing reportBacking) []reportshare.Attachment {
	ref := c.caseByIdentity(backing.packet.Manifest.Current.CaseIdentity)
	if ref == nil {
		return nil
	}
	held, err := c.store.Attachments()
	if err != nil {
		return nil
	}
	out := []reportshare.Attachment{}
	for _, attachment := range held {
		if attachment.Item != ref.ID {
			continue
		}
		data, err := boundedFile(c.store.AttachmentPath(attachment), protect.MaxEntryBytes)
		switch {
		case err != nil:
			out = append(out, reportshare.Attachment{Name: attachment.Name, Unreadable: "its stored copy cannot be read"})
		case digestOf(data) != attachment.SHA256:
			out = append(out, reportshare.Attachment{Name: attachment.Name, Unreadable: "its stored copy changed after it was attached"})
		default:
			out = append(out, reportshare.Attachment{Name: attachment.Name, Data: data})
		}
	}
	return out
}

// shareKeyName is the project's customer-local sharing key: the only link
// between an original value and what a share derived from it. It never
// enters an output, and a project without one gets a new one.
const shareKeyName = "sharing.key"

func shareKey(root string) ([]byte, error) {
	path := filepath.Join(root, catalog.Folder, shareKeyName)
	if _, err := os.Lstat(path); !errors.Is(err, fs.ErrNotExist) {
		data, err := boundedFile(path, 64)
		if err != nil || len(data) != redact.MinDeriverKeyBytes {
			return nil, errors.New("the sharing key is not a key this release reads")
		}
		return data, nil
	}
	key := make([]byte, redact.MinDeriverKeyBytes)
	if _, err := rand.Read(key); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	if err := shellDocument.Create(path, key); err != nil {
		if data, again := boundedFile(path, 64); again == nil && len(data) == redact.MinDeriverKeyBytes {
			return data, nil
		}
		return nil, err
	}
	return key, nil
}

// shareTemplates are the disclosure templates of the project, by name.
func shareTemplates(root string) []ShareTemplate {
	templates := []ShareTemplate{}
	entries, err := os.ReadDir(root)
	if err != nil {
		return templates
	}
	for _, entry := range entries {
		name := entry.Name()
		if !entry.Type().IsRegular() || artifactpath.EntryName(name) != nil {
			continue
		}
		if kind, ok := classify(root, name, false); ok && kind == RedactPolicyArtifact {
			templates = append(templates, ShareTemplate{Entry: name, Name: templateName(name)})
		}
	}
	slices.SortFunc(templates, func(x, y ShareTemplate) int { return strings.Compare(strings.ToLower(x.Name), strings.ToLower(y.Name)) })
	return templates
}

// templateName is a template's entry as its name.
func templateName(entry string) string {
	return strings.TrimSuffix(entry, filepath.Ext(entry))
}

// shareControls are the active encryption controls of the project.
func shareControls(root string) []ShareControl {
	controls := []ShareControl{}
	entries, err := os.ReadDir(root)
	if err != nil {
		return controls
	}
	for _, entry := range entries {
		name := entry.Name()
		if !entry.Type().IsRegular() || artifactpath.EntryName(name) != nil {
			continue
		}
		if kind, ok := classify(root, name, false); !ok || kind != ProtectionArtifact {
			continue
		}
		_, file, declined := protectionEntryFile(root, name)
		if declined.state != "" {
			continue
		}
		document, err := file.Read()
		if err != nil {
			continue
		}
		for _, control := range document.Controls {
			if control.State == protect.Active {
				controls = append(controls, ShareControl{Entry: name, Control: control.Name, Generation: control.Generation, Retention: control.Retain})
			}
		}
	}
	return controls
}

// shareEncryption reads the control a package is to be written under: it
// must be active and still at the generation chosen.
func shareEncryption(root string, options ShareEncryption) (*ShareEncryptionView, protect.File, refusal) {
	_, file, declined := protectionEntryFile(root, options.Entry)
	if declined.state != "" {
		return nil, file, declined
	}
	document, err := file.Read()
	if err != nil {
		return nil, file, refusal{Failed, "the encryption controls cannot be read"}
	}
	control, err := protect.Find(document, options.Control)
	switch {
	case err != nil:
		return nil, file, refusal{Failed, "that encryption control is not registered"}
	case control.State != protect.Active:
		return nil, file, refusal{Failed, "that encryption control is retired; choose an active one"}
	case control.Generation != options.Generation:
		return nil, file, refusal{Failed, "the control's key generation changed; choose it again"}
	}
	reference := filepath.Base(control.Command)
	return &ShareEncryptionView{Control: control.Name, Reference: reference, Generation: control.Generation, Retention: control.Retain}, file, noRefusal
}

// shareProjects are the team projects a Send can reach now: the signed-in
// hub's configured projects.
func (a *App) shareProjects() []string {
	if _, _, err := a.hub.SignedIn(); err != nil {
		return []string{}
	}
	status := a.hub.Status()
	if status.Config == nil {
		return []string{}
	}
	return slices.Clone(status.Config.Projects)
}

// teamBindingParts is the signed-in connection a Send is bound to.
func (a *App) teamBindingParts() string {
	client, session, err := a.hub.SignedIn()
	if err != nil {
		return ""
	}
	return a.teamConnectionBinding(client, session) + "|" + session.Issuer + "|" + session.Subject
}

// bindShareSend binds a Send: a redacted report file, a signed-in session
// allowed to add files to the named project, and the resource it becomes
// the next revision of.
func (a *App) bindShareSend(ctx context.Context, share *reportshare.Share, options ReportShareOptions, display *ReportShareReview, notReady func(string)) (*teamBinding, string, refusal) {
	switch {
	case !share.Redacted:
		notReady("only a redacted report with nothing unresolved is sent")
	case share.Folder() || options.Encrypt != nil:
		notReady("a Send holds the report file alone; export the rest locally")
	}
	client, session, declined := a.signedIn()
	if declined.state != "" {
		notReady("sign in to the customer hub to send")
		return nil, "", noRefusal
	}
	status := a.hub.Status()
	if status.Config == nil || !slices.Contains(status.Config.Projects, options.Project) {
		notReady("choose a team project to send to")
		return nil, "", noRefusal
	}
	name, _ := a.hubTeamLabel(status.ConfigPath)
	display.Destination.Team = cmp.Or(name, hubAddress(a))
	if !session.Allows("evidence.write") {
		notReady("your role in " + options.Project + " cannot add files")
	}
	resource := shareResource(share.Files[0].Name)
	history, err := client.GetLifecycle(ctx, options.Project)
	if err != nil {
		return nil, "", refusal{hubReadState(err), "the project's history cannot be read: " + err.Error()}
	}
	parents := []string{}
	if held := findResource(teamResources(history), resource); held != nil {
		if len(held.Tips) != 1 {
			notReady(resource + " has unresolved revisions; resolve them in Team first")
		} else {
			parents = []string{held.Tips[0]}
		}
	}
	if pending := a.pendingTeamRevision(session, options.Project, resource); pending != "" {
		notReady("a previous send is unconfirmed; check its status before sending again")
	}
	return &teamBinding{project: options.Project, data: share.Files[0].Data, resource: resource, parents: parents, head: history.Head, kind: "revision"}, resource, noRefusal
}

// shareResource is the team resource a sent report file is kept under: its
// name in lowercase letters, digits and hyphens.
func shareResource(name string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			b.WriteRune(r)
			dash = false
		case !dash && b.Len() > 0:
			b.WriteByte('-')
			dash = true
		}
	}
	resource := strings.Trim(b.String(), "-")
	if len(resource) > 60 {
		resource = strings.Trim(resource[:60], "-")
	}
	if !hubprotocol.ValidProject(resource) {
		return "shared-report"
	}
	return resource
}

func executeReportShare(a *App, ctx context.Context, bound *boundAction, decisions ReviewDecisions) ReviewedActionResult {
	share := bound.reportShare
	if share.team != nil {
		result := executeTeam(a, ctx, &boundAction{action: bound.action, team: share.team, executionReview: bound.executionReview}, decisions)
		if result.Outcome == ActionCompleted {
			result.ReportShare = &ReportShareOutcome{Name: share.share.Files[0].Name, Project: share.team.project, Resource: share.resource}
			result.Reason = a.recordShare(ctx, bound, share, "customer-hub")
		}
		return result
	}
	result := ReviewedActionResult{Outcome: ActionRefused}
	destination, err := artifactpath.Destination(share.path)
	if err != nil {
		result.refuse(Failed, "the output must be written outside retained evidence")
		return result
	}
	if _, err := os.Lstat(destination); !errors.Is(err, fs.ErrNotExist) {
		result.refuse(Failed, "something is already there; choose a new name")
		return result
	}
	switch {
	case share.encrypt != nil:
		sources, err := share.packageSources(ctx)
		if err != nil {
			result.refuse(Failed, err.Error())
			return result
		}
		if _, err := share.encrypt.PackSources(ctx, share.control, uint64(share.gen), sources, destination, a.now()); err != nil {
			if errors.Is(err, protect.ErrGenerationChanged) {
				result.refuse(Failed, "the control's key generation changed; nothing was written")
			} else {
				result.refuse(Failed, "the package could not be written; a package that cannot be completed is removed")
			}
			return result
		}
	case share.share.Folder() || share.derived != nil:
		if written, err := share.writeFolder(ctx, destination); err != nil {
			result.refuse(Failed, err.Error())
			if written {
				result.ReportShare = &ReportShareOutcome{Name: markIncomplete(destination), Incomplete: true}
			}
			return result
		}
	default:
		data := share.share.Files[0].Data
		if err := operation.WriteNewFile(destination, data, "cannot create the file", "cannot write the file"); err != nil {
			result.refuse(Failed, "the report must be written to a new file in a folder this account can write")
			return result
		}
		if back, err := os.ReadFile(destination); err != nil || !bytes.Equal(back, data) {
			result.refuse(Failed, "the written report could not be verified; it is incomplete")
			result.ReportShare = &ReportShareOutcome{Name: markIncomplete(destination), Incomplete: true}
			return result
		}
	}
	result.State, result.Outcome = Completed, ActionCompleted
	result.ReportShare = &ReportShareOutcome{Name: filepath.Base(destination), Output: a.rememberShareOutput(destination)}
	result.Reason = a.recordShare(ctx, bound, share, "local-file")
	return result
}

// writeFolder writes a folder output: every generated file, then the
// original evidence through its own exporter. written says something was
// written before it failed.
func (s *reportShareBinding) writeFolder(ctx context.Context, destination string) (bool, error) {
	if err := os.Mkdir(destination, 0o700); err != nil {
		return false, errors.New("the output folder could not be created")
	}
	for _, file := range s.share.Files {
		path := filepath.Join(destination, filepath.FromSlash(file.Name))
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			return true, errors.New("the output could not be written; it is incomplete")
		}
		if err := operation.WriteNewFile(path, file.Data, "cannot create a file", "cannot write a file"); err != nil {
			return true, errors.New("the output could not be written; it is incomplete")
		}
	}
	if s.share.Original {
		if _, err := s.packet.ExportDocumentReview(ctx, filepath.Join(destination, "Original evidence"), s.authored); err != nil {
			return true, errors.New("the original evidence could not be written; the output is incomplete")
		}
	}
	if s.derived != nil {
		if _, err := redact.Export(ctx, redact.ExportRequest{ReviewPath: s.derived.review, LocalState: s.derived.private, Approval: s.derived.identity,
			Output: filepath.Join(destination, derivedTestName)}); err != nil {
			return true, errors.New("the derived test could not be generated; the output is incomplete")
		}
	}
	return true, nil
}

// packageSources are the files an encrypted package holds, in memory.
func (s *reportShareBinding) packageSources(ctx context.Context) ([]protect.Source, error) {
	sources := []protect.Source{}
	for _, file := range s.share.Files {
		sources = append(sources, protect.Source{Name: file.Name, Data: file.Data})
	}
	if s.share.Original {
		files, err := s.packet.DocumentReviewFiles(ctx, s.authored)
		if err != nil {
			return nil, errors.New("the original evidence could not be read")
		}
		for name, data := range files {
			sources = append(sources, protect.Source{Name: "Original evidence/" + name, Data: data})
		}
	}
	if s.derived != nil {
		// The derived test is generated where its private state is kept,
		// read into the package, and removed.
		stage, err := os.MkdirTemp(s.derived.private, ".share-derived-")
		if err != nil {
			return nil, errors.New("the derived test could not be generated")
		}
		defer os.RemoveAll(stage)
		output := filepath.Join(stage, derivedTestName)
		if _, err := redact.Export(ctx, redact.ExportRequest{ReviewPath: s.derived.review, LocalState: s.derived.private, Approval: s.derived.identity, Output: output}); err != nil {
			return nil, errors.New("the derived test could not be generated")
		}
		collected, _, err := protect.Collect([]string{output})
		if err != nil {
			return nil, errors.New("the derived test could not be read")
		}
		sources = append(sources, collected...)
	}
	return sources, nil
}

// markIncomplete renames a partly written output so it never reads as an
// export, and answers the name it now has.
func markIncomplete(path string) string {
	for i := 1; i < 100; i++ {
		marked := path + " (incomplete)"
		if i > 1 {
			marked = path + " (incomplete " + strconv.Itoa(i) + ")"
		}
		if _, err := os.Lstat(marked); !errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if os.Rename(path, marked) != nil {
			break
		}
		return filepath.Base(marked)
	}
	return filepath.Base(path)
}

// Destinations chosen for a share, and outputs written by one, are held in
// this process under opaque handles: the window names neither path.
type shareHandles struct {
	destinations map[string]heldPlace
	outputs      map[string]heldPlace
	seq          int
}

// heldPlace is one place a handle stands for: the path, whether a folder
// was asked for, and the name the save dialog offered.
type heldPlace struct {
	path   string
	name   string
	folder bool
	seq    int
}

const maxShareHandles = 64

// holdShare keeps a place under a new handle; a full table forgets its
// oldest place first.
func (a *App) holdShare(outputs bool, place heldPlace) string {
	a.shareMu.Lock()
	defer a.shareMu.Unlock()
	if a.shareHandles.destinations == nil {
		a.shareHandles = shareHandles{destinations: map[string]heldPlace{}, outputs: map[string]heldPlace{}}
	}
	held := a.shareHandles.destinations
	if outputs {
		held = a.shareHandles.outputs
	}
	if len(held) >= maxShareHandles {
		oldest := ""
		for handle, place := range held {
			if oldest == "" || place.seq < held[oldest].seq {
				oldest = handle
			}
		}
		delete(held, oldest)
	}
	var raw [16]byte
	rand.Read(raw[:])
	handle := hex.EncodeToString(raw[:])
	a.shareHandles.seq++
	place.seq = a.shareHandles.seq
	held[handle] = place
	return handle
}

func (a *App) shareDestination(handle string) (heldPlace, bool) {
	a.shareMu.Lock()
	defer a.shareMu.Unlock()
	place, ok := a.shareHandles.destinations[handle]
	return place, ok
}

func (a *App) rememberShareOutput(path string) string {
	return a.holdShare(true, heldPlace{path: path})
}

// ShareDestinationRequest asks for where a share's output is written: a new
// file, or a new folder when the output is several files or a package.
type ShareDestinationRequest struct {
	Context RequestContext `json:"context"`
	Name    string         `json:"name"`
	Folder  bool           `json:"folder,omitzero"`
}

// ShareDestinationResult is the chosen place, as values, and its handle.
type ShareDestinationResult struct {
	State       State          `json:"state"`
	Reason      string         `json:"reason,omitzero"`
	Context     RequestContext `json:"context"`
	Destination string         `json:"destination,omitzero"`
	Name        string         `json:"name,omitzero"`
	Location    string         `json:"location,omitzero"`
}

func (r *ShareDestinationResult) refuse(state State, reason string) {
	r.State, r.Reason = state, reason
}

// ChooseShareDestination presents the host's save dialog, offering the
// output's own name. Choosing writes nothing: the final Export writes there,
// and refuses a place something is already at.
func (a *App) ChooseShareDestination(request ShareDestinationRequest) ShareDestinationResult {
	return run(a, true, false, func(ctx context.Context) ShareDestinationResult {
		result := ShareDestinationResult{Context: request.Context}
		title := "Export report"
		if request.Folder {
			title = "Export package"
		}
		path, declined := a.chooseNamedDestination(ctx, title, request.Name)
		if path == "" {
			result.refuse(declined.state, declined.reason)
			return result
		}
		if !filepath.IsAbs(path) {
			result.refuse(Failed, "the save dialog did not name a place on this computer")
			return result
		}
		result.State = Completed
		result.Destination = a.holdShare(false, heldPlace{path: path, name: request.Name, folder: request.Folder})
		result.Name, result.Location = filepath.Base(path), filepath.Base(filepath.Dir(path))
		return result
	})
}

// SharedOutputRequest names one output a share wrote in this process.
type SharedOutputRequest struct {
	Output string `json:"output"`
	// Folder shows it in the file manager instead of opening it.
	Folder bool `json:"folder,omitzero"`
}

// FileOpener opens a file with the application the host associates with it.
type FileOpener interface {
	OpenFile(path string) error
}

// OpenSharedOutput opens an output a share wrote, or shows it in its folder.
// Only outputs this process wrote are reached.
func (a *App) OpenSharedOutput(request SharedOutputRequest) RevealResult {
	return run(a, false, false, func(context.Context) RevealResult {
		a.shareMu.Lock()
		place, ok := a.shareHandles.outputs[request.Output]
		path := place.path
		a.shareMu.Unlock()
		if !ok {
			return RevealResult{State: Failed, Reason: "that output was not written in this window"}
		}
		if _, err := os.Lstat(path); err != nil {
			return RevealResult{State: Failed, Reason: "the output is no longer where it was written"}
		}
		if request.Folder {
			if err := a.revealer()(path); err != nil {
				return RevealResult{State: Failed, Reason: "the file manager could not be opened"}
			}
			return RevealResult{State: Completed}
		}
		opener, ok := a.chooser.(FileOpener)
		if !ok || opener.OpenFile(path) != nil {
			return RevealResult{State: Failed, Reason: "this computer cannot open the file"}
		}
		return RevealResult{State: Completed}
	})
}

// A share that completed is recorded in its report's history: what was
// written or sent, how, and whether it was redacted. Nothing it holds is a
// value or a path.

// ReportShareItem is the share history of one report: each completed share
// is one revision.
const ReportShareItem ItemKind = "report-share"

// ReportShareSchema is the contract of one recorded share.
const ReportShareSchema = "readmit-report-share/v1"

type reportShareRecord struct {
	Schema       string `json:"schema"`
	Report       string `json:"report"`
	Revision     string `json:"revision"`
	Actor        string `json:"actor"`
	At           string `json:"at"`
	Destination  string `json:"destination"`
	Output       string `json:"output"`
	Format       string `json:"format"`
	Redacted     bool   `json:"redacted"`
	SourceValues bool   `json:"source_values"`
	Encrypted    bool   `json:"encrypted"`
	Original     bool   `json:"original"`
}

func decodeReportShare(data []byte) (reportShareRecord, error) {
	var record reportShareRecord
	invalid := errors.New("the report share record cannot be read")
	if len(data) > catalog.MaxMemberBytes || json.Unmarshal(data, &record, json.RejectUnknownMembers(true)) != nil || record.Schema != ReportShareSchema ||
		!catalog.ValidID(record.Report) || record.Revision == "" || strings.TrimSpace(record.Actor) == "" ||
		!slices.Contains([]string{"local-file", "customer-hub"}, record.Destination) ||
		!slices.Contains([]string{ShareOutputFile, ShareOutputFolder, ShareOutputPackage}, record.Output) || !slices.Contains(reportShareFormats, record.Format) {
		return reportShareRecord{}, invalid
	}
	if _, err := time.Parse(time.RFC3339, record.At); err != nil {
		return reportShareRecord{}, invalid
	}
	return record, nil
}

func readReportShareItem(_ *loadedCatalog, _ catalog.Item, paths map[string]string) (view, error) {
	data, err := boundedFile(paths[string(ReportShareItem)], catalog.MaxMemberBytes)
	if err != nil {
		return view{}, err
	}
	_, err = decodeReportShare(data)
	return view{}, err
}

// ReportShareEntry is one recorded share of a report version.
type ReportShareEntry struct {
	Version      string `json:"version"`
	At           string `json:"at"`
	Actor        string `json:"actor"`
	Destination  string `json:"destination"`
	Output       string `json:"output"`
	Format       string `json:"format"`
	Redacted     bool   `json:"redacted"`
	SourceValues bool   `json:"source_values"`
	Encrypted    bool   `json:"encrypted"`
}

// reportShares are the recorded shares of one report, newest first, and
// the history item they are recorded in.
func (c *loadedCatalog) reportShares(report string) ([]ReportShareEntry, *catalog.Item) {
	entries := []ReportShareEntry{}
	var history *catalog.Item
	for i := range c.document.Items {
		item := c.document.Items[i]
		if item.Kind != string(ReportShareItem) || c.removed(item) {
			continue
		}
		for _, revision := range item.Revisions {
			for _, member := range revision.Members {
				data, err := boundedFile(c.store.Path(member), catalog.MaxMemberBytes)
				if err != nil {
					continue
				}
				record, err := decodeReportShare(data)
				if err != nil || record.Report != report {
					continue
				}
				history = &c.document.Items[i]
				entries = append(entries, ReportShareEntry{Version: record.Revision, At: record.At, Actor: record.Actor, Destination: record.Destination,
					Output: record.Output, Format: record.Format, Redacted: record.Redacted, SourceValues: record.SourceValues, Encrypted: record.Encrypted})
			}
		}
	}
	slices.Reverse(entries)
	return entries, history
}

// recordShare records a completed share in its report's history and says
// why it could not, which the result carries beside what was written.
func (a *App) recordShare(ctx context.Context, bound *boundAction, share *reportShareBinding, destination string) string {
	output := ShareOutputFile
	switch {
	case share.encrypt != nil:
		output = ShareOutputPackage
	case share.share.Folder() || share.derived != nil:
		output = ShareOutputFolder
	}
	record := reportShareRecord{Schema: ReportShareSchema, Report: share.item, Revision: share.revision, Actor: a.reviewerName(), At: catalog.Stamp(a.now()),
		Destination: destination, Output: output, Format: share.options.Format, Redacted: share.share.Redacted, SourceValues: share.share.SourceValues,
		Encrypted: share.encrypt != nil, Original: share.share.Original}
	unrecorded := "the share was completed; the report's history could not record it"
	data, err := encodeMember(record)
	if err != nil {
		return unrecorded
	}
	loaded, _ := a.loadCatalog(ctx, bound.origin.Context, true)
	if loaded == nil {
		return unrecorded
	}
	intent := ""
	if bound.executionReview != nil {
		intent = bound.executionReview.intent
	}
	sum := sha256.Sum256([]byte("report-share\x00" + intent))
	draft := catalog.Draft{Kind: string(ReportShareItem), Intent: "report-share-" + hex.EncodeToString(sum[:16]), Digest: digestOf(data),
		Author: a.reviewerName(), Members: []catalog.Staged{{Role: string(ReportShareItem), File: "share.json", Data: data}}}
	if _, history := loaded.reportShares(share.item); history != nil {
		draft.ItemID, draft.Base = history.ID, history.RevisionLabel()
	}
	if _, err := loaded.store.Save(draft, verifierFor(ReportShareItem), catalog.Options{Now: a.now, Fault: a.saveFault}); err != nil {
		return unrecorded
	}
	return ""
}
