package scenariogen

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json/v2"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/bharm16/readmit/internal/artifactdir"
	"github.com/bharm16/readmit/internal/artifactpath"
	"github.com/bharm16/readmit/internal/bundle"
	"github.com/bharm16/readmit/internal/hl7"
	"github.com/bharm16/readmit/internal/scenario"
)

// Manifest is the completion record. Intended arrivals are a generator plan,
// never observations, an executed delay or an assertion about a real target.
type Manifest struct {
	Schema  string   `json:"schema"`
	State   string   `json:"state"`
	Inputs  Plan     `json:"inputs"`
	Streams []Stream `json:"streams"`
}
type Stream struct {
	Row              string    `json:"row"`
	Variant          string    `json:"variant"`
	File             string    `json:"file"`
	SHA256           string    `json:"sha256"`
	Bytes            int       `json:"bytes"`
	IntendedArrivals []Arrival `json:"intended_arrivals"`
}

// Family is the material of one plan, produced in memory: every bounded
// stream's manifest row and its framed bytes. Producing one is a pure
// function of the plan — the same plan is the same family on any machine —
// and it reads and writes nothing, so a check can hold generated bytes
// without a scratch directory of its own.
type Family struct {
	// Manifest is the completion record a write of this family installs as
	// generation.json.
	Manifest Manifest
	streams  [][]byte
}

// Stream returns the framed MLLP bytes of the stream whose manifest row is
// f.Manifest.Streams[i].
func (f Family) Stream(i int) []byte { return f.streams[i] }

// Produce validates the plan and materializes every bounded stream in memory,
// creating nothing. Cancellation is observed between streams, and a family
// past the generator's byte bound is refused.
func Produce(ctx context.Context, data []byte) (Family, error) {
	if err := ctx.Err(); err != nil {
		return Family{}, err
	}
	p, err := Decode(data)
	if err != nil {
		return Family{}, err
	}
	family, _, err := produce(ctx, p)
	return family, err
}

// produce materializes the decoded plan's streams and reports the timeline
// its template previews on, whose profile version and base time a generated
// case's provenance records.
func produce(ctx context.Context, p Plan) (Family, scenario.Timeline, error) {
	d, timeline, err := readTemplate(p.Template)
	if err != nil {
		return Family{}, scenario.Timeline{}, err
	}
	family := Family{Manifest: Manifest{Schema: "readmit-scenario-generation/v1", State: "complete", Inputs: p, Streams: []Stream{}}}
	total := 0
	for _, r := range p.Rows {
		for _, v := range p.Variants {
			if err := ctx.Err(); err != nil {
				return Family{}, scenario.Timeline{}, err
			}
			s, err := generate(p, d, r, v)
			if err != nil {
				return Family{}, scenario.Timeline{}, err
			}
			total += len(s.data)
			if total > 16<<20 {
				return Family{}, scenario.Timeline{}, errors.New("generated family exceeds 16 MiB")
			}
			sum := sha256.Sum256(s.data)
			family.Manifest.Streams = append(family.Manifest.Streams, Stream{Row: r.ID, Variant: v.ID, File: fmt.Sprintf("stream-%03d.mllp", len(family.streams)+1), SHA256: hex.EncodeToString(sum[:]), Bytes: len(s.data), IntendedArrivals: s.arrivals})
			family.streams = append(family.streams, s.data)
		}
	}
	return family, timeline, nil
}

// WrittenCase reports one generated case the package wrote beside its
// streams: the completion record the generation directory retains, how many
// streams it holds, and the identity of the case bundle together with the
// generator inputs its provenance declares.
type WrittenCase struct {
	// Record is the generation.json bytes installed in the generation
	// directory.
	Record []byte
	// Streams is how many bounded streams the family held.
	Streams int
	// Identity is the identity the case bundle reports when it is opened.
	Identity string
	// Seed and GeneratorVersion are the plan's declared generator inputs.
	Seed             uint64
	GeneratorVersion string
	// ProfileVersion and BaseTime are the lifecycle profile and the declared
	// instant the plan's template previews on.
	ProfileVersion string
	BaseTime       time.Time
}

// WriteCase is the one operation that writes a generated case from a
// generator plan: it materializes the plan's streams in memory, writes them
// with their completion record into the new directory generation names, and
// writes the new case bundle casePath names from those same bytes. The
// provenance decision is made here, once: the case is generated from the
// plan's declared generator inputs — its seed and generator version, and the
// template's profile version and base time — and no caller reimplements it.
func WriteCase(ctx context.Context, data []byte, generation, casePath string) (WrittenCase, error) {
	if err := ctx.Err(); err != nil {
		return WrittenCase{}, err
	}
	p, err := Decode(data)
	if err != nil {
		return WrittenCase{}, err
	}
	family, timeline, err := produce(ctx, p)
	if err != nil {
		return WrittenCase{}, err
	}
	record, err := write(ctx, generation, family)
	if err != nil {
		return WrittenCase{}, err
	}
	inputs := make([]bundle.Input, 0, len(family.streams))
	for _, stream := range family.streams {
		inputs = append(inputs, bundle.Input{Data: stream, Options: hl7.Options{Format: hl7.MLLP, Terminator: hl7.CR}})
	}
	written, err := bundle.WriteContext(ctx, casePath, inputs, bundle.Provenance{Mode: bundle.Generated, Generator: &bundle.GeneratorInputs{
		Seed:             p.Seed,
		BaseTime:         timeline.BaseTime.UTC(),
		GeneratorVersion: p.GeneratorVersion,
		ProfileVersion:   string(timeline.Profile),
	}})
	if err != nil {
		return WrittenCase{}, err
	}
	return WrittenCase{
		Record:           record,
		Streams:          len(family.Manifest.Streams),
		Identity:         written.Identity,
		Seed:             p.Seed,
		GeneratorVersion: p.GeneratorVersion,
		ProfileVersion:   string(timeline.Profile),
		BaseTime:         timeline.BaseTime,
	}, nil
}

// Write materializes the plan's streams in memory and writes them, with
// their completion record, into the new directory path names. Completion is
// installed last, and the directory and the folder naming it are synced, so
// what reads as complete survives a power loss. Cancellation or I/O failure
// retains incomplete output; retry requires a new destination, never an
// overwrite or partial resume.
func Write(ctx context.Context, path string, data []byte) ([]byte, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	p, err := Decode(data)
	if err != nil {
		return nil, err
	}
	family, _, err := produce(ctx, p)
	if err != nil {
		return nil, err
	}
	return write(ctx, path, family)
}

// write materializes the family into the new directory path names and answers
// the completion record bytes it installed.
func write(ctx context.Context, path string, family Family) ([]byte, error) {
	encoded, err := json.Marshal(family.Manifest, json.Deterministic(true))
	if err != nil {
		return nil, errors.New("cannot encode generation record")
	}
	encoded = append(encoded, '\n')
	path, err = artifactpath.Destination(path)
	if err != nil {
		return nil, err
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if err := os.Mkdir(path, 0700); err != nil {
		return nil, errors.New("generation destination must be new with an existing writable parent")
	}
	root, err := os.OpenRoot(path)
	if err != nil {
		return nil, errors.New("cannot open generation output; incomplete output retained")
	}
	defer root.Close()
	for i := range family.streams {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if err := writeFile(root, family.Manifest.Streams[i].File, family.streams[i]); err != nil {
			return nil, err
		}
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if err := writeFile(root, ".generation.json.incomplete", encoded); err != nil {
		return nil, err
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if err := root.Rename(".generation.json.incomplete", "generation.json"); err != nil {
		return nil, errors.New("cannot finish generation record; incomplete output retained")
	}
	// Every file is already synced. Sync the directory naming them and the
	// folder naming the directory, so the completed generation, its record
	// and its entry all survive a power loss.
	if err := artifactdir.SyncDirectory(root, "."); err != nil {
		return nil, errors.New("cannot sync the generation output; a power loss could still lose it")
	}
	parent, err := os.OpenRoot(filepath.Dir(path))
	if err != nil {
		return nil, errors.New("cannot sync the generation output; a power loss could still lose it")
	}
	defer parent.Close()
	if err := artifactdir.SyncDirectory(parent, "."); err != nil {
		return nil, errors.New("cannot sync the generation output; a power loss could still lose it")
	}
	return encoded, nil
}
func writeFile(root *os.Root, name string, data []byte) error {
	err := artifactdir.WriteFile(root, name, data)
	if errors.Is(err, artifactdir.ErrCreateFile) {
		return errors.New("cannot create generation file; incomplete output retained")
	}
	if err != nil {
		return errors.New("cannot write generation file; incomplete output retained")
	}
	return nil
}
